list(

  age__agep = list(
    AHS = list(
      groups = 1,
      levels = "Min: 0, Median: 39, Mean: 39.9, Max: 85",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 38, Mean: 39.1, Max: 96",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2026-06-24 10:51:28.789413"),

  bedrooms__bdsp = list(
    AHS = list(
      groups = 1,
      levels = "Min: 0, Median: 3, Mean: 2.76, Max: 5",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 3, Mean: 2.76, Max: 8",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2026-06-24 10:51:28.789593"),

  bld__bld = list(
    AHS = list(
      groups = 1:10,
      levels = c("Mobile home or trailer", "One-family house, detached", "One-family house, attached", "2 apartments", "3 to 4 apartments", "5 to 9 apartments", "10 to 19 apartments", "20 to 49 apartments", "50 or more apartments", "Boat, RV, van, etc."),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:10,
      levels = c("Mobile home or trailer", "One-family house detached", "One-family house attached", "2 Apartments", "3-4 Apartments", "5-9 Apartments", "10-19 Apartments", "20-49 Apartments", "50 or more apartments", "Boat, RV, van, etc."),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.789685"),

  citshp__cit = list(
    AHS = list(
      groups = 1:5,
      levels = c("Native, born in U.S.", "Native, born in Puerto Rico or U.S. outlying area", "Native born abroad of U.S. parent(s)", "Foreign born, U.S. citizen by naturalization", "Foreign born, not a U.S. citizen"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:5,
      levels = c("Born in the United States", "Born in Puerto Rico, Guam, the U.S. Virgin Islands, or Northern Marianas", "Born abroad of U.S. citizen parent or parents", "U.S. citizen by naturalization", "Not a U.S. citizen"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.789776"),

  elecamt__elep = list(
    AHS = list(
      groups = 1,
      levels = "Min: 0, Median: 100, Mean: 107, Max: 450",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 120, Mean: 140.7, Max: 650",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2026-06-24 10:51:28.789949"),

  elecamt_flag__elefp = list(
    AHS = list(
      groups = c(2, 1, 2, 3),
      levels = c("Occupied home: provided free of charge", "Occupied or vacant home: included in the rent, site rent, condominium fee, other fee, or other utility bill", "Unit does not use electricity", "Valid amount"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:3,
      levels = c("Included in rent or in condo fee", "No charge or electricity not used", "Valid monthly electricity cost in ELEP"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.790033"),

  enroll__sch = list(
    AHS = list(
      groups = 1:2,
      levels = c("Yes", "No"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(2, 2, 1, 1),
      levels = c("Less than 3 years old", "No, has not attended in the last 3 months", "Yes, public school or public college", "Yes, private school or college or home school"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.790116"),

  fincp__fincp = list(
    AHS = list(
      groups = 1,
      levels = "Min: -5000, Median: 49000, Mean: 72400, Max: 3876000",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: -15350, Median: 41400, Mean: 70500, Max: 2940000",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2026-06-24 10:51:28.790201"),

  fridge__refr = list(
    AHS = list(
      groups = 1:2,
      levels = c("Yes", "No"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:2,
      levels = c("Yes", "No"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.790284"),

  fs__fs = list(
    AHS = list(
      groups = 1:2,
      levels = c("Yes", "No"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:2,
      levels = c("Yes", "No"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.790366"),

  gasamt__gasp = list(
    AHS = list(
      groups = 1,
      levels = "Min: 0, Median: 20, Mean: 37.94, Max: 470",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 10, Mean: 42.25, Max: 630",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2026-06-24 10:51:28.790448"),

  gasamt_flag__gasfp = list(
    AHS = list(
      groups = c(1, 2, 1, 3),
      levels = c("Occupied home: provided free of charge", "Occupied or vacant home: included in the rent, site rent, condominium fee, other fee, or other utility bill", "Unit does not use gas", "Valid amount"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(2, 2, 1, 3),
      levels = c("Included in rent or in condo fee", "Included in electricity payment", "No charge or gas not used", "Valid monthly gas cost in GASP"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.790535"),

  grad__schl = list(
    AHS = list(
      groups = c(1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 11, 11, 12, 13, 14, 15),
      levels = c("Age 17 or younger", "Less than 1st grade", "1st, 2nd, 3rd, or 4th grade", "5th or 6th grade", "7th or 8th grade", "9th grade", "10th grade", "11th grade", "12th grade, no diploma", "High school graduate - high school diploma or equivalent (for example: GED)", "Some college but no degree", "Diploma or certificate from a vocational, technical, trade or business school beyond the high school level", "Associate degree in college - occupational / vocational program", "Associate degree in college - academic program", "Bachelor's degree (for example: BA, AB, BS)", "Master's degree (for example: MA, MS, MEng, MEd, MSW, MBA)", "Professional school degree (for example: MD, DDS, DVM, LLB, JD)", "Doctorate degree (for example: PhD, EdD)"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 4, 4, 5, 6, 7, 8, 9, 9, 10, 10, 11, 12, 13, 14, 15),
      levels = c("Less than 3 years old", "No schooling completed", "Nursery school, preschool", "Kindergarten", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8", "Grade 9", "Grade 10", "Grade 11", "12th grade - no diploma", "Regular high school diploma", "GED or alternative credential", "Some college, but less than 1 year", "1 or more years of college credit, no degree", "Associate's degree", "Bachelor's degree", "Master's degree", "Professional degree beyond a bachelor's degree", "Doctorate degree"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2026-06-24 10:51:28.790614"),

  grandhh__npp = list(
    AHS = list(
      groups = 1:2,
      levels = c("Yes", "No"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 2:1,
      levels = c("Not a grandparent headed household with no parent present", "Grandparent headed household with no parent present"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.790696"),

  heatfuel__hfl = list(
    AHS = list(
      groups = c(1, 2, 3, 4, 4, 5, 6, 7, 8, 9),
      levels = c("Electricity", "Piped gas", "Liquefied petroleum gas", "Fuel oil", "Kerosene or other liquid fuel", "Coal or coke", "Wood", "Solar energy", "Other", "None"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(2, 3, 1, 4, 5, 6, 7, 8, 9),
      levels = c("Utility gas", "Bottled, tank, or LP gas", "Electricity", "Fuel oil, kerosene, etc.", "Coal or coke", "Wood", "Solar energy", "Other fuel", "No fuel used"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.790775"),

  hincp__hincp = list(
    AHS = list(
      groups = 1,
      levels = "Min: -5000, Median: 60000, Mean: 84900, Max: 3876000",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: -15350, Median: 65700, Mean: 92400, Max: 2940000",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2026-06-24 10:51:28.79085"),

  hshldtype__hht = list(
    AHS = list(
      groups = 1:7,
      levels = c("Married-couple family household", "Other family household: male householder, no wife present", "Other family household: female householder, no husband present", "Nonfamily household: male householder, living alone", "Nonfamily household: male householder, not living alone", "Nonfamily household: female householder, living alone", "Nonfamily household: female householder, not living alone"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:7,
      levels = c("Married couple household", "Other family household: Male householder, no spouse present", "Other family household: Female householder, no spouse present", "Nonfamily household: Male householder: Living alone", "Nonfamily household: Male householder: Not living alone", "Nonfamily household: Female householder: Living alone", "Nonfamily household: Female householder: Not living alone"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.790931"),

  intp__intp = list(
    AHS = list(
      groups = 1,
      levels = "Min: -5000, Median: 0, Mean: 1570, Max: 571000",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: -2626, Median: 0, Mean: 1815, Max: 474000",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2026-06-24 10:51:28.791011"),

  lotsize__acr = list(
    AHS = list(
      groups = c(1, 2, 2, 2, 2, 3, 3, 4),
      levels = c("Multi-unit building", "Less than 1/8 acre", "1/8 up to 1/4 acre", "1/4 up to 1/2 acre", "1/2 up to 1 acre", "1 up to 5 acres", "5 up to 10 acres", "10 acres or more"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:4,
      levels = c("Not a one-family house or mobile home", "House on less than one acre", "House on one to less than ten acres", "House on ten or more acres"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2026-06-24 10:51:28.791093"),

  mar__mar = list(
    AHS = list(
      groups = c(1, 2, 2, 3, 4, 5, 1),
      levels = c("Age under 14 or over 85", "Married, spouse present", "Married, spouse absent", "Widowed", "Divorced", "Separated", "Never married"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(2, 3, 4, 5, 1),
      levels = c("Married", "Widowed", "Divorced", "Separated", "Never married or under 15 years old"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.791171"),

  marketval__valp = list(
    AHS = list(
      groups = 1,
      levels = "Min: 0, Median: 198000, Mean: 304600, Max: 10000000",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 120000, Mean: 214000, Max: 7680000",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2026-06-24 10:51:28.791252"),

  mil__mil = list(
    AHS = list(
      groups = 1:3,
      levels = c("Now on active duty", "Served on active duty in the past", "Never served in military"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(3, 1, 2, 1, 3),
      levels = c("Less than 17 years old", "Now on active duty", "On active duty in the past, but not now", "Only on active duty for training in Reserves / National Guard", "Never served in the military"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.791333"),

  miscpmt__mrgi = list(
    AHS = list(
      groups = 1:3,
      levels = c("No mortgage", "Yes", "No"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:3,
      levels = c("Not owned or being bought / Not mortgaged", "Yes, insurance included in payment", "No, insurance paid separately or no insurance"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.791418"),

  move__mv = list(
    AHS = list(
      groups = 1:7,
      levels = c("Less than 1993", "[1993 to 2004)", "[2004 to 2013)", "[2013 to 2018)", "[2018 to 2020)", "[2020 to 2021)", "2021 or more"),
      breaks = c(1993, 2003, 2013, 2018, 2020, 2021),
      adj = ""),
    ACS = list(
      groups = 7:1,
      levels = c("12 months or less", "13 to 23 months", "2 to 4 years", "5 to 9 years", "10 to 19 years", "20 to 29 years", "30 years or more"),
      breaks = "",
      adj = "",
      agg = logical(0)
    ),
    ordered = TRUE,
    comment = "",
    modified = "2026-06-24 11:02:09.305263"),

  numpeople__np = list(
    AHS = list(
      groups = 1,
      levels = "Min: 0, Median: 2, Mean: 2.193, Max: 18",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 1, Median: 2, Mean: 2.47, Max: 20",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2026-06-24 10:51:28.791497"),

  numsubfam__psf = list(
    AHS = list(
      groups = 1:2,
      levels = c("Less than 1", "1 or more"),
      breaks = 1,
      adj = ""),
    ACS = list(
      groups = 1:2,
      levels = c("No subfamilies", "1 or more subfamilies"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2026-06-24 10:53:09.467004"),

  oilamt_flag__fulfp = list(
    AHS = list(
      groups = c(1, 2, 1, 3),
      levels = c("Occupied home: provided free of charge", "Occupied or vacant home: included in the rent, site rent, condominium fee, other fee, or other utility bill", "Unit does not use fuel oil", "Valid amount"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(2, 1, 3),
      levels = c("Included in rent or in condo fee", "No charge or fuel other than gas or electricity not used", "Valid annual fuel cost in FULP"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.79158"),

  pap__pap = list(
    AHS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 23.17, Max: 32700",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 27.75, Max: 24140",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2026-06-24 10:51:28.791664"),

  partner__partner = list(
    AHS = list(
      groups = 1:5,
      levels = c("Householder does not have an unmarried partner present", "Male householder, male partner", "Male householder, female partner", "Female householder, female partner", "Female householder, male partner"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:5,
      levels = c("No unmarried partner in household", "Male householder, male partner", "Male householder, female partner", "Female householder, female partner", "Female householder, male partner"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.791747"),

  pcare__ddrs = list(
    AHS = list(
      groups = 1:2,
      levels = c("Yes", "No"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(2, 1, 2),
      levels = c("Less than 5 years old", "Yes", "No"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.791827"),

  phear__dear = list(
    AHS = list(
      groups = 1:2,
      levels = c("Yes", "No"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:2,
      levels = c("Yes", "No"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.791913"),

  pmtamt__mrgp = list(
    AHS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 668, Max: 96800",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 560, Max: 7700",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2026-06-24 10:51:28.791994"),

  protaxamt__taxamt = list(
    AHS = list(
      groups = 1,
      levels = "Min: 0, Median: 49, Mean: 169.3, Max: 8300",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 975, Mean: 2243, Max: 22500",
      breaks = "",
      adj = "",
      agg = logical(0)
    ),
    ordered = "",
    comment = "",
    modified = "2026-06-24 10:51:28.792073"),

  race__rac1p = list(
    AHS = list(
      groups = c(1, 2, 3, 4, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6),
      levels = c("White only", "Black only", "American Indian, Alaska Native only", "Asian only", "Hawaiian, Pacific Islander only", "White / Black", "White / American Indian, Alaska Native", "White / Asian", "White / Hawaiian, Pacific Islander", "Black / American Indian, Alaska Native", "Black / Asian", "Black / Hawaiian, Pacific Islander", "American Indian, Alaska Native / Asian", "Asian / Hawaiian, Pacific Islander", "White / Black / American Indian, Alaska Native", "White / Black / Asian", "White / American Indian, Alaska Native / Asian", "White / Asian / Hawaiian, Pacific Islander", "White / Black / American Indian, Alaska Native / Asian", "Other combinations of 2 or 3 races"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 2, 3, 3, 3, 4, 5, 1, 6),
      levels = c("White alone", "Black or African American alone", "American Indian alone", "Alaska Native alone", "American Indian and Alaska Native tribes specified; or American Indian or Alaska Native, not specified and no other races", "Asian alone", "Native Hawaiian and Other Pacific Islander alone", "Some Other Race alone", "Two or More Races"),
      breaks = "",
      adj = "",
      agg = logical(0)
    ),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.792159"),

  rent__rntp = list(
    AHS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 401, Max: 11700",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 367, Max: 4000",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2026-06-24 10:51:28.79224"),

  retp__retp = list(
    AHS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 1740, Max: 707000",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 2640, Max: 210000",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2026-06-24 10:51:28.792323"),

  semp__semp = list(
    AHS = list(
      groups = 1,
      levels = "Min: -5000, Median: 0, Mean: 2350, Max: 1938000",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: -9700, Median: 0, Mean: 1698, Max: 516000",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2026-06-24 10:51:28.7924"),

  sex__sex = list(
    AHS = list(
      groups = 1:2,
      levels = c("Male", "Female"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:2,
      levels = c("Male", "Female"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.792483"),

  span__hisp = list(
    AHS = list(
      groups = 1:2,
      levels = c("Yes", "No"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
      levels = c("Not Spanish / Hispanic / Latino", "Mexican", "Puerto Rican", "Cuban", "Dominican", "Costa Rican", "Guatemalan", "Honduran", "Nicaraguan", "Panamanian", "Salvadoran", "Other Central American", "Argentinean", "Bolivian", "Chilean", "Colombian", "Ecuadorian", "Paraguayan", "Peruvian", "Uruguayan", "Venezuelan", "Other South American", "Spaniard", "All Other Spanish / Hispanic / Latino"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.792562"),

  ssip__ssip = list(
    AHS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 164, Max: 46400",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 217.4, Max: 27700",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2026-06-24 10:51:28.792639"),

  ssp__ssp = list(
    AHS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 2210, Max: 54000",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 2453, Max: 39100",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2026-06-24 10:51:28.792717"),

  taxpmt__mrgt = list(
    AHS = list(
      groups = 1:3,
      levels = c("No mortgage", "Yes", "No"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:3,
      levels = c("Not owned or being bought / Not mortgaged", "Yes, taxes included in payment", "No, taxes paid separately or taxes not required"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.792799"),

  tenure__ten = list(
    AHS = list(
      groups = 1:3,
      levels = c("Owned or being bought by someone in your household", "Rented", "Occupied without payment of rent"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 1, 2, 3),
      levels = c("Owned with mortgage or loan (include home equity loans)", "Owned free and clear", "Rented", "Occupied without payment of rent"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.792877"),

  totrooms__rmsp = list(
    AHS = list(
      groups = 1,
      levels = "Min: 1, Median: 6, Mean: 5.73, Max: 14",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 1, Median: 6, Mean: 5.89, Max: 20",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "Excludes bathrooms by design.",
    modified = "2026-06-24 10:51:28.792958"),

  wagp__wagp = list(
    AHS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 26800, Max: 587000",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 202, Mean: 26370, Max: 724000",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2026-06-24 10:51:28.793042"),

  wateramt_flag__watfp = list(
    AHS = list(
      groups = 1:3,
      levels = c("Occupied home: provided free of charge", "Occupied or vacant home: included in the rent, site rent, condominium fee, other fee, or other utility bill", "Valid amount"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(2, 1, 3),
      levels = c("Included in rent or in condo fee", "No charge", "Valid annual water cost in WATP"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2026-06-24 10:51:28.793121"),

  yrbuilt__yrblt = list(
    AHS = list(
      groups = c(1, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 11, 12, 12),
      levels = c("1919 or earlier", "1920 to 1929", "1930 to 1939", "1940 to 1949", "1950 to 1959", "1960 to 1969", "1970 to 1979", "1980 to 1989", "1990 to 1999", "2000 to 2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:12,
      levels = c("1939 or earlier", "1940 to 1949", "1950 to 1959", "1960 to 1969", "1970 to 1979", "1980 to 1989", "1990 to 1999", "2000 to 2009", "2010 to 2019", "2020", "2021", "2022"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2026-06-24 10:54:00.965254")
)
