list(

  age__agep = list(
    ASEC = list(
      groups = 1:82,
      levels = c("Under 1 year", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "85"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:82,
      levels = c("Less than 1", "[1 to 2)", "[2 to 3)", "[3 to 4)", "[4 to 5)", "[5 to 6)", "[6 to 7)", "[7 to 8)", "[8 to 9)", "[9 to 10)", "[10 to 11)", "[11 to 12)", "[12 to 13)", "[13 to 14)", "[14 to 15)", "[15 to 16)", "[16 to 17)", "[17 to 18)", "[18 to 19)", "[19 to 20)", "[20 to 21)", "[21 to 22)", "[22 to 23)", "[23 to 24)", "[24 to 25)", "[25 to 26)", "[26 to 27)", "[27 to 28)", "[28 to 29)", "[29 to 30)", "[30 to 31)", "[31 to 32)", "[32 to 33)", "[33 to 34)", "[34 to 35)", "[35 to 36)", "[36 to 37)", "[37 to 38)", "[38 to 39)", "[39 to 40)", "[40 to 41)", "[41 to 42)", "[42 to 43)", "[43 to 44)", "[44 to 45)", "[45 to 46)", "[46 to 47)", "[47 to 48)", "[48 to 49)", "[49 to 50)", "[50 to 51)", "[51 to 52)", "[52 to 53)", "[53 to 54)", "[54 to 55)", "[55 to 56)", "[56 to 57)", "[57 to 58)", "[58 to 59)", "[59 to 60)", "[60 to 61)", "[61 to 62)", "[62 to 63)", "[63 to 64)", "[64 to 65)", "[65 to 66)", "[66 to 67)", "[67 to 68)", "[68 to 69)", "[69 to 70)", "[70 to 71)", "[71 to 72)", "[72 to 73)", "[73 to 74)", "[74 to 75)", "[75 to 76)", "[76 to 77)", "[77 to 78)", "[78 to 79)", "[79 to 80)", "[80 to 85)", "85 or more"),
      breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 85),
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2022-08-29 15:48:04"),

  anycovnw__hicov = list(
    ASEC = list(
      groups = 1:2,
      levels = c("Covered", "Not covered"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:2,
      levels = c("With health insurance coverage", "No health insurance coverage"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2022-08-30 15:52:59"),

  asian__rac2p = list(
    ASEC = list(
      groups = 1:8,
      levels = c("Asian Indian", "Chinese", "Filipino", "Japanese", "Korean", "Vietnamese", "Other Asian", "NIU: Not of Asian descent"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 1, 7, 7, 7, 7, 2, 7, 3, 7, 7, 4, 5, 7, 7, 7, 7, 7, 7, 7, 6, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8),
      levels = c("White alone", "Black or African American alone", "Apache alone", "Blackfeet alone", "Cherokee alone", "Cheyenne alone", "Chickasaw alone", "Chippewa alone", "Choctaw alone", "Comanche alone", "Creek alone", "Crow alone", "Hopi alone", "Iroquois alone", "Lumbee alone", "Mexican American Indian alone", "Navajo alone", "Pima alone", "Potawatomi alone", "Pueblo alone", "Puget Sound Salish alone", "Seminole alone", "Sioux alone", "South American Indian alone", "Tohono O'Odham alone", "Yaqui alone", "Other specified American Indian tribes alone", "All other specified American Indian tribe combinations", "American Indian, tribe not specified", "Alaskan Athabascan alone", "Tlingit-Haida alone", "Inupiat alone", "Yup'ik alone", "Aleut alone", "Other Alaska Native", "Other American Indian and Alaska Native specified", "American Indian and Alaska Native, not specified", "Asian Indian alone", "Bangladeshi alone", "Bhutanese alone", "Burmese alone", "Cambodian alone", "Chinese, except Taiwanese, alone", "Taiwanese alone", "Filipino alone", "Hmong alone", "Indonesian alone", "Japanese alone", "Korean alone", "Laotian alone", "Malaysian alone", "Mongolian alone", "Nepalese alone", "Pakistani alone", "Sri Lankan alone", "Thai alone", "Vietnamese alone", "Other Asian alone", "All combinations of Asian races only", "Native Hawaiian alone", "Samoan alone", "Tongan alone", "Guamanian or Chamorro alone", "Marshallese alone", "Fijian alone", "Other Native Hawaiian and Other Pacific Islander", "Some Other Race alone", "Two or More Races"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2022-08-30 16:13:10"),

  bpl__pobp = list(
    ASEC = list(
      groups = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 84, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158),
      levels = c("United States, n.s.", "American Samoa", "Guam", "Puerto Rico", "U.S. Virgin Islands", "Canada", "Bermuda", "Mexico", "Belize/British Honduras", "Costa Rica", "El Salvador", "Guatemala", "Honduras", "Nicaragua", "Panama", "Cuba", "Dominican Republic", "Haiti", "Jamaica", "Bahamas", "Barbados", "Dominica", "Grenada", "Trinidad and Tobago", "Antigua and Barbuda", "St. Kitts--Nevis", "St. Lucia", "St. Vincent and the Grenadi", "Caribbean, n.s.", "Argentina", "Bolivia", "Brazil", "Chile", "Colombia", "Ecuador", "Guyana/British Guiana", "Peru", "Uruguay", "Venezuela", "Paraguay", "South America, n.s.", "Americas, n.s.", "Denmark", "Finland", "Iceland", "Norway", "Sweden", "England", "Scotland", "United Kingdom, n.s.", "Ireland", "Northern Ireland", "Belgium", "France", "Netherlands", "Switzerland", "Greece", "Italy", "Portugal", "Azores", "Spain", "Austria", "Czechoslavakia", "Slovakia", "Czech Republic", "Germany", "Hungary", "Poland", "Romania", "Bulgaria", "Albania", "Yugoslavia", "Bosnia and Herzegovina", "Croatia", "Macedonia", "Serbia", "Estonia", "Latvia", "Lithuania", "Other USSR/Russia", "Ukraine", "Belarus", "Moldova", "USSR, n.s.", "Europe, n.s.", "China", "Hong Kong", "Taiwan", "Japan", "Korea", "South Korea", "Mongolia", "Cambodia", "Indonesia", "Laos", "Malaysia", "Philippines", "Singapore", "Thailand", "Vietnam", "Afghanistan", "India", "Bangladesh", "Bhutan", "Burma", "Pakistan", "Sri Lanka", "Nepal", "Iran", "Iraq", "Israel", "Jordan", "Lebanon", "Saudi Arabia", "Syria", "Turkey", "Kuwait", "Yemen", "United Arab Emirates", "Armenia", "Azerbaijan", "Georgia", "Uzbekistan", "Kazakhstan", "Asia, n.e.c./n.s.", "Egypt/United Arab Rep.", "Morocco", "Algeria", "Sudan", "Libya", "Ghana", "Nigeria", "Cameroon", "Cape Verde", "Liberia", "Senegal", "Sierra Leone", "Guinea", "Ivory Coast", "Togo", "Eritrea", "Ethiopia", "Kenya", "Somalia", "Tanzania", "Uganda", "Zimbabwe", "South Africa (Union of)", "Zaire", "Congo", "Zambia", "Africa, n.s./n.e.c.", "Australia", "New Zealand", "Fiji", "Tonga", "Samoa", "Marshall Islands", "Micronesia", "Other, n.e.c. and unknown"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 4, 5, 71, 62, 53, 70, 63, 43, 44, 54, 66, 57, 67, 45, 51, 58, 55, 46, 68, 59, 60, 69, 61, 47, 56, 50, 48, 49, 52, 72, 65, 64, 73, 74, 75, 76, 77, 78, 118, 119, 81, 120, 82, 79, 80, 83, 84, 84, 84, 84, 99, 101, 102, 103, 91, 85, 86, 100, 92, 107, 108, 109, 88, 110, 89, 122, 123, 115, 93, 111, 94, 90, 106, 104, 95, 112, 96, 105, 113, 87, 97, 114, 117, 121, 98, 116, 123, 123, 123, 7, 6, 8, 9, 10, 11, 12, 13, 14, 15, 25, 20, 21, 16, 22, 17, 23, 18, 19, 26, 27, 28, 24, 29, 29, 30, 31, 32, 33, 34, 35, 36, 40, 37, 38, 39, 41, 42, 126, 131, 132, 148, 124, 140, 139, 150, 129, 136, 137, 141, 133, 128, 125, 130, 150, 134, 135, 142, 146, 127, 143, 138, 150, 144, 147, 149, 145, 150, 150, 150, 150, 150, 151, 153, 156, 157, 152, 154, 155, 158),
      levels = c("Alabama / AL", "Alaska / AK", "Arizona / AZ", "Arkansas / AR", "California / CA", "Colorado / CO", "Connecticut / CT", "Delaware / DE", "District of Columbia / DC", "Florida / FL", "Georgia / GA", "Hawaii / HI", "Idaho / ID", "Illinois / IL", "Indiana / IN", "Iowa / IA", "Kansas / KS", "Kentucky / KY", "Louisiana / LA", "Maine / ME", "Maryland / MD", "Massachusetts / MA", "Michigan / MI", "Minnesota / MN", "Mississippi / MS", "Missouri / MO", "Montana / MT", "Nebraska / NE", "Nevada / NV", "New Hampshire / NH", "New Jersey / NJ", "New Mexico / NM", "New York / NY", "North Carolina / NC", "North Dakota / ND", "Ohio / OH", "Oklahoma / OK", "Oregon / OR", "Pennsylvania / PA", "Rhode Island / RI", "South Carolina / SC", "South Dakota / SD", "Tennessee / TN", "Texas / TX", "Utah / UT", "Vermont / VT", "Virginia / VA", "Washington / WA", "West Virginia / WV", "Wisconsin / WI", "Wyoming / WY", "American Samoa", "Guam", "Commonwealth of the Northern Mariana Islands", "Puerto Rico", "US Virgin Islands", "Albania", "Austria", "Belgium", "Bulgaria", "Czechoslovakia", "Denmark", "Finland", "France", "Germany", "Greece", "Hungary", "Iceland", "Ireland", "Italy", "Netherlands", "Norway", "Poland", "Portugal", "Azores Islands", "Romania", "Spain", "Sweden", "Switzerland", "United Kingdom, Not Specified", "England", "Scotland", "Northern Ireland", "Yugoslavia", "Czech Republic", "Slovakia", "Bosnia and Herzegovina", "Croatia", "Macedonia", "Serbia", "Latvia", "Lithuania", "Armenia", "Azerbaijan", "Belarus", "Georgia", "Moldova", "Russia", "Ukraine", "USSR", "Europe", "Kosovo", "Montenegro", "Other Europe, Not Specified", "Afghanistan", "Bangladesh", "Bhutan", "Myanmar", "Cambodia", "China", "Hong Kong", "India", "Indonesia", "Iran", "Iraq", "Israel", "Japan", "Jordan", "Korea", "Kazakhstan", "Kyrgyzstan", "Kuwait", "Laos", "Lebanon", "Malaysia", "Mongolia", "Nepal", "Pakistan", "Philippines", "Saudi Arabia", "Singapore", "Sri Lanka", "Syria", "Taiwan", "Thailand", "Turkey", "United Arab Emirates", "Uzbekistan", "Vietnam", "Yemen", "Asia", "South Central Asia, Not Specified", "Other Asia, Not Specified", "Bermuda", "Canada", "Mexico", "Belize", "Costa Rica", "El Salvador", "Guatemala", "Honduras", "Nicaragua", "Panama", "Antigua and Barbuda", "Bahamas", "Barbados", "Cuba", "Dominica", "Dominican Republic", "Grenada", "Haiti", "Jamaica", "St. Kitts-Nevis", "St. Lucia", "St. Vincent and the Grenadines", "Trinidad and Tobago", "West Indies", "Caribbean, Not Specified", "Argentina", "Bolivia", "Brazil", "Chile", "Colombia", "Ecuador", "Guyana", "Paraguay", "Peru", "Uruguay", "Venezuela", "South America", "Americas, Not Specified", "Algeria", "Cameroon", "Cabo Verde", "Congo", "Egypt", "Ethiopia", "Eritrea", "Gambia", "Ghana", "Guinea", "Ivory Coast", "Kenya", "Liberia", "Libya", "Morocco", "Nigeria", "Rwanda", "Senegal", "Sierra Leone", "Somalia", "South Africa", "Sudan", "Tanzania", "Togo", "Tunisia", "Uganda", "Democratic Republic of Congo (Zaire)", "Zambia", "Zimbabwe", "Africa", "South Sudan", "Western Africa, Not Specified", "Other Africa, Not Specified", "Eastern Africa, Not Specified", "Australia", "Fiji", "Marshall Islands", "Micronesia", "New Zealand", "Tonga", "Samoa", "Other US Island Areas, Oceania, Not Specified, or at Sea"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2022-09-08 15:49:11"),

  champvanw__hins6 = list(
    ASEC = list(
      groups = 1:2,
      levels = c("No", "Yes"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 2:1,
      levels = c("Yes", "No"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2022-08-30 16:42:49")

  # child_pres_age__paoc = list(
  #   ASEC = list(
  #     groups = 1:5,
  #     levels = c("NIU: Male / female under 16", "only kids < 6", "kids 6-17", "kids < 6 and kids 6-17", "no own kids"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 1:5,
  #     levels = c("Male / Female under 16 years old", "Females with own children under 6 years only", "Females with own children 6 to 17 years only", "Females with own children under 6 years and 6 to 17 years", "Females with no own children"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "constructed in ASEC from sex, age, momloc, poploc, momloc2, poploc2",
  #   modified = "2022-09-13 13:13:25"),
  # 
  # citizen__cit = list(
  #   ASEC = list(
  #     groups = 1:5,
  #     levels = c("Born in U.S", "Born in U.S. outlying", "Born abroad of American parents", "Naturalized citizen", "Not a citizen"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 1:5,
  #     levels = c("Born in the U.S.", "Born in Puerto Rico, Guam, the U.S. Virgin Islands, or the Northern Marianas", "Born abroad of American parent(s)", "U.S. citizen by naturalization", "Not a citizen of the U.S."),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-08-30 16:44:04"),
  # 
  # classwkr__cow = list(
  #   ASEC = list(
  #     groups = c(1, 2, 3, 4, 5, 5, 6, 7, 8),
  #     levels = c("NIU: Less than 15 or never worked", "Self-employed, not incorporated", "Self-employed, incorporated", "Wage/salary, private", "Federal government employee", "Armed forces", "State government employee", "Local government employee", "Unpaid family worker"),
  #     breaks = "",
  #     adj = "if_else(age != \"15\", classwkr, factor(\"NIU: Less than 15 or never worked\",\nordered = T, levels = levels(classwkr))\n)"),
  #   ACS = list(
  #     groups = c(1, 4, 4, 7, 6, 5, 2, 3, 8, 1),
  #     levels = c("Less than 16 years old / Not in labor force who last worked more than 5 years ago or never worked", "Employee of a private for-profit company or business, or of an individual, for wages, salary, or commissions", "Employee of a private not-for-profit, tax-exempt, or charitable organization", "Local government employee (city, county, etc.)", "State government employee", "Federal government employee", "Self-employed in own not incorporated business, professional practice, or farm", "Self-employed in own incorporated business, professional practice or farm", "Working without pay in family business or farm", "Unemployed and last worked 5 years ago or earlier or never worked"),
  #     breaks = "",
  #     adj = "",
  #     agg = logical(0)
  #   ),
  #   ordered = TRUE,
  #   comment = "Put ASEC people under 16 into the NIU category to match ACS NIU",
  #   modified = "2022-08-31 17:53:54"),
  # 
  # diffcare__ddrs = list(
  #   ASEC = list(
  #     groups = 1:3,
  #     levels = c("NIU: Less than 15", "No personal care difficulty", "Has personal care difficulty"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = c(1, 3, 2),
  #     levels = c("Less than 5 years old", "Yes", "No"),
  #     breaks = "",
  #     adj = "if_else(agep >= 15, ddrs, factor(\"Less than 5 years old\")\n)",
  #     agg = logical(0)
  #   ),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-08-31 17:58:01"),
  # 
  # diffeye__deye = list(
  #   ASEC = list(
  #     groups = c(1, 1, 2),
  #     levels = c("NIU: Less than 15", "No vision difficulty", "Has vision difficulty"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 2:1,
  #     levels = c("Yes", "No"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = FALSE,
  #   comment = "Assume less than 15 has no difficulty",
  #   modified = "2022-09-13 14:30:59"),
  # 
  # diffhear__dear = list(
  #   ASEC = list(
  #     groups = c(1, 1, 2),
  #     levels = c("NIU: Less than 15", "No hearing difficulty", "Has hearing difficulty"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 2:1,
  #     levels = c("Yes", "No"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = FALSE,
  #   comment = "Assume less than 15 has no difficulty",
  #   modified = "2022-09-13 14:31:46"),
  # 
  # diffmob__dphy = list(
  #   ASEC = list(
  #     groups = c(1, 1, 2),
  #     levels = c("NIU: Less than 15", "No mobility limitation", "Has mobility limitation"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = c(1, 2, 1),
  #     levels = c("Less than 5 years old", "Yes", "No"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = FALSE,
  #   comment = "Assume less than 15 has no difficulty",
  #   modified = "2022-09-13 14:40:13"),
  # 
  # dpcovnw__hins2 = list(
  #   ASEC = list(
  #     groups = 1:2,
  #     levels = c("No", "Yes"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 2:1,
  #     levels = c("Yes", "No"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-08-31 17:00:11"),
  # 
  # educ__schl = list(
  #   ASEC = list(
  #     groups = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 12, 13, 14, 15, 16),
  #     levels = c("NIU: Less than 15", "None or preschool", "Grades 1, 2, 3, or 4", "Grades 5 or 6", "Grades 7 or 8", "Grade 9", "Grade 10", "Grade 11", "12th grade, no diploma", "High school diploma or equivalent", "Some college but no degree", "Associate's degree, occupational/vocational program", "Associate's degree, academic program", "Bachelor's degree", "Master's degree", "Professional school degree", "Doctorate degree"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = c(1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 5, 5, 6, 7, 8, 9, 10, 10, 11, 11, 12, 13, 14, 15, 16),
  #     levels = c("NIU: Less than 15", "No schooling completed", "Nursery school, preschool", "Kindergarten", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8", "Grade 9", "Grade 10", "Grade 11", "12th grade - no diploma", "Regular high school diploma", "GED or alternative credential", "Some college, but less than 1 year", "1 or more years of college credit, no degree", "Associate's degree", "Bachelor's degree", "Master's degree", "Professional degree beyond a bachelor's degree", "Doctorate degree"),
  #     breaks = "",
  #     adj = "if_else(agep < 15, factor(\"NIU: Less than 15\", levels = c(\"NIU: Less than 15\", levels(schl)), ordered=T\n), factor(schl, levels = c(\"NIU: Less than 15\", levels(schl)))\n)",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "Limit ACS to under 15",
  #   modified = "2022-09-13 14:45:39"),
  # 
  # empstat__esr = list(
  #   ASEC = list(
  #     groups = c(1, 2, 3, 4, 5, 5, 6, 6, 6),
  #     levels = c("NIU: Less than 15", "Armed Forces", "At work", "Has job, not at work last week", "Unemployed, experienced worker", "Unemployed, new worker", "NILF, unable to work", "NILF, other", "NILF, retired"),
  #     breaks = "",
  #     adj = "if_else(age != '15', empstat, factor('NIU: Less than 15',\nordered = T, levels = levels(empstat))\n)"),
  #   ACS = list(
  #     groups = c(1, 3, 4, 5, 2, 2, 6),
  #     levels = c("Less than 16 years old", "Civilian employed, at work", "Civilian employed, with a job but not at work", "Unemployed", "Armed forces, at work", "Armed forces, with a job but not at work", "Not in labor force"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "Changes ASEC 15 yr olds to be in NIU category to match ACS NIU category. Assumed that ASEC 'armed forces' includes armed forces at work and not at work. ",
  #   modified = "2022-08-31 17:46:23"),
  # 
  # faminc__fincp = list(
  #   ASEC = list(
  #     groups = 1:16,
  #     levels = c("Under $5,000", "$5,000 - 7,499", "$7,500 - 9,999", "$10,000 - 12,499", "$12,500 - 14,999", "$15,000 - 19,999", "$20,000 - 24,999", "$25,000 - 29,999", "$30,000 - 34,999", "$35,000 - 39,999", "$40,000 - 49,999", "$50,000 - 59,999", "$60,000 - 74,999", "$75,000 - 99,999", "$100,000 - 149,999", "$150,000 and over"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 1:16,
  #     levels = c("Less than 5000", "[5000 to 7500)", "[7500 to 10000)", "[10000 to 12500)", "[12500 to 15000)", "[15000 to 20000)", "[20000 to 25000)", "[25000 to 30000)", "[30000 to 35000)", "[35000 to 40000)", "[40000 to 50000)", "[50000 to 60000)", "[60000 to 75000)", "[75000 to 1e+05)", "[1e+05 to 150000)", "150000 or more"),
  #     breaks = c(5000, 7500, 10000, 12500, 15000, 20000, 25000, 30000, 35000, 40000, 50000, 60000, 75000, 1e+05, 150000),
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2023-01-11 08:37:08"),
  # 
  # famkind__hht = list(
  #   ASEC = list(
  #     groups = 1:3,
  #     levels = c("Husband/wife family", "Male reference person", "Female reference person"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = c(1, 2, 3, 2, 2, 3, 3),
  #     levels = c("Married couple household", "Other family household: Male householder, no spouse present", "Other family household: Female householder, no spouse present", "Nonfamily household: Male householder: Living alone", "Nonfamily household: Male householder: Not living alone", "Nonfamily household: Female householder: Living alone", "Nonfamily household: Female householder: Not living alone"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "Although famkind in ASEC is at the person level - it is the same for all people in a family ",
  #   modified = "2022-09-13 09:44:20"),
  # 
  # foodstmp__fs = list(
  #   ASEC = list(
  #     groups = 1:2,
  #     levels = c("No", "Yes"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 2:1,
  #     levels = c("Yes", "No"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2023-01-06 15:55:07"),
  # 
  # ftype__sfr = list(
  #   ASEC = list(
  #     groups = c(1, 1, 2, 2, 1),
  #     levels = c("Primary family", "Nonfamily householder", "Related subfamily", "Unrelated subfamily", "Secondary individual"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = c(1, 2, 2, 2, 2, 2, 2),
  #     levels = c("Not in a subfamily", "Husband / Wife no children", "Husband / Wife with children", "Parent in a one-parent subfamily", "Child in a married-couple subfamily", "Child in a mother-child subfamily", "Child in a father-child subfamily"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = FALSE,
  #   comment = "Non-family householders and secondary individuals are not part of Census defined subfamilies",
  #   modified = "2022-09-13 10:01:02"),
  # 
  # fullpart__wkhp = list(
  #   ASEC = list(
  #     groups = 1:3,
  #     levels = c("NIU: Less than 15 or did not work last year", "Full-time", "Part-time"),
  #     breaks = "",
  #     adj = "if_else(age != '15', fullpart, factor('NIU: Less than 15 or did not work last year',\nordered = T, levels = levels(fullpart))\n)"),
  #   ACS = list(
  #     groups = c(1, 3, 2),
  #     levels = c("Less than 1", "[1 to 35)", "35 or more"),
  #     breaks = c(1, 35),
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "ACS is 16+, ASEC is 15+ - change ASEC 15 yr olds to NIU",
  #   modified = "2022-08-31 18:23:01"),
  # 
  # grpcovnw__hins1 = list(
  #   ASEC = list(
  #     groups = 1:2,
  #     levels = c("No", "Yes"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 2:1,
  #     levels = c("Yes", "No"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-08-31 18:27:38"),
  # 
  # hhincome__hincp = list(
  #   ASEC = list(
  #     groups = 1,
  #     levels = "Min: -13000, Median: 63000, Mean: 90000, Max: 2250000",
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 1,
  #     levels = "Min: -15350, Median: 65700, Mean: 92400, Max: 2940000",
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = "",
  #   comment = "",
  #   modified = "2023-01-06 15:58:44"),
  # 
  # hhtenure__ten = list(
  #   ASEC = list(
  #     groups = 1:3,
  #     levels = c("Owned or being bought", "Rented for cash", "Occupied without payment of cash rent"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = c(1, 1, 2, 3),
  #     levels = c("Owned with mortgage or loan (include home equity loans)", "Owned free and clear", "Rented", "Occupied without payment of rent"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "Can't distinguish between owned with or without mortgage in ASEC",
  #   modified = "2023-01-06 16:03:12"),
  # 
  # himcaidnw__hins4 = list(
  #   ASEC = list(
  #     groups = 1:2,
  #     levels = c("No", "Yes"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 2:1,
  #     levels = c("Yes", "No"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-08-31 18:30:11"),
  # 
  # himcarenw__hins3 = list(
  #   ASEC = list(
  #     groups = 1:2,
  #     levels = c("No", "Yes"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 2:1,
  #     levels = c("Yes", "No"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-08-31 18:30:41"),
  # 
  # hispan__hisp = list(
  #   ASEC = list(
  #     groups = 1:9,
  #     levels = c("Not Hispanic", "Mexican", "Puerto Rican", "Cuban", "Dominican", "Salvadoran", "Other Hispanic", "Central American, (excluding Salvadoran)", "South American"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = c(1, 2, 3, 4, 5, 8, 8, 8, 8, 8, 6, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 7, 7),
  #     levels = c("Not Spanish / Hispanic / Latino", "Mexican", "Puerto Rican", "Cuban", "Dominican", "Costa Rican", "Guatemalan", "Honduran", "Nicaraguan", "Panamanian", "Salvadoran", "Other Central American", "Argentinean", "Bolivian", "Chilean", "Colombian", "Ecuadorian", "Paraguayan", "Peruvian", "Uruguayan", "Venezuelan", "Other South American", "Spaniard", "All Other Spanish / Hispanic / Latino"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-08-31 18:35:05"),
  # 
  # incasist__oip = list(
  #   ASEC = list(
  #     groups = 1,
  #     levels = "Min: 0, Median: 0, Mean: 85.8, Max: 300000",
  #     breaks = "",
  #     adj = "incunemp + incvet + incwkcom + incchild + inceduc + incother + incasist + incdisab"),
  #   ACS = list(
  #     groups = 1,
  #     levels = "Min: 0, Median: 0, Mean: 489, Max: 84900",
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = "",
  #   comment = "Including INCDISAB although some portion of it might be from disability pension, in which case it would go in retirement income (might therefore under-estimate retirement income and overestimate other income). ",
  #   modified = "2022-09-13 10:32:51"),
  # 
  # incbus__semp = list(
  #   ASEC = list(
  #     groups = 1,
  #     levels = "Min: -10000, Median: 0, Mean: 1390, Max: 1100000",
  #     breaks = "",
  #     adj = "incbus + incfarm"),
  #   ACS = list(
  #     groups = 1,
  #     levels = "Min: -9700, Median: 0, Mean: 1698, Max: 516000",
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = "",
  #   comment = "",
  #   modified = "2022-09-02 08:14:04"),
  # 
  # incdivid__intp = list(
  #   ASEC = list(
  #     groups = 1,
  #     levels = "Min: 0, Median: 0, Mean: 465.5, Max: 400000",
  #     breaks = "",
  #     adj = "incdivid + incint + incrent"),
  #   ACS = list(
  #     groups = 1,
  #     levels = "Min: -2626, Median: 0, Mean: 1815, Max: 474000",
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = "",
  #   comment = "",
  #   modified = "2022-09-02 08:22:27"),
  # 
  # incret1__retp = list(
  #   ASEC = list(
  #     groups = 1,
  #     levels = "Min: 0, Median: 0, Mean: 610, Max: 1000000",
  #     breaks = "",
  #     adj = "incret1 + incret2 + incpens + incrann + incsurv"),
  #   ACS = list(
  #     groups = 1,
  #     levels = "Min: 0, Median: 0, Mean: 2640, Max: 210000",
  #     breaks = "",
  #     adj = "",
  #     agg = logical(0)
  #   ),
  #   ordered = "",
  #   comment = "Using incret1 + incret2 instead of total incretir because incret1 and incret2 includes people 15+ with retirement income, while incretir is only 58+. ACS retp is 15+. Including INCSURV even though some of it might not be survivors retirement income and instead should be included in other income. Might therefore over-estimate retirement income and under-estimate other income. ",
  #   modified = "2022-09-13 10:34:04"),
  # 
  # incss__ssp = list(
  #   ASEC = list(
  #     groups = 1,
  #     levels = "Min: 0, Median: 0, Mean: 2583, Max: 60000",
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 1,
  #     levels = "Min: 0, Median: 0, Mean: 2453, Max: 39100",
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = "",
  #   comment = "",
  #   modified = "2022-09-02 08:45:56"),
  # 
  # incssi__ssip = list(
  #   ASEC = list(
  #     groups = 1,
  #     levels = "Min: 0, Median: 0, Mean: 149.3, Max: 40000",
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 1,
  #     levels = "Min: 0, Median: 0, Mean: 217.4, Max: 27700",
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = "",
  #   comment = "",
  #   modified = "2022-09-02 08:45:30"),
  # 
  # inctot__pincp = list(
  #   ASEC = list(
  #     groups = 1,
  #     levels = "Min: -13000, Median: 19500, Mean: 36060, Max: 2056000",
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 1,
  #     levels = "Min: -10300, Median: 18200, Mean: 35700, Max: 1646000",
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = "",
  #   comment = "",
  #   modified = "2022-09-02 09:16:37"),
  # 
  # incwage__wagp = list(
  #   ASEC = list(
  #     groups = 1,
  #     levels = "Min: 0, Median: 0, Mean: 26900, Max: 1600000",
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 1,
  #     levels = "Min: 0, Median: 202, Mean: 26370, Max: 724000",
  #     breaks = "",
  #     adj = "",
  #     agg = logical(0)
  #   ),
  #   ordered = "",
  #   comment = "",
  #   modified = "2022-09-02 08:25:38"),
  # 
  # incwelfr__pap = list(
  #   ASEC = list(
  #     groups = 1,
  #     levels = "Min: 0, Median: 0, Mean: 14.66, Max: 25000",
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 1,
  #     levels = "Min: 0, Median: 0, Mean: 27.75, Max: 24140",
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = "",
  #   comment = "",
  #   modified = "2022-09-02 08:48:00"),
  # 
  # ind__naicsp = list(
  #   ASEC = list(
  #     groups = 1:19,
  #     levels = c("Less than 1", "[1 to 370)", "[370 to 570)", "[570 to 770)", "[770 to 1070)", "[1070 to 3570)", "[3570 to 4670)", "[4670 to 6070)", "[6070 to 6470)", "[6470 to 6870)", "[6870 to 7270)", "[7270 to 7860)", "[7860 to 7970)", "[7970 to 8370)", "[8370 to 8560)", "[8560 to 8780)", "[8780 to 9370)", "[9370 to 9890)", "9890 or more"),
  #     breaks = c(1, 370, 570, 770, 1070, 3570, 4670, 6070, 6470, 6870, 7270, 7860, 7970, 8370, 8560, 8780, 9370, 9890),
  #     adj = ""),
  #   ACS = list(
  #     groups = c(1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 18, 18, 18, 18, 1),
  #     levels = c("Less than 16 years old / Not in labor force who last worked more than 5 years ago or never worked", "AGR-Crop Production", "AGR-Animal Production And Aquaculture", "AGR-Logging", "AGR-Forestry Except Logging", "AGR-Fishing, Hunting And Trapping", "AGR-Support Activities For Agriculture And Forestry", "EXT-Oil And Gas Extraction", "EXT-Coal Mining", "EXT-Metal Ore Mining", "EXT-Nonmetallic Mineral Mining And Quarrying", "EXT-Support Activities For Mining", "UTL-Electric Power Generation, Transmission And Distribution", "UTL-Natural Gas Distribution", "UTL-Sewage Treatment Facilities", "UTL-Water, Steam, Air-Conditioning, And Irrigation Systems", "UTL-Electric And Gas, And Other Combinations", "UTL-Not Specified Utilities", "CON-Construction (The Cleaning Of Buildings And Dwellings Is Incidental During Construction And Immediately After Construction)", "MFG-Sugar And Confectionery Products", "MFG-Fruit And Vegetable Preserving And Specialty Food", "MFG-Dairy Product", "MFG-Animal Slaughtering And Processing", "MFG-Retail Bakeries", "MFG-Bakeries And Tortilla, Except Retail Bakeries", "MFG-Animal Food, Grain And Oilseed Milling", "MFG-Seafood And Other Miscellaneous Foods, N.E.C.", "MFG-Not Specified Food Industries", "MFG-Beverage", "MFG-Tobacco", "MFG-Fiber, Yarn, And Thread Mills", "MFG-Fabric Mills, Except Knitting Mills", "MFG-Textile And Fabric Finishing And Fabric Coating Mills", "MFG-Carpet And Rug Mills", "MFG-Textile Product Mills, Except Carpet And Rug", "MFG-Cut And Sew, And Apparel Accessories And Other Apparel", "MFG-Footwear", "MFG-Leather And Hide Tanning And Finishing, And Other Leather And Allied Product", "MFG-Knitting Fabric Mills, And Apparel Knitting Mills", "MFG-Sawmills And Wood Preservation", "MFG-Veneer, Plywood, And Engineered Wood Products", "MFG-Prefabricated Wood Buildings And Mobile Homes", "MFG-Miscellaneous Wood Products", "MFG-Pulp, Paper, And Paperboard Mills", "MFG-Paperboard Container", "MFG-Miscellaneous Paper And Pulp Products", "MFG-Printing And Related Support Activities", "MFG-Miscellaneous Petroleum And Coal Products", "MFG-Petroleum Refining", "MFG-Resin, Synthetic Rubber, And Fibers And Filaments", "MFG-Agricultural Chemical", "MFG-Pharmaceuticals And Medicine", "MFG-Paint, Coating, And Adhesive", "MFG-Soap, Cleaning Compound, And Cosmetics", "MFG-Industrial And Miscellaneous Chemicals", "MFG-Plastics Product", "MFG-Tire", "MFG-Rubber Products, Except Tires", "MFG-Pottery, Ceramics, And Plumbing Fixture", "MFG-Clay Building Material And Refractories", "MFG-Glass And Glass Product", "MFG-Miscellaneous Nonmetallic Mineral Product", "MFG-Cement, Concrete, Lime, And Gypsum Product", "MFG-Aluminum Production And Processing", "MFG-Nonferrous Metal (Except Aluminum) Production And Processing", "MFG-Foundries", "MFG-Iron And Steel Mills And Steel Product", "MFG-Metal Forgings And Stampings", "MFG-Cutlery And Hand Tool", "MFG-Machine Shops; Turned Product; Screw, Nut And Bolt", "MFG-Coating, Engraving, Heat Treating, And Allied Activities", "MFG-Ordnance", "MFG-Structural Metals, And Boiler, Tank, And Shipping Container", "MFG-Miscellaneous Fabricated Metal Products", "MFG-Agricultural Implement", "MFG-Construction, And Mining And Oil And Gas Field Machinery", "MFG-Commercial And Service Industry Machinery", "MFG-Metalworking Machinery", "MFG-Engine, Turbine, And Power Transmission Equipment", "MFG-Machinery, N.E.C. Or Not Specified", "MFG-Computer And Peripheral Equipment", "MFG-Navigational, Measuring, Electromedical, And Control Instruments", "MFG-Communications, Audio And Video Equipment", "MFG-Electronic Component And Product, N.E.C.", "MFG-Household Appliance", "MFG-Electric Lighting And Electrical Equipment, And Other Electrical Component, N.E.C.", "MFG-Aircraft And Parts", "MFG-Aerospace Products And Parts", "MFG-Railroad Rolling Stock", "MFG-Ship And Boat Building", "MFG-Other Transportation Equipment", "MFG-Motor Vehicles And Motor Vehicle Equipment", "MFG-Furniture And Related Product", "MFG-Medical Equipment And Supplies", "MFG-Sporting And Athletic Goods, And Doll, Toy And Game", "MFG-Miscellaneous Manufacturing, N.E.C.", "MFG-Not Specified Metal Industries", "MFG-Not Specified Manufacturing Industries", "WHL-Motor Vehicle And Motor Vehicle Parts And Supplies Merchant Wholesalers", "WHL-Furniture And Home Furnishing Merchant Wholesalers", "WHL-Lumber And Other Construction Materials Merchant Wholesalers", "WHL-Professional And Commercial Equipment And Supplies Merchant Wholesalers", "WHL-Metals And Minerals, Except Petroleum, Merchant Wholesalers", "WHL-Household Appliances And Electrical And Electronic Goods Merchant Wholesalers", "WHL-Hardware, And Plumbing And Heating Equipment, And Supplies Merchant Wholesalers", "WHL-Machinery, Equipment, And Supplies Merchant Wholesalers", "WHL-Recyclable Material Merchant Wholesalers", "WHL-Miscellaneous Durable Goods Merchant Wholesalers", "WHL-Paper And Paper Products Merchant Wholesalers", "WHL-Apparel, Piece Goods, And Notions Merchant Wholesalers", "WHL-Grocery And Related Product Merchant Wholesalers", "WHL-Farm Product Raw Material Merchant Wholesalers", "WHL-Petroleum And Petroleum Products Merchant Wholesalers", "WHL-Alcoholic Beverages Merchant Wholesalers", "WHL-Farm Supplies Merchant Wholesalers", "WHL-Miscellaneous Nondurable Goods Merchant Wholesalers", "WHL-Drugs, Sundries, And Chemical And Allied Products Merchant Wholesalers", "WHL-Wholesale Electronic Markets And Agents And Brokers", "WHL-Not Specified Wholesale Trade", "RET-Automobile Dealers", "RET-Other Motor Vehicle Dealers", "RET-Automotive Parts, Accessories, And Tire Stores", "RET-Furniture And Home Furnishings Stores", "RET-Household Appliance Stores", "RET-Electronics Stores", "RET-Hardware Stores", "RET-Building Material And Supplies Dealers", "RET-Lawn And Garden Equipment And Supplies Stores", "RET-Supermarkets And Other Grocery (Except Convenience) Stores", "RET-Convenience Stores", "RET-Specialty Food Stores", "RET-Beer, Wine, And Liquor Stores", "RET-Pharmacies And Drug Stores", "RET-Health And Personal Care, Except Drug, Stores", "RET-Gasoline Stations", "RET-Shoe Stores", "RET-Jewelry, Luggage, And Leather Goods Stores", "RET-Clothing Stores", "RET-Sewing, Needlework, And Piece Goods Stores", "RET-Musical Instrument And Supplies Stores", "RET-Sporting Goods, And Hobby And Toy Stores", "RET-Book Stores And News Dealers", "RET-Department Stores", "RET-General Merchandise Stores, Including Warehouse Clubs and Supercenters", "RET-Florists", "RET-Office Supplies And Stationery Stores", "RET-Gift, Novelty, And Souvenir Shops", "RET-Used Merchandise Stores", "RET-Miscellaneous Retail Stores", "RET-Electronic Shopping And Mail-Order Houses", "RET-Vending Machine Operators", "RET-Fuel Dealers", "RET-Other Direct Selling Establishments", "RET-Not Specified Retail Trade", "TRN-Air Transportation", "TRN-Rail Transportation", "TRN-Water Transportation", "TRN-Truck Transportation", "TRN-Taxi And Limousine Service", "TRN-Bus Service And Urban Transit", "TRN-Pipeline Transportation", "TRN-Scenic And Sightseeing Transportation", "TRN-Services Incidental To Transportation", "TRN-Postal Service", "TRN-Couriers And Messengers", "TRN-Warehousing And Storage", "INF-Newspaper Publishers", "INF-Periodical, Book, And Directory Publishers", "INF-Software Publishers", "INF-Motion Pictures And Video Industries", "INF-Sound Recording Industries", "INF-Broadcasting (Except Internet)", "INF-Wired Telecommunications Carriers", "INF-Telecommunications, Except Wired Telecommunications Carriers", "INF-Data Processing, Hosting, And Related Services", "INF-Libraries And Archives", "INF-Internet Publishing And Broadcasting And Web Search Portals", "INF-Other Information Services, Except Libraries And Archives, And Internet Publishing And Broadcasting And Web Search Portals", "FIN-Savings Institutions, Including Credit Unions", "FIN-Nondepository Credit And Related Activities", "FIN-Insurance Carriers", "FIN-Agencies, Brokerages, And Other Insurance Related Activities", "FIN-Banking And Related Activities", "FIN-Securities, Commodities, Funds, Trusts, And Other Financial Investments", "FIN-Lessors Of Real Estate, And Offices Of Real Estate Agents And Brokers", "FIN-Real Estate Property Managers, Offices of Real Estate Appraisers, And Other Activities Related to Real Estate", "FIN-Automotive Equipment Rental And Leasing", "FIN-Other Consumer Goods Rental", "FIN-Commercial, Industrial, And Other Intangible Assets Rental And Leasing", "PRF-Legal Services", "PRF-Accounting, Tax Preparation, Bookkeeping, And Payroll Services", "PRF-Architectural, Engineering, And Related Services", "PRF-Specialized Design Services", "PRF-Computer Systems Design And Related Services", "PRF-Management, Scientific, And Technical Consulting Services", "PRF-Scientific Research And Development Services", "PRF-Advertising, Public Relations, And Related Services", "PRF-Veterinary Services", "PRF-Other Professional, Scientific, And Technical Services", "PRF-Management Of Companies And Enterprises", "PRF-Employment Services", "PRF-Business Support Services", "PRF-Travel Arrangements And Reservation Services", "PRF-Investigation And Security Services", "PRF-Landscaping Services", "PRF-Services To Buildings And Dwellings (Except Cleaning During Construction And Immediately After Construction)", "PRF-Other Administrative And Other Support Services", "PRF-Waste Management And Remediation Services", "EDU-Elementary And Secondary Schools", "EDU-Colleges, Universities, And Professional Schools, Including Junior Colleges", "EDU-Business, Technical, And Trade Schools And Training", "EDU-Other Schools And Instruction, And Educational Support Services", "MED-Offices Of Physicians", "MED-Offices Of Dentists", "MED-Offices Of Chiropractors", "MED-Offices Of Optometrists", "MED-Offices Of Other Health Practitioners", "MED-Outpatient Care Centers", "MED-Home Health Care Services", "MED-Other Health Care Services", "MED-General Medical And Surgical Hospitals, And Specialty (Except Psychiatric And Substance Abuse) Hospitals", "MED-Psychiatric And Substance Abuse Hospitals", "MED-Nursing Care Facilities (Skilled Nursing Facilities)", "MED-Residential Care Facilities, Except Skilled Nursing Facilities", "SCA-Individual And Family Services", "SCA-Community Food And Housing, And Emergency Services", "SCA-Vocational Rehabilitation Services", "SCA-Child Day Care Services", "ENT-Performing Arts Companies", "ENT-Spectator Sports", "ENT-Promoters Of Performing Arts, Sports, And Similar Events, Agents And Managers For Artists, Athletes, Entertainers, And Other Public Figures", "ENT-Independent Artists, Writers, And Performers", "ENT-Museums, Art Galleries, Historical Sites, And Similar Institutions", "ENT-Bowling Centers", "ENT-Other Amusement, Gambling, And Recreation Industries", "ENT-Traveler Accommodation", "ENT-Recreational Vehicle Parks And Camps, And Rooming And Boarding Houses, Dormitories, And Workers' Camps", "ENT-Drinking Places, Alcoholic Beverages", "ENT-Restaurants And Other Food Services", "SRV-Car Washes", "SRV-Automotive Repair And Maintenance", "SRV-Electronic And Precision Equipment Repair And Maintenance", "SRV-Commercial And Industrial Machinery And Equipment Repair And Maintenance", "SRV-Personal And Household Goods Repair And Maintenance", "SRV-Barber Shops", "SRV-Beauty Salons", "SRV-Nail Salons And Other Personal Care Services", "SRV-Funeral Homes, And Cemeteries And Crematories", "SRV-Drycleaning And Laundry Services", "SRV-Other Personal Services", "SRV-Religious Organizations", "SRV-Labor Unions", "SRV-Business, Professional, Political, And Similar Organizations", "SRV-Civic, Social, Advocacy Organizations, And Grantmaking And Giving Services", "SRV-Private Households", "ADM-Public Finance Activities", "ADM-Other General Government And Support", "ADM-Executive Offices And Legislative Bodies", "ADM-Administration Of Human Resource Programs", "MIL-U.S. Army", "MIL-U.S. Air Force", "MIL-U.S. Navy", "MIL-U.S. Marines", "MIL-U.S. Coast Guard", "MIL-Armed Forces, Branch Not Specified", "MIL-Military Reserves Or National Guard", "ADM-National Security And International Affairs", "ADM-Administration Of Environmental Quality And Housing Programs", "ADM-Administration Of Economic Programs And Space Research", "ADM-Justice, Public Order, And Safety Activities", "Unemployed, With No Work Experience In The Last 5 Years Or Earlier Or Never Worked"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-09-13 17:24:23"),
  # 
  # inhcovnw__hins7 = list(
  #   ASEC = list(
  #     groups = 1:2,
  #     levels = c("No", "Yes"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 2:1,
  #     levels = c("Yes", "No"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-09-02 09:18:56"),
  # 
  # labforce__esr = list(
  #   ASEC = list(
  #     groups = 1:3,
  #     levels = c("NIU: Less than 15", "No, not in the labor force", "Yes, in the labor force"),
  #     breaks = "",
  #     adj = "if_else(age != '15', labforce, factor('NIU: Less than 15',\nordered = T, levels = levels(labforce))\n)"),
  #   ACS = list(
  #     groups = c(1, 3, 3, 3, 3, 3, 2),
  #     levels = c("Less than 16 years old", "Civilian employed, at work", "Civilian employed, with a job but not at work", "Unemployed", "Armed forces, at work", "Armed forces, with a job but not at work", "Not in labor force"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-09-02 09:20:49"),
  # 
  # marst__mar = list(
  #   ASEC = list(
  #     groups = c(1, 1, 2, 3, 4, 5),
  #     levels = c("Married, spouse present", "Married, spouse absent", "Separated", "Divorced", "Widowed", "Never married/single"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = c(1, 4, 3, 2, 5),
  #     levels = c("Married", "Widowed", "Divorced", "Separated", "Never married or under 15 years old"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-09-02 09:22:39"),
  # 
  # migsta1__migsp = list(
  #   ASEC = list(
  #     groups = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 1),
  #     levels = c("NIU: Less than one years old", "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming", "Abroad", "Same house"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53),
  #     levels = c("Person less than 1 year old / Lived in same house 1 year ago", "Alabama / AL", "Alaska / AK", "Arizona / AZ", "Arkansas / AR", "California / CA", "Colorado / CO", "Connecticut / CT", "Delaware / DE", "District of Columbia / DC", "Florida / FL", "Georgia / GA", "Hawaii / HI", "Idaho / ID", "Illinois / IL", "Indiana / IN", "Iowa / IA", "Kansas / KS", "Kentucky / KY", "Louisiana / LA", "Maine / ME", "Maryland / MD", "Massachusetts / MA", "Michigan / MI", "Minnesota / MN", "Mississippi / MS", "Missouri / MO", "Montana / MT", "Nebraska / NE", "Nevada / NV", "New Hampshire / NH", "New Jersey / NJ", "New Mexico / NM", "New York / NY", "North Carolina / NC", "North Dakota / ND", "Ohio / OH", "Oklahoma / OK", "Oregon / OR", "Pennsylvania / PA", "Rhode Island / RI", "South Carolina / SC", "South Dakota / SD", "Tennessee / TN", "Texas / TX", "Utah / UT", "Vermont / VT", "Virginia / VA", "Washington / WA", "West Virginia / WV", "Wisconsin / WI", "Wyoming / WY", "Puerto Rico", "France", "Germany", "Northern Europe, Not Specified", "Eastern Europe, Not Specified", "Western Europe or Other Europe, Not Specified", "Italy", "Spain", "United Kingdom, Excluding England", "England", "Russia", "Ukraine", "Afghanistan", "China, Hong Kong, Macau And Paracel Islands", "India", "Israel", "Japan", "Korea", "Nepal", "Pakistan", "Philippines", "Saudi Arabia", "Taiwan", "Thailand", "Turkey", "United Arab Emirates", "Vietnam", "Eastern Asia, Not Specified", "Western Asia, Not Specified", "South Central Asia or Asia, Not Specified", "Canada", "Mexico", "El Salvador", "Guatemala", "Honduras", "Central America, Not Specified", "Cuba", "Dominican Republic", "Haiti", "Jamaica", "Caribbean and North America, Not Specified", "Brazil", "Colombia", "Ecuador", "Peru", "Venezuela", "South America, Not Specified", "Egypt", "Ethiopia", "Kenya", "Nigeria", "Western Africa, Not Specified", "Other Africa, Not Specified", "Eastern Africa, Not Specified", "Australia", "Other US Island Areas, Oceania, Not Specified, or At Sea"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-09-02 09:31:46"),
  # 
  # nativity__nativity = list(
  #   ASEC = list(
  #     groups = c(2, 2, 2, 2, 2, 1),
  #     levels = c("Unknown", "Both parents native-born", "Father foreign, mother native", "Mother foreign, father native", "Both parents foreign", "Foreign born"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 2:1,
  #     levels = c("Native", "Foreign born"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = FALSE,
  #   comment = "No equivalent of 'unknown' in the ACS - assume unknown is Native",
  #   modified = "2022-09-13 10:37:25"),
  # 
  # noc__noc = list(
  #   ASEC = list(
  #     groups = 1,
  #     levels = "Min: 0, Median: 0, Mean: 0.895, Max: 10",
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 1,
  #     levels = "Min: 0, Median: 0, Mean: 0.497, Max: 14",
  #     breaks = "",
  #     adj = "",
  #     agg = "reference"),
  #   ordered = "",
  #   comment = "",
  #   modified = "2022-09-13 13:23:43"),
  # 
  # numprec__np = list(
  #   ASEC = list(
  #     groups = 1,
  #     levels = "Min: 1, Median: 2, Mean: 2.457, Max: 16",
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 1,
  #     levels = "Min: 1, Median: 2, Mean: 2.47, Max: 20",
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = "",
  #   comment = "",
  #   modified = "2023-01-06 16:10:02"),
  # 
  # occ__socp = list(
  #   ASEC = list(
  #     groups = 1:26,
  #     levels = c("Less than 1", "[1 to 500)", "[500 to 800)", "[800 to 1000)", "[1000 to 1300)", "[1300 to 1600)", "[1600 to 2000)", "[2000 to 2100)", "[2100 to 2200)", "[2200 to 2600)", "[2600 to 3000)", "[3000 to 3600)", "[3600 to 3700)", "[3700 to 4000)", "[4000 to 4200)", "[4200 to 4300)", "[4300 to 4700)", "[4700 to 5000)", "[5000 to 6000)", "[6000 to 6200)", "[6200 to 6800)", "[6800 to 7000)", "[7000 to 7700)", "[7700 to 9000)", "[9000 to 9840)", "9840 or more"),
  #     breaks = c(1, 500, 800, 1000, 1300, 1600, 2000, 2100, 2200, 2600, 3000, 3600, 3700, 4000, 4200, 4300, 4700, 5000, 6000, 6200, 6800, 7000, 7700, 9000, 9840),
  #     adj = ""),
  #   ACS = list(
  #     groups = c(1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21, 21, 21, 2, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26, 1),
  #     levels = c("Less than 16 years old / Not in labor force who last worked more than 5 years ago or never worked", "MGR-Chief Executives And Legislators", "MGR-General And Operations Managers", "MGR-Advertising And Promotions Managers", "MGR-Marketing Managers", "MGR-Sales Managers", "MGR-Public Relations And Fundraising Managers", "MGR-Administrative Services Managers", "MGR-Facilities Managers", "MGR-Computer And Information Systems Managers", "MGR-Financial Managers", "MGR-Compensation And Benefits Managers", "MGR-Human Resources Managers", "MGR-Training And Development Managers", "MGR-Industrial Production Managers", "MGR-Purchasing Managers", "MGR-Transportation, Storage, And Distribution Managers", "MGR-Farmers, Ranchers, And Other Agricultural Managers", "MGR-Construction Managers", "MGR-Education And Childcare Administrators", "MGR-Architectural And Engineering Managers", "MGR-Food Service Managers", "MGR-Entertainment And Recreation Managers", "MGR-Lodging Managers", "MGR-Medical And Health Services Managers", "MGR-Natural Sciences Managers", "MGR-Property, Real Estate, And Community Association Managers", "MGR-Social And Community Service Managers", "MGR-Emergency Management Directors", "MGR-Other Managers", "BUS-Agents And Business Managers Of Artists, Performers, And Athletes", "BUS-Buyers And Purchasing Agents, Farm Products", "BUS-Wholesale And Retail Buyers, Except Farm Products", "BUS-Purchasing Agents, Except Wholesale, Retail, And Farm Products", "BUS-Claims Adjusters, Appraisers, Examiners, And Investigators", "BUS-Compliance Officers", "BUS-Cost Estimators", "BUS-Human Resources Workers", "BUS-Logisticians", "BUS-Project Management Specialists", "BUS-Management Analysts", "BUS-Meeting, Convention, And Event Planners", "BUS-Fundraisers", "BUS-Compensation, Benefits, And Job Analysis Specialists", "BUS-Training And Development Specialists", "BUS-Market Research Analysts And Marketing Specialists", "BUS-Business Operations Specialists, All Other", "FIN-Accountants And Auditors", "FIN-Property Appraisers And Assessors", "FIN-Budget Analysts", "FIN-Credit Analysts", "FIN-Financial And Investment Analysts", "FIN-Personal Financial Advisors", "FIN-Insurance Underwriters", "FIN-Financial Examiners", "FIN-Credit Counselors And Loan Officers", "FIN-Tax Examiners And Collectors, And Revenue Agents", "FIN-Tax Preparers", "FIN-Other Financial Specialists", "CMM-Computer And Information Research Scientists", "CMM-Computer Systems Analysts", "CMM-Information Security Analysts", "CMM-Computer Programmers", "CMM-Software Developers", "CMM-Software Quality Assurance Analysts And Testers", "CMM-Web Developers", "CMM-Web And Digital Interface Designers", "CMM-Computer Support Specialists", "CMM-Database Administrators And Architects", "CMM-Network And Computer Systems Administrators", "CMM-Computer Network Architects", "CMM-Computer Occupations, All Other", "CMM-Actuaries", "CMM-Operations Research Analysts", "CMM-Other Mathematical Science Occupations", "ENG-Architects, Except Landscape And Naval", "ENG-Landscape Architects", "ENG-Surveyors, Cartographers, And Photogrammetrists", "ENG-Aerospace Engineers", "ENG-Biomedical And Agricultural Engineers", "ENG-Chemical Engineers", "ENG-Civil Engineers", "ENG-Computer Hardware Engineers", "ENG-Electrical And Electronics Engineers", "ENG-Environmental Engineers", "ENG-Industrial Engineers, Including Health And Safety", "ENG-Marine Engineers And Naval Architects", "ENG-Materials Engineers", "ENG-Mechanical Engineers", "ENG-Petroleum, Mining And Geological Engineers, Including Mining Safety Engineers", "ENG-Other Engineers", "ENG-Architectural And Civil Drafters", "ENG-Other Drafters", "ENG-Electrical and Electronic Engineering Technologists And Technicians", "ENG-Other Engineering Technologists And Technicians, Except Drafters", "ENG-Surveying And Mapping Technicians", "SCI-Agricultural And Food Scientists", "SCI-Biological Scientists", "SCI-Conservation Scientists And Foresters", "SCI-Other Life Scientists", "SCI-Astronomers And Physicists", "SCI-Atmospheric And Space Scientists", "SCI-Chemists And Materials Scientists", "SCI-Environmental Scientists And Specialists, Including Health", "SCI-Geoscientists And Hydrologists, Except Geographers", "SCI-Physical Scientists, All Other", "SCI-Economists", "SCI-Clinical And Counseling Psychologists", "SCI-School Psychologists", "SCI-Other Psychologists", "SCI-Urban And Regional Planners", "SCI-Other Social Scientists", "SCI-Agricultural And Food Science Technicians", "SCI-Biological Technicians", "SCI-Chemical Technicians", "SCI-Environmental Science And Geoscience Technicians, And Nuclear Technicians", "SCI-Other Life, Physical, And Social Science Technicians", "SCI-Occupational Health And Safety Specialists And Technicians", "CMS-Substance Abuse And Behavioral Disorder Counselors", "CMS-Educational, Guidance, And Career Counselors And Advisors", "CMS-Marriage And Family Therapists", "CMS-Mental Health Counselors", "CMS-Rehabilitation Counselors", "CMS-Counselors, All Other", "CMS-Child, Family, And School Social Workers", "CMS-Healthcare Social Workers", "CMS-Mental Health And Substance Abuse Social Workers", "CMS-Social Workers, All Other", "CMS-Probation Officers And Correctional Treatment Specialists", "CMS-Social And Human Service Assistants", "CMS-Other Community And Social Service Specialists", "CMS-Clergy", "CMS-Directors, Religious Activities And Education", "CMS-Religious Workers, All Other", "LGL-Lawyers, And Judges, Magistrates, And Other Judicial Workers", "LGL-Judicial Law Clerks", "LGL-Paralegals And Legal Assistants", "LGL-Title Examiners, Abstractors, And Searchers", "LGL-Legal Support Workers, All Other", "EDU-Postsecondary Teachers", "EDU-Preschool And Kindergarten Teachers", "EDU-Elementary And Middle School Teachers", "EDU-Secondary School Teachers", "EDU-Special Education Teachers", "EDU-Tutors", "EDU-Other Teachers And Instructors", "EDU-Archivists, Curators, And Museum Technicians", "EDU-Librarians And Media Collections Specialists", "EDU-Library Technicians", "EDU-Teaching Assistants", "EDU-Other Educational Instruction and Library Workers", "ENT-Artists And Related Workers", "ENT-Commercial And Industrial Designers", "ENT-Fashion Designers", "ENT-Floral Designers", "ENT-Graphic Designers", "ENT-Interior Designers", "ENT-Merchandise Displayer And Windows Trimmers", "ENT-Other Designers", "ENT-Actors", "ENT-Producers And Directors", "ENT-Athletes And Sports Competitors", "ENT-Coaches And Scouts", "ENT-Umpires, Referees, And Other Sports Officials", "ENT-Dancers And Choreographers", "ENT-Music Directors And Composers", "ENT-Musicians And Singers", "ENT-Disc Jockeys, Except Radio", "ENT-Entertainers And Performers, Sports And Related Workers, All Other", "ENT-Broadcast Announcers And Radio Disc Jockeys", "ENT-News Analysts, Reporters, And Journalists", "ENT-Public Relations Specialists", "ENT-Editors", "ENT-Technical Writers", "ENT-Writers And Authors", "ENT-Interpreters And Translators", "ENT-Court Reporters And Simultaneous Captioners", "ENT-Media And Communication Workers, All Other", "ENT-Other Media And Communication Equipment Workers", "ENT-Photographers", "ENT-Television, Video, And Film Camera Operators And Editors", "MED-Chiropractors", "MED-Dentists", "MED-Dietitians And Nutritionists", "MED-Optometrists", "MED-Pharmacists", "MED-Physicians", "MED-Surgeons", "MED-Physician Assistants", "MED-Podiatrists", "MED-Occupational Therapists", "MED-Physical Therapists", "MED-Radiation Therapists", "MED-Recreational Therapists", "MED-Respiratory Therapists", "MED-Speech-Language Pathologists", "MED-Other Therapists", "MED-Veterinarians", "MED-Registered Nurses", "MED-Nurse Anesthetists", "MED-Audiologists", "MED-Nurse Practitioners, And Nurse Midwives", "MED-Acupuncturists", "MED-Healthcare Diagnosing Or Treating Practitioners, All Other", "MED-Clinical Laboratory Technologists And Technicians", "MED-Dental Hygienists", "MED-Cardiovascular Technologists And Technicians", "MED-Diagnostic Medical Sonographers", "MED-Radiologic Technologists And Technicians", "MED-Magnetic Resonance Imaging Technologists", "MED-Nuclear Medicine Technologists And Medical Dosimetrists", "MED-Emergency Medical Technicians", "MED-Paramedics", "MED-Pharmacy Technicians", "MED-Psychiatric Technicians", "MED-Surgical Technologists", "MED-Veterinary Technologists And Technicians", "MED-Dietetic Technicians And Ophthalmic Medical Technicians", "MED-Licensed Practical And Licensed Vocational Nurses", "MED-Medical Records Specialists", "MED-Opticians, Dispensing", "MED-Miscellaneous Health Technologists And Technicians", "MED-Other Healthcare Practitioners And Technical Occupations", "HLS-Home Health Aides", "HLS-Personal Care Aides", "HLS-Nursing Assistants", "HLS-Orderlies And Psychiatric Aides", "HLS-Occupational Therapy Assistants And Aides", "HLS-Physical Therapist Assistants And Aides", "HLS-Massage Therapists", "HLS-Dental Assistants", "HLS-Medical Assistants", "HLS-Medical Transcriptionists", "HLS-Pharmacy Aides", "HLS-Veterinary Assistants And Laboratory Animal Caretakers", "HLS-Phlebotomists", "HLS-Other Healthcare Support Workers", "PRT-First-Line Supervisors Of Correctional Officers", "PRT-First-Line Supervisors Of Police And Detectives", "PRT-First-Line Supervisors Of Firefighting And Prevention Workers", "PRT-Miscellaneous First-Line Supervisors, Protective Service Workers", "PRT-Firefighters", "PRT-Fire Inspectors", "PRT-Bailiffs", "PRT-Correctional Officers And Jailers", "PRT-Detectives And Criminal Investigators", "PRT-Fish And Game Wardens And Parking Enforcement Officers", "PRT-Police Officers", "PRT-Animal Control Workers", "PRT-Private Detectives And Investigators", "PRT-Security Guards And Gambling Surveillance Officers", "PRT-Crossing Guards And Flaggers", "PRT-Transportation Security Screeners", "PRT-School Bus Monitors", "PRT-Other Protective Service Workers", "EAT-Chefs And Head Cooks", "EAT-First-Line Supervisors Of Food Preparation And Serving Workers", "EAT-Cooks", "EAT-Food Preparation Workers", "EAT-Bartenders", "EAT-Fast Food And Counter Workers", "EAT-Waiters And Waitresses", "EAT-Food Servers, Nonrestaurant", "EAT-Dining Room And Cafeteria Attendants And Bartender Helpers", "EAT-Dishwashers", "EAT-Hosts And Hostesses, Restaurant, Lounge, And Coffee Shop", "EAT-Food Preparation And Serving Related Workers, All Other", "CLN-First-Line Supervisors Of Housekeeping And Janitorial Workers", "CLN-First-Line Supervisors Of Landscaping, Lawn Service, And Groundskeeping Workers", "CLN-Janitors And Building Cleaners", "CLN-Maids And Housekeeping Cleaners", "CLN-Pest Control Workers", "CLN-Landscaping And Groundskeeping Workers", "CLN-Tree Trimmers And Pruners", "CLN-Other Grounds Maintenance Workers", "PRS-Supervisors of Personal Care And Service Workers", "PRS-Animal Trainers", "PRS-Animal Caretakers", "PRS-Gambling Services Workers", "PRS-Ushers, Lobby Attendants, And Ticket Takers", "PRS-Other Entertainment Attendants And Related Workers", "PRS-Morticians, Undertakers, And Funeral Arrangers", "PRS-Embalmers, Crematory Operators And Funeral Attendants", "PRS-Barbers", "PRS-Hairdressers, Hairstylists, And Cosmetologists", "PRS-Manicurists and Pedicurists", "PRS-Skincare Specialists", "PRS-Other Personal Appearance Workers", "PRS-Baggage Porters, Bellhops, And Concierges", "PRS-Tour And Travel Guides", "PRS-Childcare Workers", "PRS-Exercise Trainers And Group Fitness Instructors", "PRS-Recreation Workers", "PRS-Residential Advisors", "PRS-Personal Care And Service Workers, All Other", "SAL-First-Line Supervisors Of Retail Sales Workers", "SAL-First-Line Supervisors Of Non-Retail Sales Workers", "SAL-Cashiers", "SAL-Counter And Rental Clerks", "SAL-Parts Salespersons", "SAL-Retail Salespersons", "SAL-Advertising Sales Agents", "SAL-Insurance Sales Agents", "SAL-Securities, Commodities, And Financial Services Sales Agents", "SAL-Travel Agents", "SAL-Sales Representatives Of Services, Except Advertising, Insurance, Financial Services, And Travel", "SAL-Sales Representatives, Wholesale And Manufacturing", "SAL-Models, Demonstrators, And Product Promoters", "SAL-Real Estate Brokers And Sales Agents", "SAL-Sales Engineers", "SAL-Telemarketers", "SAL-Door-To-Door Sales Workers, News And Street Vendors, And Related Workers", "SAL-Sales And Related Workers, All Other", "OFF-First-Line Supervisors Of Office And Administrative Support Workers", "OFF-Switchboard Operators, Including Answering Service", "OFF-Telephone Operators", "OFF-Communications Equipment Operators, All Other", "OFF-Bill And Account Collectors", "OFF-Billing And Posting Clerks", "OFF-Bookkeeping, Accounting, And Auditing Clerks", "OFF-Payroll And Timekeeping Clerks", "OFF-Procurement Clerks", "OFF-Tellers", "OFF-Other Financial Clerks", "OFF-Court, Municipal, And License Clerks", "OFF-Credit Authorizers, Checkers, And Clerks", "OFF-Customer Service Representatives", "OFF-Eligibility Interviewers, Government Programs", "OFF-File Clerks", "OFF-Hotel, Motel, And Resort Desk Clerks", "OFF-Interviewers, Except Eligibility And Loan", "OFF-Library Assistants, Clerical", "OFF-Loan Interviewers And Clerks", "OFF-New Accounts Clerks", "OFF-Correspondence Clerks And Order Clerks", "OFF-Human Resources Assistants, Except Payroll And Timekeeping", "OFF-Receptionists And Information Clerks", "OFF-Reservation And Transportation Ticket Agents And Travel Clerks", "OFF-Other Information And Records Clerks", "OFF-Cargo And Freight Agents", "OFF-Couriers And Messengers", "OFF-Public Safety Telecommunicators", "OFF-Dispatchers, Except Police, Fire, And Ambulance", "OFF-Meter Readers, Utilities", "OFF-Postal Service Clerks", "OFF-Postal Service Mail Carriers", "OFF-Postal Service Mail Sorters, Processors, And Processing Machine Operators", "OFF-Production, Planning, And Expediting Clerks", "OFF-Shipping, Receiving, And Inventory Clerks", "OFF-Weighers, Measurers, Checkers, And Samplers, Recordkeeping", "OFF-Executive Secretaries And Executive Administrative Assistants", "OFF-Legal Secretaries And Administrative Assistants", "OFF-Medical Secretaries And Administrative Assistants", "OFF-Secretaries And Administrative Assistants, Except Legal, Medical, And Executive", "OFF-Data Entry Keyers", "OFF-Word Processors And Typists", "OFF-Insurance Claims And Policy Processing Clerks", "OFF-Mail Clerks And Mail Machine Operators, Except Postal Service", "OFF-Office Clerks, General", "OFF-Office Machine Operators, Except Computer", "OFF-Proofreaders And Copy Markers", "OFF-Statistical Assistants", "OFF-Other Office And Administrative Support Workers", "FFF-First-Line Supervisors Of Farming, Fishing, And Forestry Workers", "FFF-Agricultural Inspectors", "FFF-Graders And Sorters, Agricultural Products", "FFF-Other Agricultural Workers", "FFF-Fishing And Hunting Workers", "FFF-Forest And Conservation Workers", "FFF-Logging Workers", "CON-First-Line Supervisors Of Construction Trades And Extraction Workers", "CON-Boilermakers", "CON-Carpenters", "CON-Carpet, Floor, And Tile Installers And Finishers", "CON-Cement Masons, Concrete Finishers, And Terrazzo Workers", "CON-Construction Laborers", "CON-Construction Equipment Operators", "CON-Drywall Installers, Ceiling Tile Installers, And Tapers", "CON-Electricians", "CON-Glaziers", "CON-Insulation Workers", "CON-Painters And Paperhangers", "CON-Pipelayers", "CON-Plumbers, Pipefitters, And Steamfitters", "CON-Plasterers And Stucco Masons", "CON-Roofers", "CON-Sheet Metal Workers", "CON-Structural Iron And Steel Workers", "CON-Solar Photovoltaic Installers", "CON-Brickmasons, Blockmasons, Stonemasons, And Reinforcing Iron And Rebar Workers", "CON-Helpers, Construction Trades", "CON-Construction And Building Inspectors", "CON-Elevator And Escalator Installers And Repairers", "CON-Fence Erectors", "CON-Hazardous Materials Removal Workers", "CON-Highway Maintenance Workers", "CON-Rail-Track Laying And Maintenance Equipment Operators", "CON-Other Construction And Related Workers", "EXT-Derrick, Rotary Drill, And Service Unit Operators, And Roustabouts, Oil, Gas, And Mining", "EXT-Surface Mining Machine Operators And Earth Drillers", "EXT-Explosives Workers, Ordnance Handling Experts, And Blasters", "EXT-Underground Mining Machine Operators", "EXT-Other Extraction Workers", "RPR-First-Line Supervisors Of Mechanics, Installers, And Repairers", "RPR-Computer, Automated Teller, And Office Machine Repairers", "RPR-Radio And Telecommunications Equipment Installers And Repairers", "RPR-Avionics Technicians", "RPR-Electric Motor, Power Tool, And Related Repairers", "RPR-Other Electrical And Electronic Equipment Mechanics, Installers, and Repairers", "RPR-Audiovisual Equipment Installers And Repairers", "RPR-Security And Fire Alarm Systems Installers", "RPR-Aircraft Mechanics And Service Technicians", "RPR-Automotive Body And Related Repairers", "RPR-Automotive Glass Installers And Repairers", "RPR-Automotive Service Technicians And Mechanics", "RPR-Bus And Truck Mechanics And Diesel Engine Specialists", "RPR-Heavy Vehicle And Mobile Equipment Service Technicians And Mechanics", "RPR-Small Engine Mechanics", "RPR-Miscellaneous Vehicle And Mobile Equipment Mechanics, Installers, And Repairers", "RPR-Control And Valve Installers And Repairers", "RPR-Heating, Air Conditioning, And Refrigeration Mechanics And Installers", "RPR-Home Appliance Repairers", "RPR-Industrial And Refractory Machinery Mechanics", "RPR-Maintenance Workers, Machinery", "RPR-Millwrights", "RPR-Electrical Power-Line Installers And Repairers", "RPR-Telecommunications Line Installers And Repairers", "RPR-Precision Instrument And Equipment Repairers", "RPR-Maintenance And Repair Workers, General", "RPR-Coin, Vending, And Amusement Machine Servicers And Repairers", "RPR-Locksmiths And Safe Repairers", "RPR-Riggers", "RPR-Helpers--Installation, Maintenance, And Repair Workers", "RPR-Other Installation, Maintenance, And Repair Workers", "PRD-First-Line Supervisors Of Production And Operating Workers", "PRD-Electrical, Electronics, And Electromechanical Assemblers", "PRD-Engine And Other Machine Assemblers", "PRD-Structural Metal Fabricators And Fitters", "PRD-Other Assemblers and Fabricators", "PRD-Bakers", "PRD-Butchers And Other Meat, Poultry, And Fish Processing Workers", "PRD-Food And Tobacco Roasting, Baking, And Drying Machine Operators And Tenders", "PRD-Food Batchmakers", "PRD-Food Cooking Machine Operators And Tenders", "PRD-Food Processing Workers, All Other", "PRD-Computer Numerically Controlled Tool Operators And Programmers", "PRD-Forming Machine Setters, Operators, And Tenders, Metal And Plastic", "PRD-Cutting, Punching, And Press Machine Setters, Operators, And Tenders, Metal And Plastic", "PRD-Grinding, Lapping, Polishing, And Buffing Machine Tool Setters, Operators, And Tenders, Metal and Plastic", "PRD-Other Machine Tool Setters, Operators, And Tenders, Metal And Plastic", "PRD-Machinists", "PRD-Metal Furnace Operators, Tenders, Pourers, And Casters", "PRD-Model Makers, Patternmakers, And Molding Machine Setters, Metal And Plastic", "PRD-Tool And Die Makers", "PRD-Welding, Soldering, And Brazing Workers", "PRD-Other Metal Workers And Plastic Workers", "PRD-Prepress Technicians And Workers", "PRD-Printing Press Operators", "PRD-Print Binding And Finishing Workers", "PRD-Laundry And Dry-Cleaning Workers", "PRD-Pressers, Textile, Garment, And Related Materials", "PRD-Sewing Machine Operators", "PRD-Shoe And Leather Workers", "PRD-Tailors, Dressmakers, And Sewers", "PRD-Textile Machine Setters, Operators, And Tenders", "PRD-Upholsterers", "PRD-Other Textile, Apparel, And Furnishings Workers", "PRD-Cabinetmakers And Bench Carpenters", "PRD-Furniture Finishers", "PRD-Sawing Machine Setters, Operators, And Tenders, Wood", "PRD-Woodworking Machine Setters, Operators, And Tenders, Except Sawing", "PRD-Other Woodworkers", "PRD-Power Plant Operators, Distributors, And Dispatchers", "PRD-Stationary Engineers And Boiler Operators", "PRD-Water And Wastewater Treatment Plant And System Operators", "PRD-Miscellaneous Plant And System Operators", "PRD-Chemical Processing Machine Setters, Operators, And Tenders", "PRD-Crushing, Grinding, Polishing, Mixing, And Blending Workers", "PRD-Cutting Workers", "PRD-Extruding, Forming, Pressing, And Compacting Machine Setters, Operators, And Tenders", "PRD-Furnace, Kiln, Oven, Drier, And Kettle Operators And Tenders", "PRD-Inspectors, Testers, Sorters, Samplers, And Weighers", "PRD-Jewelers And Precious Stone And Metal Workers", "PRD-Dental And Ophthalmic Laboratory Technicians And Medical Appliance Technicians", "PRD-Packaging And Filling Machine Operators And Tenders", "PRD-Painting Workers", "PRD-Photographic Process Workers And Processing Machine Operators", "PRD-Adhesive Bonding Machine Operators And Tenders", "PRD-Etchers And Engravers", "PRD-Molders, Shapers, And Casters, Except Metal And Plastic", "PRD-Paper Goods Machine Setters, Operators, And Tenders", "PRD-Tire Builders", "PRD-Helpers--Production Workers", "PRD-Miscellaneous Production Workers, Including Equipment Operators and Tenders", "TRN-Supervisors Of Transportation And Material Moving Workers", "TRN-Aircraft Pilots And Flight Engineers", "TRN-Air Traffic Controllers And Airfield Operations Specialists", "TRN-Flight Attendants", "TRN-Ambulance Drivers And Attendants, Except Emergency Medical Technicians", "TRN-Bus Drivers, School", "TRN-Bus Drivers, Transit And Intercity", "TRN-Driver / Sales Workers And Truck Drivers", "TRN-Shuttle Drivers and Chauffeurs", "TRN-Taxi Drivers", "TRN-Motor Vehicle Operators, All Other", "TRN-Locomotive Engineers And Operators", "TRN-Railroad Conductors And Yardmasters", "TRN-Other Rail Transportation Workers", "TRN-Sailors And Marine Oilers, And Ship Engineers", "TRN-Ship And Boat Captains And Operators", "TRN-Parking Attendants", "TRN-Transportation Service Attendants", "TRN-Transportation Inspectors", "TRN-Passenger Attendants", "TRN-Other Transportation Workers", "TRN-Crane And Tower Operators", "TRN-Conveyor, Dredge, And Hoist And Winch Operators", "TRN-Industrial Truck And Tractor Operators", "TRN-Cleaners Of Vehicles And Equipment", "TRN-Laborers And Freight, Stock, And Material Movers, Hand", "TRN-Machine Feeders And Offbearers", "TRN-Packers And Packagers, Hand", "TRN-Stockers And Order Fillers", "TRN-Pumping Station Operators", "TRN-Refuse And Recyclable Material Collectors", "TRN-Other Material Moving Workers", "MIL-Military Officer Special And Tactical Operations Leaders", "MIL-First-Line Enlisted Military Supervisors", "MIL-Military Enlisted Tactical Operations And Air / Weapons Specialists And Crew Members", "MIL-Military, Rank Not Specified", "Unemployed, With No Work Experience In The Last 5 Years Or Earlier Or Never Worked"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-09-13 16:14:48"),
  # 
  # ownchild__oc = list(
  #   ASEC = list(
  #     groups = 1:2,
  #     levels = c("Not child (<18) of householder", "Child (<18) of householder"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 1:2,
  #     levels = c("No", "Yes"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-09-13 13:11:32"),
  # 
  # ownershp__ten = list(
  #   ASEC = list(
  #     groups = 1:3,
  #     levels = c("Owned or being bought", "No cash rent", "With cash rent"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = c(1, 1, 3, 2),
  #     levels = c("Owned with mortgage or loan (include home equity loans)", "Owned free and clear", "Rented", "Occupied without payment of rent"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "Same as hhtenure in ASEC",
  #   modified = "2023-01-06 16:14:17"),
  # 
  # phone__tel = list(
  #   ASEC = list(
  #     groups = c(1, 1, 2),
  #     levels = c("No, no phone available", "Yes, phone available", "Yes, phone in household"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 2:1,
  #     levels = c("Yes", "No"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = FALSE,
  #   comment = "Only 'phone in household' (not also 'phone available') is equivalent to the ACS's question on phone service. From IPUMS: 'For later census years and the ACS, category 3 in IPUMS-CPS is comparable to a 'yes' response in IPUMS-USA.'",
  #   modified = "2023-01-06 16:20:05"),
  # 
  # prvtcovnw__privcov = list(
  #   ASEC = list(
  #     groups = 1:2,
  #     levels = c("No", "Yes"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 2:1,
  #     levels = c("With private health insurance coverage", "Without private health insurance coverage"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-09-02 13:26:43"),
  # 
  # race__rac3p = list(
  #   ASEC = list(
  #     groups = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 21, 21, 21, 20, 21, 22),
  #     levels = c("White", "Black", "American Indian/Aleut/Eskimo", "Asian only", "Hawaiian/Pacific Islander only", "White-Black", "White-American Indian", "White-Asian", "White-Hawaiian/Pacific Islander", "Black-American Indian", "Black-Asian", "Black-Hawaiian/Pacific Islander", "American Indian-Asian", "Asian-Hawaiian/Pacific Islander", "White-Black-American Indian", "White-Black-Asian", "White-American Indian-Asian", "White-Asian-Hawaiian/Pacific Islander", "White-Black-American Indian-Asian", "American Indian-Hawaiian/Pacific Islander", "White-Black--Hawaiian/Pacific Islander", "White-American Indian-Hawaiian/Pacific Islander", "Black-American Indian-Asian", "White-American Indian-Asian-Hawaiian/Pacific Islander", "Two or three races, unspecified", "Four or five races, unspecified"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = c(1, 2, 3, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 21, 6, 7, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 21, 10, 11, 11, 11, 11, 11, 11, 12, 21, 13, 13, 21, 4, 4, 4, 4, 4, 4, 4, 14, 4, 14, 14, 21, 4, 14, 4, 14, 21, 21, 15, 16, 21, 17, 21, 8, 8, 18, 18, 18, 21, 14, 18, 18, 11, 12, 4, 4, 16, 17, 21, 19, 22, 22, 20, 22, 22, 22, 22, 22, 22, 22, 22, 22, 14, 21, 21, 21, 21, 21, 22),
  #     levels = c("White alone", "Black or African American alone", "American Indian and Alaska Native alone", "Asian Indian alone", "Chinese alone", "Filipino alone", "Japanese alone", "Korean alone", "Vietnamese alone", "Other Asian alone", "Native Hawaiian alone", "Guamanian or Chamorro alone", "Samoan alone", "Other Pacific Islander alone", "Some Other Race alone", "White; Black or African American", "White; American Indian and Alaska Native", "White; Asian Indian", "White; Chinese", "White; Filipino", "White; Japanese", "White; Korean", "White; Vietnamese", "White; Other Asian", "White; Native Hawaiian", "White; Guamanian or Chamorro", "White; Samoan", "White; Other Pacific Islander", "White; Some Other Race", "Black or African American; American Indian and Alaska Native", "Black or African American; Asian Indian", "Black or African American; Chinese", "Black or African American; Filipino", "Black or African American; Japanese", "Black or African American; Korean", "Black or African American; Other Asian", "Black or African American; Other Pacific Islander", "Black or African American; Some Other Race", "American Indian and Alaska Native; Asian Indian", "American Indian and Alaska Native; Filipino", "American Indian and Alaska Native; Some Other Race", "Asian Indian; Other Asian", "Asian Indian; Some Other Race", "Chinese; Filipino", "Chinese; Japanese", "Chinese; Korean", "Chinese; Vietnamese", "Chinese; Other Asian", "Chinese; Native Hawaiian", "Filipino; Japanese", "Filipino; Native Hawaiian", "Filipino; Other Pacific Islander", "Filipino; Some Other Race", "Japanese; Korean", "Japanese; Native Hawaiian", "Vietnamese; Other Asian", "Other Asian; Other Pacific Islander", "Other Asian; Some Other Race", "Other Pacific Islander; Some Other Race", "White; Black or African American; American Indian and Alaska Native", "White; Black or African American; Filipino", "White; Black or African American; Some Other Race", "White; American Indian and Alaska Native; Filipino", "White; American Indian and Alaska Native; Some Other Race", "White; Chinese; Filipino", "White; Chinese; Japanese", "White; Chinese; Native Hawaiian", "White; Filipino; Native Hawaiian", "White; Japanese; Native Hawaiian", "White; Other Asian; Some Other Race", "Chinese; Filipino; Native Hawaiian", "White; Chinese; Filipino; Native Hawaiian", "White; Chinese; Japanese; Native Hawaiian", "Black or African American; Asian groups", "Black or African American; Native Hawaiian and Other Pacific Islander groups", "Asian Indian; Asian groups", "Filipino; Asian groups", "White; Black or African American; Asian groups", "White; American Indian and Alaska Native; Asian groups", "White; Native Hawaiian and Other Pacific Islander groups; and / Or Some Other Race", "White; Black or African American; American Indian and Alaska Native; Asian groups", "White; Black or African American; American Indian and Alaska Native; and / Or Native Hawaiian and Other Pacific Islander groups; and / Or Some Other Race", "White; Black or African American; and / Or Asian groups; and / Or Native Hawaiian and Other Pacific Islander groups; and / Or Some Other Race", "White; American Indian and Alaska Native; and / Or Asian groups; and / Or Native Hawaiian and Other Pacific Islander groups", "White; Chinese; Filipino; and / Or Asian groups; and / Or Native Hawaiian and Other Pacific Islander groups; and / Or Some Other Race", "White; Chinese; and / Or Asian groups; and / Or Native Hawaiian and Other Pacific Islander groups; and / Or Some Other Race", "White; Filipino; and / Or Native Hawaiian and Other Pacific Islander groups; and / Or Some Other Race", "White; Japanese; and / Or Asian groups; and / Or Native Hawaiian and Other Pacific Islander groups; and / Or Some Other Race", "White; Asian groups; and / Or Native Hawaiian and Other Pacific Islander groups; and / Or Some Other Race", "Black or African American; American Indian and Alaska Native; and / Or Asian groups; and / Or Native Hawaiian and Other Pacific Islander groups; and / Or Some Other Race", "Black or African American; Asian groups; and / Or Native Hawaiian and Other Pacific Islander groups; and / Or Some Other Race", "American Indian and Alaska Native; Asian groups; and / Or Native Hawaiian and Other Pacific Islander groups; and / Or Some Other Race", "Asian Indian; and / Or White; and / Or Asian groups; and / Or Native Hawaiian and Other Pacific Islander groups; and / Or Some Other Race", "Chinese; Japanese; Native Hawaiian; and / Or other Asian and / Or Pacific Islander groups", "Chinese; and / Or Asian groups; and / Or Native Hawaiian and Other Pacific Islander groups; and / Or Some Other Race", "Filipino; and / Or Asian groups; and / Or Native Hawaiian and Other Pacific Islander groups; and / Or Some Other Race", "Japanese; and / Or Asian groups; and / Or Native Hawaiian and Other Pacific Islander groups; and / Or Some Other Race", "Korean; and / Or Vietnamese; and / Or Other Asian; and / Or Native Hawaiian and Other Pacific Islander groups; and / Or Some Other Race", "Native Hawaiian; and / Or Pacific Islander groups; and / Or Some Other Race", "White; and / Or Black or African American; and / Or American Indian and Alaska Native; and / Or Asian groups; and / Or Native Hawaiian and Other Pacific Islander groups; and / Or Some Other Race"),
  #     breaks = "",
  #     adj = "",
  #     agg = logical(0)
  #   ),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-09-02 13:49:01"),
  # 
  # asec_division__region = list(
  #   ASEC = list(
  #     groups = c(2, 3, 1, 4, 1, 4, 3, 2, 3),
  #     levels = c("East North Central", "East South Central", "Middle Atlantic", "Mountain", "New England", "Pacific", "South Atlantic", "West North Central", "West South Central"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 1:4,
  #     levels = c("Northeast", "Midwest", "South", "West"),
  #     breaks = "",
  #     adj = "",
  #     agg = "reference"),
  #   ordered = FALSE,
  #   comment = "",
  #   modified = "2023-01-06 16:26:19"),
  # 
  # relate__relshipp = list(
  #   ASEC = list(
  #     groups = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 12),
  #     levels = c("Head/householder", "Opposite sex spouse", "Same sex spouse", "Child", "Parent", "Sibling", "Grandchild", "Other relatives, n.s.", "Housemate/roomate", "Opposite sex unmarried partner", "Same sex unmarried partner", "Roomer/boarder/lodger", "Foster children", "Other nonrelatives"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = c(1, 2, 10, 3, 11, 4, 4, 4, 6, 5, 7, 5, 4, 8, 9, 13, 12, NA, NA),
  #     levels = c("Reference person", "Opposite-sex husband / Wife / Spouse", "Opposite-sex unmarried partner", "Same-sex husband / Wife / Spouse", "Same-sex unmarried partner", "Biological son or daughter", "Adopted son or daughter", "Stepson or stepdaughter", "Brother or sister", "Father or mother", "Grandchild", "Parent-in-law", "Son-in-law or daughter-in-law", "Other relative", "Roommate or housemate", "Foster child", "Other nonrelative", "Institutionalized group quarters population", "Noninstitutionalized group quarters population"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "Assuming in-laws are parents or siblings, not 'other relatives'. Assuming that roomer/boarder is 'other non-relative'.",
  #   modified = "2022-09-02 16:49:26"),
  # 
  # schlcoll__sch = list(
  #   ASEC = list(
  #     groups = c(1, 2, 2, 2, 2, 3),
  #     levels = c("NIU: Less than 16 or older than 55", "High school full time", "High school part time", "College or university full time", "College or university part time", "Does not attend school, college or university"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = c(1, 3, 2, 2),
  #     levels = c("NIU: Less than 16 or older than 55", "No, has not attended in the last 3 months", "Yes, public school or public college", "Yes, private school or college or home school"),
  #     breaks = "",
  #     adj = "if_else(agep < 16 | agep > 55, factor(\"NIU: Less than 16 or older than 55\", levels = c(\"NIU: Less than 16 or older than 55\", levels(sch))\n), factor(sch, levels = c(\"NIU: Less than 16 or older than 55\", levels(sch)))\n)",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-09-13 14:48:59"),
  # 
  # sex__sex = list(
  #   ASEC = list(
  #     groups = 1:2,
  #     levels = c("Male", "Female"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 1:2,
  #     levels = c("Male", "Female"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-09-02 16:55:05"),
  # 
  # trccovnw__hins5 = list(
  #   ASEC = list(
  #     groups = 1:2,
  #     levels = c("No", "Yes"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 2:1,
  #     levels = c("Yes", "No"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-09-02 13:32:42"),
  # 
  # uhrsworkly__wkhp = list(
  #   ASEC = list(
  #     groups = 1,
  #     levels = "Min: 0, Median: 12, Mean: 20.06, Max: 99",
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 1,
  #     levels = "Min: 0, Median: 15, Mean: 20.33, Max: 99",
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = "",
  #   comment = "Slight misalignment in universe - CPS starts at 15 and ACS starts at 16, before those is zero for both",
  #   modified = "2022-09-02 16:59:19"),
  # 
  # unitsstr__bld = list(
  #   ASEC = list(
  #     groups = 1:6,
  #     levels = c("Mobile home or trailer", "2 family building", "3-4 family building", "5-9 family building", "One unit, unspecified type", "10+ units in structure"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = c(1, 5, 5, 2, 3, 4, 6, 6, 6, 1),
  #     levels = c("Mobile home or trailer", "One-family house detached", "One-family house attached", "2 Apartments", "3-4 Apartments", "5-9 Apartments", "10-19 Apartments", "20-49 Apartments", "50 or more apartments", "Boat, RV, van, etc."),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "No code for 'boat, RV, van etc' in CPS - placed in Mobile home or trailer",
  #   modified = "2023-01-06 16:35:04"),
  # 
  # vacovnw__hins6 = list(
  #   ASEC = list(
  #     groups = 1:2,
  #     levels = c("No", "Yes"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 2:1,
  #     levels = c("Yes", "No"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-09-02 13:33:25"),
  # 
  # vetserv__vps = list(
  #   ASEC = list(
  #     groups = 1:11,
  #     levels = c("NIU: Under 17 or have not served in the U.S. Armed Forces", "September 2001 or later", "August 1990 to August 2001", "May 1975 to July 1990", "Vietnam Era (August 1964 to April 1975)", "February 1955 to July 1964", "Korean War (July 1950 to January 1955)", "January 1947 to June 1950", "World War II (December 1941 to December 1946)", "November 1941 or earlier", "Served multiple periods"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = c(1, 2, 11, 11, 3, 11, 5, 11, 11, 7, 11, 9, 4, 6, 8, 10),
  #     levels = c("Never served in military", "Gulf War: 9/2001 or later", "Gulf War: 9/2001 or later and Gulf War: 8/1990 - 8/2001", "Gulf War: 9/2001 or later and Gulf War: 8/1990 - 8/2001 and Vietnam Era", "Gulf War: 8/1990 - 8/2001", "Gulf War: 8/1990 - 8/2001 and Vietnam Era", "Vietnam Era", "Vietnam Era and Korean War", "Vietnam Era, Korean War, and WWII", "Korean War", "Korean War and WWII", "WWII", "Between Gulf War and Vietnam Era only", "Between Vietnam Era and Korean War only", "Between Korean War and World War II only", "Pre-WWII only"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-09-08 17:26:36"),
  # 
  # vetstat__vps = list(
  #   ASEC = list(
  #     groups = c(1, 1, 2),
  #     levels = c("NIU: Less than 17", "No service", "Yes"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = c(1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2),
  #     levels = c("Never served in military", "Gulf War: 9/2001 or later", "Gulf War: 9/2001 or later and Gulf War: 8/1990 - 8/2001", "Gulf War: 9/2001 or later and Gulf War: 8/1990 - 8/2001 and Vietnam Era", "Gulf War: 8/1990 - 8/2001", "Gulf War: 8/1990 - 8/2001 and Vietnam Era", "Vietnam Era", "Vietnam Era and Korean War", "Vietnam Era, Korean War, and WWII", "Korean War", "Korean War and WWII", "WWII", "Between Gulf War and Vietnam Era only", "Between Vietnam Era and Korean War only", "Between Korean War and World War II only", "Pre-WWII only"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-09-02 17:04:40"),
  # 
  # wkswork1__wkwn = list(
  #   ASEC = list(
  #     groups = 1,
  #     levels = "Min: 0, Median: 12, Mean: 24.5, Max: 52",
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = 1,
  #     levels = "Min: 0, Median: 12, Mean: 24.6, Max: 52",
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = "",
  #   comment = "",
  #   modified = "2022-09-02 17:05:47"),
  # 
  # wnlwnilf__wkl = list(
  #   ASEC = list(
  #     groups = 1:4,
  #     levels = c("NIU: Less than 15 or older than 49 or in the labor force last week", "Within past 12 months", "More than 12 months ago", "Never worked"),
  #     breaks = "",
  #     adj = "if_else(age != '15', wnlwnilf, factor('NIU: Less than 15 or older than 49 or in the labor force last week',\nordered = T, levels = levels(wnlwnilf))\n)"),
  #   ACS = list(
  #     groups = 1:4,
  #     levels = c("Less than 16 years old", "Within the past 12 months", "1-5 years ago", "Over 5 years ago or never worked"),
  #     breaks = "",
  #     adj = "if_else(agep <= 49, wkl, factor(\"Less than 16 years old\", \nordered = T, levels = levels(wkl)))",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "Adjust NIU to the smallest overlapping age range: 16-49",
  #   modified = "2022-09-02 17:14:18"),
  # 
  # workly__wkl = list(
  #   ASEC = list(
  #     groups = 1:3,
  #     levels = c("NIU: Non-adult", "No", "Yes"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = c(1, 3, 2, 2),
  #     levels = c("Less than 16 years old", "Within the past 12 months", "1-5 years ago", "Over 5 years ago or never worked"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-09-02 17:15:35"),
  # 
  # yrimmig__yoep = list(
  #   ASEC = list(
  #     groups = 1:26,
  #     levels = c("NIU: Born in the US", "1949 or earlier", "1950-1959", "1960-1964", "1965-1969", "1970-1974", "1975-1979", "1980-1981", "1982-1983", "1984-1985", "1986-1987", "1988-1989", "1990-1991", "1992-1993", "1994-1995", "1996-1997", "1998-1999 (1999 CPS: 1996-1999)", "2000-2001 (2001 CPS: 1998-2001)", "2002-2003 (2003 CPS: 2000-2003)", "2004-2005 (2005 CPS: 2002-2005)", "2004-2007", "2006-2009 (2012 CPS forward: 2008-2009)", "2008-2011 (2014 CPS forward: 2010-2011)", "2010-2013 (2016 CPS forward: 2012-2013)", "2012-2015 (2018 CPS forward: 2014-2015)", "2016-2019"),
  #     breaks = "",
  #     adj = ""),
  #   ACS = list(
  #     groups = c(1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16, 17, 17, 18, 18, 19, 19, 20, 20, 21, 21, 22, 22, 23, 23, 24, 24, 25, 25, 26, 26, 26, 26),
  #     levels = c("Born in the U.S.", "1929 or earlier (Bottom-coded)", "1930 - 1934", "1935 - 1938", "1939 - 1940", "1941 - 1942", "1943 - 1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019"),
  #     breaks = "",
  #     adj = "",
  #     agg = ""),
  #   ordered = TRUE,
  #   comment = "",
  #   modified = "2022-09-02 17:21:54")
)
