list(

  hefaminc__hincp = list(
    CPS = list(
      groups = 1:15,
      levels = c("5,000 TO 7,499", "7,500 TO 9,999", "10,000 TO 12,499", "12,500 TO 14,999", "15,000 TO 19,999", "20,000 TO 24,999", "25,000 TO 29,999", "30,000 TO 34,999", "35,000 TO 39,999", "40,000 TO 49,999", "50,000 TO 59,999", "60,000 TO 74,999", "75,000 TO 99,999", "100,000 TO 149,999", "150,000 OR MORE"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:15,
      levels = c("Less than 7500", "[7500 to 10000)", "[10000 to 12500)", "[12500 to 15000)", "[15000 to 20000)", "[20000 to 25000)", "[25000 to 30000)", "[30000 to 35000)", "[35000 to 40000)", "[40000 to 50000)", "[50000 to 60000)", "[60000 to 75000)", "[75000 to 100000)", "[100000 to 150000)", "150000 or more"),
      breaks = c(7500, 10000, 12500, 15000, 20000, 25000, 30000, 35000, 40000, 50000, 60000, 75000, 100000, 150000),
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2025-06-06 18:40:27.736194"),

  hehousut__bld = list(
    CPS = list(
      groups = c(3, 3, 3, 3, 1, 1, 2, 2),
      levels = c("HOUSE, APARTMENT, FLAT", "HU IN NONTRANSIENT HOTEL, MOTEL, ETC.", "HU PERMANENT IN TRANSIENT HOTEL, MOTEL", "HU IN ROOMING HOUSE", "MOBILE HOME OR TRAILER W/NO PERM. ROOM ADDED", "MOBILE HOME OR TRAILER W/1 OR MORE PERM. ROOMS ADDED", "HU NOT SPECIFIED ABOVE", "OTHER UNIT NOT SPECIFIED ABOVE"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 3, 3, 3, 3, 3, 3, 3, 3, 2),
      levels = c("Mobile home or trailer", "One-family house detached", "One-family house attached", "2 Apartments", "3-4 Apartments", "5-9 Apartments", "10-19 Apartments", "20-49 Apartments", "50 or more apartments", "Boat, RV, van, etc."),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2025-06-07 07:49:01.322435"),

  hesp1__fs = list(
    CPS = list(
      groups = c(1, 2, 2),
      levels = c("Yes", "No", "Not poor"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:2,
      levels = c("Yes", "No"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2025-06-07 07:47:32.497859"),

  hetenure__ten = list(
    CPS = list(
      groups = 1:3,
      levels = c("OWNED OR BEING BOUGHT BY A HH MEMBER", "RENTED FOR CASH", "OCCUPIED WITHOUT PAYMENT OF CASH RENT"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 1, 2, 3),
      levels = c("Owned with mortgage or loan (include home equity loans)", "Owned free and clear", "Rented", "Occupied without payment of rent"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2025-06-07 07:47:54.992509"),

  hrhtype__hht = list(
    CPS = list(
      groups = c(1, 1, 2, 3, 2, 4, 5, 2, 2, 2),
      levels = c("HUSBAND/WIFE PRIMARY FAMILY (NEITHER AF)", "HUSB/WIFE PRIM. FAMILY (EITHER/BOTH AF)", "UNMARRIED CIVILIAN MALE-PRIM. FAM HHLDER", "UNMARRIED CIV. FEMALE-PRIM FAM HHLDER", "PRIMARY FAMILY HHLDER-RP IN AF, UNMAR.", "CIVILIAN MALE PRIMARY INDIVIDUAL", "CIVILIAN FEMALE PRIMARY INDIVIDUAL", "PRIMARY INDIVIDUAL HHLD-RP IN AF", "GROUP QUARTERS WITH FAMILY", "GROUP QUARTERS WITHOUT FAMILY"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 2, 3, 4, 4, 5, 5),
      levels = c("Married couple household", "Other family household: Male householder, no spouse present", "Other family household: Female householder, no spouse present", "Nonfamily household: Male householder: Living alone", "Nonfamily household: Male householder: Not living alone", "Nonfamily household: Female householder: Living alone", "Nonfamily household: Female householder: Not living alone"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2025-06-07 07:50:08.441229"),

  hrnumhou__np = list(
    CPS = list(
      groups = 1,
      levels = "Min: 1, Median: 2, Mean: 2.43, Max: 14",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 1, Median: 2, Mean: 2.47, Max: 20",
      breaks = "",
      adj = "",
      agg = logical(0)
    ),
    ordered = "",
    comment = "",
    modified = "2025-06-06 18:37:27.880685"),

  peafever__mil = list(
    CPS = list(
      groups = 1:2,
      levels = c("YES", "NO"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(2, 1, 1, 1, 2),
      levels = c("Less than 17 years old", "Now on active duty", "On active duty in the past, but not now", "Only on active duty for training in Reserves / National Guard", "Never served in the military"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2025-06-07 07:50:36.007227"),

  peafnow__mil = list(
    CPS = list(
      groups = 1:2,
      levels = c("YES", "NO"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(2, 1, 1, 1, 2),
      levels = c("Less than 17 years old", "Now on active duty", "On active duty in the past, but not now", "Only on active duty for training in Reserves / National Guard", "Never served in the military"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2025-06-07 07:50:59.074361"),

  peeduca__schl = list(
    CPS = list(
      groups = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 11, 12, 13, 14, 15),
      levels = c("LESS THAN 1ST GRADE", "1ST, 2ND, 3RD OR 4TH GRADE", "5TH OR 6TH GRADE", "7TH OR 8TH GRADE", "9TH GRADE", "10TH GRADE", "11TH GRADE", "12TH GRADE NO DIPLOMA", "HIGH SCHOOL GRAD-DIPLOMA OR EQUIV (GED)", "SOME COLLEGE BUT NO DEGREE", "ASSOCIATE DEGREE-OCCUPATIONAL/VOCATIONAL", "ASSOCIATE DEGREE-ACADEMIC PROGRAM", "BACHELOR'S DEGREE (EX: BA, AB, BS)", "MASTER'S DEGREE (EX: MA, MS, MEng, MEd, MSW)", "PROFESSIONAL SCHOOL DEG (EX: MD, DDS, DVM)", "DOCTORATE DEGREE (EX: PhD, EdD)"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 4, 4, 5, 6, 7, 8, 9, 9, 10, 10, 11, 12, 13, 14, 15),
      levels = c("Less than 3 years old", "No schooling completed", "Nursery school, preschool", "Kindergarten", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8", "Grade 9", "Grade 10", "Grade 11", "12th grade - no diploma", "Regular high school diploma", "GED or alternative credential", "Some college, but less than 1 year", "1 or more years of college credit, no degree", "Associate's degree", "Bachelor's degree", "Master's degree", "Professional degree beyond a bachelor's degree", "Doctorate degree"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = TRUE,
    comment = "",
    modified = "2025-06-07 07:52:41.289496"),

  peernhro__wkhp = list(
    CPS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 1.788, Max: 99",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 15, Mean: 20.33, Max: 99",
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = "",
    comment = "",
    modified = "2025-06-06 18:37:27.880827"),

  pehspnon__hisp = list(
    CPS = list(
      groups = 1:2,
      levels = c("HISPANIC", "NON-HISPANIC"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
      levels = c("Not Spanish / Hispanic / Latino", "Mexican", "Puerto Rican", "Cuban", "Dominican", "Costa Rican", "Guatemalan", "Honduran", "Nicaraguan", "Panamanian", "Salvadoran", "Other Central American", "Argentinean", "Bolivian", "Chilean", "Colombian", "Ecuadorian", "Paraguayan", "Peruvian", "Uruguayan", "Venezuelan", "Other South American", "Spaniard", "All Other Spanish / Hispanic / Latino"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2025-06-07 07:53:18.208931"),

  peio1cow__cow = list(
    CPS = list(
      groups = 1:9,
      levels = c("GOVERNMENT - FEDERAL", "GOVERNMENT - STATE", "GOVERNMENT - LOCAL", "PRIVATE, FOR PROFIT", "PRIVATE, NONPROFIT", "SELF-EMPLOYED, INCORPORATED", "SELF-EMPLOYED, UNINCORPORATED", "WITHOUT PAY", "NOT IN LABOR FORCE"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(9, 4, 5, 3, 2, 1, 7, 6, 8, 9),
      levels = c("Less than 16 years old / Not-in-labor-force who last worked more than 5 years ago or never worked", "Employee of a private for-profit company or business, or of an individual, for wages, salary, or commissions", "Employee of a private not-for-profit, tax-exempt, or charitable organization", "Local government employee (city, county, etc.)", "State government employee", "Federal government employee", "Self-employed in own not incorporated business, professional practice, or farm", "Self-employed in own incorporated business, professional practice or farm", "Working without pay in family business or farm", "Unemployed and last worked 5 years ago or earlier or never worked"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2025-06-07 07:54:10.326794"),

  peio1icd__indp = list(
    CPS = list(
      groups = c(19, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 18),
      levels = c("Not in industry", "Crop production", "Animal production", "Forestry except logging,", "Logging", "Fishing, hunting, and trapping", "Support activities for agriculture and forestry", "Oil and gas extraction", "Coal mining", "Metal ore mining", "Nonmetallic mineral mining and quarrying and not specified type of mining Part of", "Support activities for mining", "Electric power generation, transmission and distribution Pt.", "Natural gas distribution Pt.", "Electric and gas, and other combinations Pts.,", "Water, steam, air-conditioning, and irrigation systems,", "Sewage treatment facilities", "Not specified utilities Part of", "** Construction", "Animal food, grain and oilseed milling", "Sugar and confectionery products", "Fruit and vegetable preserving and specialty food manufacturing", "Dairy product manufacturing", "Animal slaughtering and processing", "Retail bakeries", "Bakeries, except retail", "Seafood and other miscellaneous foods, n.e.c.", "Not specified food industries", "Beverage manufacturing", "Tobacco manufacturing", "Fiber, yarn, and thread mills", "Fabric mills, except knitting", "Textile and fabric finishing and coating mills", "Carpet and rug mills", "Textile product mills, except carpets and rugs", "Cut and sew apparel manufacturing", "Apparel accessories and other apparel manufacturing", "Leather tanning and products, except footwear manufacturing", "Pulp, paper, and paperboard mills", "Paperboard containers and boxes", "Miscellaneous paper and pulp products", "Printing and related support activities", "Petroleum refining", "Miscellaneous petroleum and coal products", "Resin, synthetic rubber and fibers, and filaments manufacturing", "Agricultural chemical manufacturing", "Pharmaceutical and medicine manufacturing", "Paint, coating, and adhesive manufacturing B", "Soap, cleaning compound, and cosmetics manufacturing", "Industrial and miscellaneous chemicals", "Plastics product manufacturing", "Tire manufacturing", "Rubber products, except tires, manufacturing", "Pottery, ceramics, and related products manufacturing", "Structural clay product manufacturing", "Glass and glass product manufacturing", "Cement, concrete, lime, and gypsum product manufacturing", "Miscellaneous nonmetallic mineral product manufacturing", "Iron and steel mills and steel product manufacturing", "Aluminum production and processing", "Nonferrous metal, except aluminum, production and processing", "Foundries", "Metal forgings and stampings", "Cutlery and hand tool manufacturing", "Structural metals, and tank and shipping container manufacturing", "Machine shops; turned product; screw, nut and bolt manufacturing", "Coating, engraving, heat treating and allied activities", "Ordnance", "Miscellaneous fabricated metal products manufacturing", "Not specified metal industries", "Agricultural implement manufacturing", "Construction, mining and oil field machinery manufacturing", "Commercial and service industry machinery manufacturing", "Metalworking machinery manufacturing", "Engines, turbines, and power transmission equipment manufacturing", "Machinery manufacturing, n.e.c.", "Computer and peripheral equipment manufacturing", "Communications, audio, and video equipment manufacturing", "Navigational, measuring, electromedical, and control instruments manufacturing", "Electronic component and product manufacturing, n.e.c.", "Household appliance manufacturing", "Electrical lighting, equipment, and supplies manufacturing, n.e.c.", "Motor vehicles and motor vehicle equipment manufacturing", "Aircraft and parts manufacturing", "Aerospace products and parts manufacturing", "Railroad rolling stock manufacturing", "Ship and boat building", "Other transportation equipment manufacturing", "Sawmills and wood preservation", "Veneer, plywood, and engineered wood products", "Prefabricated wood buildings and mobile homes", "Miscellaneous wood products", "Furniture and related product manufacturing", "Medical equipment and supplies manufacturing", "Toys, amusement, and sporting goods manufacturing", "Miscellaneous manufacturing, n.e.c.", "Not specified manufacturing industries", "Motor vehicles, parts and supplies, merchant wholesalers", "Furniture and home furnishing, merchant wholesalers", "Lumber and other construction materials, merchant wholesalers", "Professional and commercial equipment and supplies, merchant wholesalers", "Metals and minerals, except petroleum, merchant wholesalers", "Electrical goods, merchant wholesalers", "Hardware, plumbing and heating equipment, and supplies, merchant wholesalers", "Machinery, equipment, and supplies, merchant wholesalers", "Recyclable material, merchant wholesalers", "Miscellaneous durable goods, merchant wholesalers", "Paper and paper products, merchant wholesalers", "Drugs, sundries, and chemical and allied products, merchant wholesalers", "Apparel, fabrics, and notions, merchant wholesalers", "Groceries and related products, merchant wholesalers", "Farm product raw materials, merchant wholesalers", "Petroleum and petroleum products, merchant wholesalers", "Alcoholic beverages, merchant wholesalers", "Farm supplies, merchant wholesalers", "Miscellaneous nondurable goods, merchant wholesalers", "Wholesale electronic markets, agents and brokers", "Not specified wholesale trade", "Automobile dealers", "Other motor vehicle dealers", "Auto parts, accessories, and tire stores", "Furniture and home furnishings stores", "Household appliance stores", "Radio, TV, and computer stores", "Building material and supplies dealers", "Hardware stores", "Lawn and garden equipment and supplies stores", "Grocery stores", "Specialty food stores", "Beer, wine, and liquor stores", "Pharmacies and drug stores", "Health and personal care, except drug, stores", "Gasoline stations", "Clothing and accessories, except shoe, stores", "Shoe stores", "Jewelry, luggage, and leather goods stores", "Sporting goods, camera, and hobby and toy stores", "Sewing, needlework, and piece goods stores", "Music stores", "Book stores and news dealers", "Department stores and discount stores", "Miscellaneous general merchandise stores", "Retail florists", "Office supplies and stationery stores", "Used merchandise stores", "Gift, novelty, and souvenir shops", "Miscellaneous retail stores", "Electronic shopping", "Mail order houses", "Vending machine operators", "Fuel dealers", "Other direct selling establishments", "Not specified retail trade", "Air transportation", "Rail transportation", "Water transportation", "Truck transportation", "Bus service and urban transit", "Taxi and limousine service", "Pipeline transportation", "Scenic and sightseeing transportation", "Services incidental to transportation", "Postal Service", "Couriers and messengers", "Warehousing and storage", "Newspaper publishers", "Publishing, except newspapers and software", "Software publishing", "Motion pictures and video industries", "Sound recording industries", "Radio and television broadcasting and cable", "Internet Publishing and Broadcasting", "Wired telecommunications carriers", "Other telecommunications services", "Data processing, hosting, and related services", "Libraries and archives", "Banking and related activities", "Savings institutions, including credit unions", "Non-depository credit and related activities", "Securities, commodities, funds, trusts, and other financial investments", "Insurance carriers and related activities", "Real estate", "Automotive equipment rental and leasing", "Video tape and disk rental", "Other consumer goods rental", "Commercial, industrial, and other intangible assets rental and leasing", "Legal services", "Accounting, tax preparation, bookkeeping, and payroll services", "Architectural, engineering, and related services", "Specialized design services", "Computer systems design and related services", "Management, scientific, and technical consulting services", "Scientific research and development services", "Advertising and related services", "Veterinary services", "Other professional, scientific, and technical services", "Management of companies and enterprises", "Employment services", "Business support services", "Travel arrangements and reservation services", "Investigation and security services", "Services to buildings and dwellings", "Landscaping services", "Other administrative and other support services", "Waste management and remediation services", "Elementary and secondary schools", "Colleges and universities, including junior colleges", "Business, technical, and trade schools and training", "Other schools, instruction, and educational services", "Offices of physicians", "Offices of dentists", "Offices of chiropractors", "Offices of optometrists", "Offices of other health practitioners", "Outpatient care centers", "Home health care services", "Other health care services", "Hospitals", "Nursing care facilities", "Residential care facilities, without nursing", "Individual and family services", "Community food and housing, and emergency services", "Vocational rehabilitation services", "Child day care services", "Independent artists, performing arts, spectator sports, and related industries", "Museums, art galleries, historical sites, and similar institutions", "Bowling centers", "Other amusement, gambling, and recreation industries", "Traveler accommodation", "Recreational vehicle parks and camps, and rooming and boarding houses", "Restaurants and other food services", "Drinking places, alcoholic beverages", "Automotive repair and maintenance", "Car washes", "Electronic and precision equipment repair and maintenance", "Commercial and industrial machinery and equipment repair and maintenance", "Personal and household goods repair and maintenance and", "Barber shops", "Beauty salons", "Nail salons and other personal care services", "Dry cleaning and laundry services", "Funeral homes, cemeteries, and crematories", "Other personal services", "Religious organizations", "Civic, social, advocacy organizations, and grant making and giving services", "Labor unions", "Business, professional, political, and similar organizations", "Private households", "Executive offices and legislative bodies", "Public finance activities", "Other general government and support", "Justice, public order, and safety activities", "Administration of human resource programs", "Administration of environmental quality and housing programs", "Administration of economic programs and space research", "National security and international affairs", "Armed Forces"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(19, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 19),
      levels = c("Less than 16 years old / Not-in-labor-force who last worked more than 5 years ago or never worked", "AGR-Crop Production", "AGR-Animal Production And Aquaculture", "AGR-Forestry Except Logging", "AGR-Logging", "AGR-Fishing, Hunting And Trapping", "AGR-Support Activities For Agriculture And Forestry", "EXT-Oil And Gas Extraction", "EXT-Coal Mining", "EXT-Metal Ore Mining", "EXT-Nonmetallic Mineral Mining And Quarrying", "EXT-Support Activities For Mining", "UTL-Electric Power Generation, Transmission And Distribution", "UTL-Natural Gas Distribution", "UTL-Electric And Gas, And Other Combinations", "UTL-Water, Steam, Air Conditioning, And Irrigation Systems", "UTL-Sewage Treatment Facilities", "UTL-Not Specified Utilities", "CON-Construction (The Cleaning Of Buildings And Dwellings Is Incidental During Construction And Immediately After Construction)", "MFG-Animal Food, Grain And Oilseed Milling", "MFG-Sugar And Confectionery Products", "MFG-Fruit And Vegetable Preserving And Specialty Foods", "MFG-Dairy Products", "MFG-Animal Slaughtering And Processing", "MFG-Retail Bakeries", "MFG-Bakeries And Tortilla, Except Retail Bakeries", "MFG-Seafood And Other Miscellaneous Foods, N.E.C.", "MFG-Not Specified Food Industries", "MFG-Beverage", "MFG-Tobacco", "MFG-Fiber, Yarn, And Thread Mills", "MFG-Fabric Mills, Except Knitting Mills", "MFG-Textile And Fabric Finishing And Fabric Coating Mills", "MFG-Carpet And Rug Mills", "MFG-Textile Product Mills, Except Carpet And Rug", "MFG-Knitting Fabric Mills, And Apparel Knitting Mills", "MFG-Cut And Sew Apparel", "MFG-Apparel Accessories And Other Apparel", "MFG-Footwear", "MFG-Leather Tanning And Finishing And Other Allied Products Manufacturing", "MFG-Pulp, Paper, And Paperboard Mills", "MFG-Paperboard Container", "MFG-Miscellaneous Paper And Pulp Products", "MFG-Printing And Related Support Activities", "MFG-Petroleum Refining", "MFG-Miscellaneous Petroleum And Coal Products", "MFG-Resin, Synthetic Rubber, And Fibers And Filaments", "MFG-Agricultural Chemicals", "MFG-Pharmaceuticals And Medicines", "MFG-Paint, Coating, And Adhesives", "MFG-Soap, Cleaning Compound, And Cosmetics", "MFG-Industrial And Miscellaneous Chemicals", "MFG-Plastics Products", "MFG-Tires", "MFG-Rubber Products, Except Tires", "MFG-Pottery, Ceramics, And Plumbing Fixture Manufacturing", "MFG-Clay Building Material And Refractories", "MFG-Glass And Glass Products", "MFG-Cement, Concrete, Lime, And Gypsum Products", "MFG-Miscellaneous Nonmetallic Mineral Products", "MFG-Iron And Steel Mills And Steel Products", "MFG-Aluminum Production And Processing", "MFG-Nonferrous Metal, Except Aluminum, Production And Processing", "MFG-Foundries", "MFG-Metal Forgings And Stampings", "MFG-Cutlery And Hand Tools", "MFG-Structural Metals, And Boiler, Tank, And Shipping Containers", "MFG-Machine Shops; Turned Products; Screws, Nuts And Bolts", "MFG-Coating, Engraving, Heat Treating And Allied Activities", "MFG-Ordnance", "MFG-Miscellaneous Fabricated Metal Products", "MFG-Not Specified Metal Industries", "MFG-Agricultural Implements", "MFG-Construction, And Mining And Oil And Gas Field Machinery", "MFG-Commercial And Service Industry Machinery", "MFG-Metalworking Machinery", "MFG-Engine, Turbine, And Power Transmission Equipment", "MFG-Machinery, N.E.C. Or Not Specified", "MFG-Computer And Peripheral Equipment", "MFG-Communications, And Audio And Video Equipment", "MFG-Navigational, Measuring, Electromedical, And Control Instruments", "MFG-Electronic Components And Products, N.E.C.", "MFG-Household Appliances", "MFG-Electric Lighting And Electrical Equipment Manufacturing, And Other Electrical Component Manufacturing, N.E.C.", "MFG-Motor Vehicles And Motor Vehicle Equipment", "MFG-Aircraft And Parts", "MFG-Aerospace Products And Parts", "MFG-Railroad Rolling Stock", "MFG-Ship And Boat Building", "MFG-Other Transportation Equipment", "MFG-Sawmills And Wood Preservation", "MFG-Veneer, Plywood, And Engineered Wood Products", "MFG-Prefabricated Wood Buildings And Mobile Homes", "MFG-Miscellaneous Wood Products", "MFG-Furniture And Related Products", "MFG-Medical Equipment And Supplies", "MFG-Sporting And Athletic Goods, And Doll, Toy, And Game Manufacturing", "MFG-Miscellaneous Manufacturing, N.E.C.", "MFG-Not Specified Manufacturing Industries", "WHL-Motor Vehicle And Motor Vehicle Parts And Supplies Merchant Wholesalers", "WHL-Furniture And Home Furnishing Merchant Wholesalers", "WHL-Lumber And Other Construction Materials Merchant Wholesalers", "WHL-Professional And Commercial Equipment And Supplies Merchant Wholesalers", "WHL-Metals And Minerals, Except Petroleum, Merchant Wholesalers", "WHL-Household Appliances And Electrical And Electronic Goods Merchant Wholesalers", "WHL-Hardware, And Plumbing And Heating Equipment, And Supplies Merchant Wholesalers", "WHL-Machinery, Equipment, And Supplies Merchant Wholesalers", "WHL-Recyclable Material Merchant Wholesalers", "WHL-Miscellaneous Durable Goods Merchant Wholesalers", "WHL-Paper And Paper Products Merchant Wholesalers", "WHL-Drugs, Sundries, And Chemical And Allied Products Merchant Wholesalers", "WHL-Apparel, Piece Goods, And Notions Merchant Wholesalers", "WHL-Grocery And Related Product Merchant Wholesalers", "WHL-Farm Product Raw Material Merchant Wholesalers", "WHL-Petroleum And Petroleum Products Merchant Wholesalers", "WHL-Alcoholic Beverages Merchant Wholesalers", "WHL-Farm Supplies Merchant Wholesalers", "WHL-Miscellaneous Nondurable Goods Merchant Wholesalers", "WHL-Wholesale Electronic Markets And Agents And Brokers", "WHL-Not Specified Wholesale Trade", "RET-Automobile Dealers", "RET-Other Motor Vehicle Dealers", "RET-Automotive Parts, Accessories, And Tire Stores", "RET-Furniture And Home Furnishings Stores", "RET-Household Appliance Stores", "RET-Electronics Stores", "RET-Building Material And Supplies Dealers", "RET-Hardware Stores", "RET-Lawn And Garden Equipment And Supplies Stores", "RET-Grocery Stores", "RET-Specialty Food Stores", "RET-Beer, Wine, And Liquor Stores", "RET-Pharmacies And Drug Stores", "RET-Health And Personal Care, Except Drug, Stores", "RET-Gasoline Stations", "RET-Clothing Stores", "RET-Shoe Stores", "RET-Jewelry, Luggage, And Leather Goods Stores", "RET-Sporting Goods, And Hobby And Toy Stores", "RET-Sewing, Needlework, And Piece Goods Stores", "RET-Musical Instrument And Supplies Stores", "RET-Book Stores And News Dealers", "RET-Department And Discount Stores", "RET-Miscellaneous General Merchandise Stores", "RET-Florists", "RET-Office Supplies And Stationery Stores", "RET-Used Merchandise Stores", "RET-Gift, Novelty, And Souvenir Shops", "RET-Miscellaneous Retail Stores", "RET-Electronic Shopping", "RET-Electronic Auctions", "RET-Mail-Order Houses", "RET-Vending Machine Operators", "RET-Fuel Dealers", "RET-Other Direct Selling Establishments", "RET-Not Specified Retail Trade", "TRN-Air Transportation", "TRN-Rail Transportation", "TRN-Water Transportation", "TRN-Truck Transportation", "TRN-Bus Service And Urban Transit", "TRN-Taxi And Limousine Service", "TRN-Pipeline Transportation", "TRN-Scenic And Sightseeing Transportation", "TRN-Services Incidental To Transportation", "TRN-Postal Service", "TRN-Couriers And Messengers", "TRN-Warehousing And Storage", "INF-Newspaper Publishers", "INF-Periodical, Book, And Directory Publishers", "INF-Software Publishers", "INF-Motion Picture And Video Industries", "INF-Sound Recording Industries", "INF-Broadcasting, Except Internet", "INF-Internet Publishing And Broadcasting And Web Search Portals", "INF-Wired Telecommunications Carriers", "INF-Telecommunications, Except Wired Telecommunications Carriers", "INF-Data Processing, Hosting, And Related Services", "INF-Libraries And Archives", "INF-Other Information Services, Except Libraries And Archives, And Internet Publishing And Broadcasting And Web Search Portals", "FIN-Banking And Related Activities", "FIN-Savings Institutions, Including Credit Unions", "FIN-Nondepository Credit And Related Activities", "FIN-Securities, Commodities, Funds, Trusts, And Other Financial Investments", "FIN-Insurance Carriers And Related Activities", "FIN-Real Estate", "FIN-Automotive Equipment Rental And Leasing", "FIN-Video Tape And Disk Rental", "FIN-Other Consumer Goods Rental", "FIN-Commercial, Industrial, And Other Intangible Assets Rental And Leasing", "PRF-Legal Services", "PRF-Accounting, Tax Preparation, Bookkeeping, And Payroll Services", "PRF-Architectural, Engineering, And Related Services", "PRF-Specialized Design Services", "PRF-Computer Systems Design And Related Services", "PRF-Management, Scientific, And Technical Consulting Services", "PRF-Scientific Research And Development Services", "PRF-Advertising, Public Relations, And Related Services", "PRF-Veterinary Services", "PRF-Other Professional, Scientific, And Technical Services", "PRF-Management Of Companies And Enterprises", "PRF-Employment Services", "PRF-Business Support Services", "PRF-Travel Arrangements And Reservation Services", "PRF-Investigation And Security Services", "PRF-Services To Buildings And Dwellings (Except Cleaning During Construction And Immediately After Construction)", "PRF-Landscaping Services", "PRF-Other Administrative And Other Support Services", "PRF-Waste Management And Remediation Services", "EDU-Elementary And Secondary Schools", "EDU-Colleges, Universities, And Professional Schools, Including Junior Colleges", "EDU-Business, Technical, And Trade Schools And Training", "EDU-Other Schools And Instruction, And Educational Support Services", "MED-Offices Of Physicians", "MED-Offices Of Dentists", "MED-Offices Of Chiropractors", "MED-Offices Of Optometrists", "MED-Offices Of Other Health Practitioners", "MED-Outpatient Care Centers", "MED-Home Health Care Services", "MED-Other Health Care Services", "MED-Hospitals", "MED-Nursing Care Facilities (Skilled Nursing Facilities)", "MED-Residential Care Facilities, Except Skilled Nursing Facilities", "SCA-Individual And Family Services", "SCA-Community Food And Housing, And Emergency Services", "SCA-Vocational Rehabilitation Services", "SCA-Child Day Care Services", "ENT-Performing Arts, Spectator Sports, And Related Industries", "ENT-Museums, Art Galleries, Historical Sites, And Similar Institutions", "ENT-Bowling Centers", "ENT-Other Amusement, Gambling, And Recreation Industries", "ENT-Traveler Accommodation", "ENT-Recreational Vehicle Parks And Camps, And Rooming And Boarding Houses", "ENT-Restaurants And Other Food Services", "ENT-Drinking Places, Alcoholic Beverages", "SRV-Automotive Repair And Maintenance", "SRV-Car Washes", "SRV-Electronic And Precision Equipment Repair And Maintenance", "SRV-Commercial And Industrial Machinery And Equipment Repair And Maintenance", "SRV-Personal And Household Goods Repair And Maintenance", "SRV-Barber Shops", "SRV-Beauty Salons", "SRV-Nail Salons And Other Personal Care Services", "SRV-Drycleaning And Laundry Services", "SRV-Funeral Homes, Cemeteries And Crematories", "SRV-Other Personal Services", "SRV-Religious Organizations", "SRV-Civic, Social, Advocacy Organizations, And Grantmaking And Giving Services", "SRV-Labor Unions", "SRV-Business, Professional, Political, And Similar Organizations", "SRV-Private Households", "ADM-Executive Offices And Legislative Bodies", "ADM-Public Finance Activities", "ADM-Other General Government And Support", "ADM-Justice, Public Order, And Safety Activities", "ADM-Administration Of Human Resource Programs", "ADM-Administration Of Environmental Quality And Housing Programs", "ADM-Administration Of Economic Programs And Space Research", "ADM-National Security And International Affairs", "Mil-U.S. Army", "MIL-U.S. Air Force", "MIL-U.S. Navy", "MIL-U.S. Marines", "MIL-U.S. Coast Guard", "MIL-U.S. Armed Forces, Branch Not Specified", "MIL-Military Reserves Or National Guard", "Unemployed And Last Worked 5 Years Ago Or Earlier Or Never Worked"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2025-06-07 18:15:43.520646"),

  pemaritl__mar = list(
    CPS = list(
      groups = c(1, 1, 2, 3, 4, 5),
      levels = c("MARRIED - SPOUSE PRESENT", "MARRIED - SPOUSE ABSENT", "WIDOWED", "DIVORCED", "SEPARATED", "NEVER MARRIED"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:5,
      levels = c("Married", "Widowed", "Divorced", "Separated", "Never married or under 15 years old"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2025-06-07 07:55:46.991177"),

  pemlr__esr = list(
    CPS = list(
      groups = c(2, 3, 4, 4, 1, 1, 1, 1),
      levels = c("EMPLOYED-AT WORK", "EMPLOYED-ABSENT", "UNEMPLOYED-ON LAYOFF", "UNEMPLOYED-LOOKING", "NOT IN LABOR FORCE-RETIRED", "NOT IN LABOR FORCE-DISABLED", "NOT IN LABOR FORCE-OTHER", "NOT IN LABOR FORCE-CHILD"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 2, 3, 4, 2, 3, 1),
      levels = c("Less than 16 years old", "Civilian employed, at work", "Civilian employed, with a job but not at work", "Unemployed", "Armed forces, at work", "Armed forces, with a job but not at work", "Not in labor force"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2025-06-07 07:56:56.831579"),

  penatvty__pobp = list(
    CPS = list(
      groups = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 87, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 103, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153),
      levels = c("United States", "American Samoa", "Guam", "Puerto Rico", "U. S. Virgin Islands", "Albania", "Austria", "Belgium", "Bulgaria", "Czechoslovakia", "Denmark", "Finland", "France", "Germany", "Greece", "Hungary", "Iceland", "Ireland", "Italy", "Netherlands", "Norway", "Poland", "Portugal", "Azores", "Romania", "Spain", "Sweden", "Switzerland", "United Kingdom", "England", "Scotland", "Northern Ireland", "Yugoslavia", "Slovakia", "Bosnia & Herzegovina", "Croatia", "Macedonia", "Serbia", "Estonia", "Latvia", "Lithuania", "Uzbekistan", "Vietnam", "Yemen", "Asia, not specified", "Bermuda", "Canada", "Mexico", "Belize", "Costa Rica", "El Salvador", "Guatemala", "Honduras", "Nicaragua", "Panama", "Antigua and Barbuda", "Bahamas", "Barbados", "Cuba", "Dominica", "Dominican Republic", "Grenada", "Haiti", "Jamaica", "St. Kitts--Nevis", "St. Vincent and the Grenadines", "Trinidad and Tobago", "West Indies, not specified", "Argentina", "Bolivia", "Brazil", "Chile", "Columbia", "Ecuador", "Guyana", "Peru", "Uruguay", "Venezuala", "South America, Not Specified", "Armenia", "Azerbaijan", "Belarus", "Georgia", "Moldova", "Russia", "Ukraine", "USSR", "Europe, not specified", "Montenegro", "Afghanistan", "Bangladesh", "Bhutan", "Myanmar (Burma)", "Cambodia", "China", "Hong Kong", "India", "Indonesia", "Iran", "Iraq", "Israel", "Japan", "Jordan", "Korea", "Kazakhstan", "South Korea", "Kuwait", "Laos", "Lebanon", "Malaysia", "Mongolia", "Nepal", "Pakistan", "Philippines", "Saudi Arabia", "Singapore", "Sri Lanka", "Syria", "Taiwan", "Thailand", "Turkey", "Americas, not specified", "Algeria", "Cameroon", "Cape Verde", "Congo", "Egypt", "Ethiopia", "Eritrea", "Ghana", "Guinea", "Kenya", "Liberia", "Libya", "Morocco", "Nigeria", "Senegal", "Sierra Leone", "Somalia", "South Africa", "Sudan", "Tanzania", "Togo", "Uganda", "Zaire", "Zimbabwe", "Africa, not specified", "Australia", "Fiji", "Marshall Islands", "Micronesia", "New Zealand", "Tonga", "Samoa", "Elsewhere"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 87, 34, 35, 36, 37, 38, 39, 40, 79, 80, 81, 82, 83, 84, 85, 86, 87, 87, 88, 87, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 44, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 44, 41, 42, 43, 44, 44, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 67, 65, 66, 67, 67, 68, 69, 70, 71, 72, 73, 74, 78, 75, 76, 77, 78, 120, 121, 122, 123, 124, 125, 126, 127, 145, 128, 129, 145, 130, 131, 132, 133, 134, 145, 135, 136, 137, 138, 139, 140, 141, 145, 142, 143, 145, 144, 145, 145, 145, 145, 145, 146, 147, 148, 149, 150, 151, 152, 153),
      levels = c("Alabama / AL", "Alaska / AK", "Arizona / AZ", "Arkansas / AR", "California / CA", "Colorado / CO", "Connecticut / CT", "Delaware / DE", "District of Columbia / DC", "Florida / FL", "Georgia / GA", "Hawaii / HI", "Idaho / ID", "Illinois / IL", "Indiana / IN", "Iowa / IA", "Kansas / KS", "Kentucky / KY", "Louisiana / LA", "Maine / ME", "Maryland / MD", "Massachusetts / MA", "Michigan / MI", "Minnesota / MN", "Mississippi / MS", "Missouri / MO", "Montana / MT", "Nebraska / NE", "Nevada / NV", "New Hampshire / NH", "New Jersey / NJ", "New Mexico / NM", "New York / NY", "North Carolina / NC", "North Dakota / ND", "Ohio / OH", "Oklahoma / OK", "Oregon / OR", "Pennsylvania / PA", "Rhode Island / RI", "South Carolina / SC", "South Dakota / SD", "Tennessee / TN", "Texas / TX", "Utah / UT", "Vermont / VT", "Virginia / VA", "Washington / WA", "West Virginia / WV", "Wisconsin / WI", "Wyoming / WY", "American Samoa", "Guam", "Commonwealth of the Northern Mariana Islands", "Puerto Rico", "US Virgin Islands", "Albania", "Austria", "Belgium", "Bulgaria", "Czechoslovakia", "Denmark", "Finland", "France", "Germany", "Greece", "Hungary", "Iceland", "Ireland", "Italy", "Netherlands", "Norway", "Poland", "Portugal", "Azores Islands", "Romania", "Spain", "Sweden", "Switzerland", "United Kingdom, Not Specified", "England", "Scotland", "Northern Ireland", "Yugoslavia", "Czech Republic", "Slovakia", "Bosnia and Herzegovina", "Croatia", "Macedonia", "Serbia", "Latvia", "Lithuania", "Armenia", "Azerbaijan", "Belarus", "Georgia", "Moldova", "Russia", "Ukraine", "USSR", "Europe", "Kosovo", "Montenegro", "Other Europe, Not Specified", "Afghanistan", "Bangladesh", "Bhutan", "Myanmar", "Cambodia", "China", "Hong Kong", "India", "Indonesia", "Iran", "Iraq", "Israel", "Japan", "Jordan", "Korea", "Kazakhstan", "Kyrgyzstan", "Kuwait", "Laos", "Lebanon", "Malaysia", "Mongolia", "Nepal", "Pakistan", "Philippines", "Saudi Arabia", "Singapore", "Sri Lanka", "Syria", "Taiwan", "Thailand", "Turkey", "United Arab Emirates", "Uzbekistan", "Vietnam", "Yemen", "Asia", "South Central Asia, Not Specified", "Other Asia, Not Specified", "Bermuda", "Canada", "Mexico", "Belize", "Costa Rica", "El Salvador", "Guatemala", "Honduras", "Nicaragua", "Panama", "Antigua & Barbuda", "Bahamas", "Barbados", "Cuba", "Dominica", "Dominican Republic", "Grenada", "Haiti", "Jamaica", "St. Kitts-Nevis", "St. Lucia", "St. Vincent & the Grenadines", "Trinidad & Tobago", "West Indies", "Caribbean, Not Specified", "Argentina", "Bolivia", "Brazil", "Chile", "Colombia", "Ecuador", "Guyana", "Paraguay", "Peru", "Uruguay", "Venezuela", "South America", "Americas, Not Specified", "Algeria", "Cameroon", "Cabo Verde", "Congo", "Egypt", "Ethiopia", "Eritrea", "Gambia", "Ghana", "Guinea", "Ivory Coast", "Kenya", "Liberia", "Libya", "Morocco", "Nigeria", "Rwanda", "Senegal", "Sierra Leone", "Somalia", "South Africa", "Sudan", "Tanzania", "Togo", "Tunisia", "Uganda", "Democratic Republic of Congo (Zaire)", "Zambia", "Zimbabwe", "Africa", "South Sudan", "Western Africa, Not Specified", "Other Africa, Not Specified", "Eastern Africa, Not Specified", "Australia", "Fiji", "Marshall Islands", "Micronesia", "New Zealand", "Tonga", "Samoa", "Other US Island Areas, Oceania, Not Specified, or at Sea"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2025-06-07 18:34:31.553423"),

  pesex__sex = list(
    CPS = list(
      groups = 1:2,
      levels = c("MALE", "FEMALE"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:2,
      levels = c("Male", "Female"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2025-06-07 07:57:39.241131"),

  prchld__hupaoc = list(
    CPS = list(
      groups = c(1, 2, 2, 3, 3, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4),
      levels = c("No own children under 18 years of age", "All own children 0- 2 years of age", "All own children 3- 5 years of age", "All own children 6-13 years of age", "All own children 14-17 years of age", "Own children 0- 2 and 3- 5 years of age (none 6-17)", "Own children 0- 2 and 14-17 years of age (none 3-13)", "Own children 3- 5 and 6-13 years of age (none 0- 2 or 14-17)", "Own children 3- 5 and 14-17 years of age (none 0- 2 or 6-13)", "Own children 6-13 and 14-17 years of age (none 0- 5)", "Own children 0- 2, 3- 5, and 6-13 years of age (none 14-17)", "Own children 0- 2, 3- 5, and 14-17 years of age (none 6-13)", "Own children 0- 2, 6-13, and 14-17 years of age (none 3- 5)", "Own children 3- 5, 6-13, and 14-17 years of age (none 0- 2)", "Own children from all age groups"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(2, 3, 4, 1),
      levels = c("Presence of own children under 6 years only", "Presence of own children 6 to 17 years only", "Presence of own children under 6 years and 6 to 17 years", "No own children present"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2025-06-07 07:55:19.32522"),

  prcitshp__cit = list(
    CPS = list(
      groups = 1:5,
      levels = c("NATIVE, BORN IN THE UNITED STATES", "NATIVE, BORN IN PUERTO RICO OR OTHER U.S. ISLAND AREAS", "NATIVE, BORN ABROAD OF AMERICAN PARENT OR PARENTS", "FOREIGN BORN, U.S. CITIZEN BY NATURALIZATION", "FOREIGN BORN, NOT A CITIZEN OF THE UNITED STATES"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:5,
      levels = c("Born in the U.S.", "Born in Puerto Rico, Guam, the U.S. Virgin Islands, or the Northern Marianas", "Born abroad of American parent(s)", "U.S. citizen by naturalization", "Not a citizen of the U.S."),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2025-06-07 07:57:59.726013"),

  prnmchld__noc = list(
    CPS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 0.482, Max: 10",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 0.497, Max: 14",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2025-06-06 18:37:27.880878"),

  prtage__agep = list(
    CPS = list(
      groups = 1:64,
      levels = c("16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80-84 Years Old", "85+ Years Old"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 12, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64),
      levels = c("Less than 17", "[17 to 18)", "[18 to 19)", "[19 to 20)", "[20 to 21)", "[21 to 22)", "[22 to 23)", "[23 to 24)", "[24 to 25)", "[25 to 26)", "[26 to 27)", "[27 to 28)", "[28 to 29)", "[29 to 30)", "[30 to 31)", "[31 to 32)", "[32 to 33)", "[33 to 34)", "[34 to 35)", "[35 to 36)", "[36 to 37)", "[37 to 38)", "[38 to 39)", "[39 to 40)", "[40 to 41)", "[41 to 42)", "[42 to 43)", "[43 to 44)", "[44 to 45)", "[45 to 46)", "[46 to 47)", "[47 to 48)", "[48 to 49)", "[49 to 50)", "[50 to 51)", "[51 to 52)", "[52 to 53)", "[53 to 54)", "[54 to 55)", "[55 to 56)", "[56 to 57)", "[57 to 58)", "[58 to 59)", "[59 to 60)", "[60 to 61)", "[61 to 62)", "[62 to 63)", "[63 to 64)", "[64 to 65)", "[65 to 66)", "[66 to 67)", "[67 to 68)", "[68 to 69)", "[69 to 70)", "[70 to 71)", "[71 to 72)", "[72 to 73)", "[73 to 74)", "[74 to 75)", "[75 to 76)", "[76 to 77)", "[77 to 78)", "[78 to 79)", "[79 to 80)", "[80 to 85)", "85 or more"),
      breaks = c(17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 85),
      adj = "",
      agg = "reference"),
    ordered = TRUE,
    comment = "",
    modified = "2025-06-07 07:59:46.292804"),

  ptdtrace__rac1p = list(
    CPS = list(
      groups = c(1, 2, 3, 4, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6),
      levels = c("White Only", "Black Only", "American Indian, Alaskan Native Only", "Asian Only", "Hawaiian/Pacific Islander Only", "White-Black", "White-AI", "White-Asian", "White-HP", "Black-AI", "Black-Asian", "AI-Asian", "AI-HP", "Asian-HP", "W-B-AI", "W-B-A", "W-AI-A", "W-AI-HP", "W-A-HP", "Other 3 Race Combinations"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 2, 3, 3, 3, 4, 5, 6, 6),
      levels = c("White alone", "Black or African American alone", "American Indian alone", "Alaska Native alone", "American Indian and Alaska Native tribes specified; or American Indian or Alaska Native, not specified and no other races", "Asian alone", "Native Hawaiian and Other Pacific Islander alone", "Some Other Race alone", "Two or More Races"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2025-06-07 08:00:38.883673")
)
