list(

  age_r__agep = list(
    FAPS = list(
      groups = 1,
      levels = "Min: 0, Median: 47.5, Mean: 38, Max: 85",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 38, Mean: 39.1, Max: 96",
      breaks = "",
      adj = "",
      agg = logical(0)
    ),
    ordered = "",
    comment = "",
    modified = "2025-06-02 08:37:08.835716"),

  anyvehicle__veh = list(
    FAPS = list(
      groups = 1:2,
      levels = c("No", "Yes"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 2, 2, 2, 2, 2, 2),
      levels = c("No vehicles", "1 vehicle", "2 vehicles", "3 vehicles", "4 vehicles", "5 vehicles", "6 or more vehicles"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2023-07-07 16:02:02"),

  educcat__schl = list(
    FAPS = list(
      groups = 1:6,
      levels = c("10th grade or less", "11th or 12th grade, no diploma", "H.S. diploma, GED or equivalent", "Some college or associate's degree", "Bachelor's degree", "Master's degree and above"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3, 3, 4, 4, 4, 5, 6, 6, 6),
      levels = c("Less than 3 years old", "No schooling completed", "Nursery school, preschool", "Kindergarten", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8", "Grade 9", "Grade 10", "Grade 11", "12th grade - no diploma", "Regular high school diploma", "GED or alternative credential", "Some college, but less than 1 year", "1 or more years of college credit, no degree", "Associate's degree", "Bachelor's degree", "Master's degree", "Professional degree beyond a bachelor's degree", "Doctorate degree"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2025-06-02 08:38:52.475918"),

  educcat_r__schl = list(
    FAPS = list(
      groups = c(1, 2, 4, 3, 5, 6),
      levels = c("10th grade or less", "11th or 12th grade, no diploma", "Bachelor's degree", "H.S. diploma, GED or equivalent", "Master's degree and above", "Some college or associate's degree"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 4, 5, 5, 6),
      levels = c("No schooling completed", "Nursery school, preschool", "Kindergarten", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8", "Grade 9", "Grade 10", "Grade 11", "12th grade - no diploma", "Regular high school diploma", "GED or alternative credential", "Some college, but less than 1 year", "1 or more years of college credit, no degree", "Associate's degree", "Bachelor's degree", "Master's degree", "Professional degree beyond a bachelor's degree", "Doctorate degree"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = TRUE,
    comment = "",
    modified = "2023-06-23 14:20:56"),

  employment_r__esr = list(
    FAPS = list(
      groups = c(3, 3, 2, 3, 1),
      levels = c("Looking for work", "Not working at a job or business", "With a job or business but not at work", "Worked, but looking for a job", "Working at a job or business"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(3, 1, 2, 3, 1, 2, 3),
      levels = c("Less than 16 years old", "Civilian employed, at work", "Civilian employed, with a job but not at work", "Unemployed", "Armed forces, at work", "Armed forces, with a job but not at work", "Not in labor force"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2025-06-02 12:04:26.040305"),

  expelectric_r__elep = list(
    FAPS = list(
      groups = 1,
      levels = "Min: -998, Median: 100, Mean: 95, Max: 468",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 120, Mean: 140.7, Max: 650",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2023-06-19 16:03:17"),

  expheatfuel_r__gasp = list(
    FAPS = list(
      groups = 1,
      levels = "Min: -998, Median: 0, Mean: 10, Max: 350",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 10, Mean: 42.25, Max: 630",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2023-06-19 16:03:34"),

  exprentmrtg_r__grntp = list(
    FAPS = list(
      groups = 1,
      levels = "Min: -998, Median: 600, Mean: 617, Max: 3100",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 419, Max: 4910",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2023-06-19 16:02:44"),

  famsize__npf = list(
    FAPS = list(
      groups = 1,
      levels = "Min: 1, Median: 2, Mean: 2.29, Max: 14",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 2, Mean: 1.975, Max: 20",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2023-06-19 15:58:48"),

  hispanic_r__hisp = list(
    FAPS = list(
      groups = 2:1,
      levels = c("Not Hispanic", "Hispanic"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
      levels = c("Not Spanish / Hispanic / Latino", "Mexican", "Puerto Rican", "Cuban", "Dominican", "Costa Rican", "Guatemalan", "Honduran", "Nicaraguan", "Panamanian", "Salvadoran", "Other Central American", "Argentinean", "Bolivian", "Chilean", "Colombian", "Ecuadorian", "Paraguayan", "Peruvian", "Uruguayan", "Venezuelan", "Other South American", "Spaniard", "All Other Spanish / Hispanic / Latino"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2023-06-24 10:15:09"),

  incfamreported_r__fincp = list(
    FAPS = list(
      groups = 1,
      levels = "Min: 0, Median: 38800, Mean: 52300, Max: 280700",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: -15350, Median: 41400, Mean: 70500, Max: 2940000",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2023-07-04 13:19:09"),

  inchhreported_r__hincp = list(
    FAPS = list(
      groups = 1,
      levels = "Min: 0, Median: 43700, Mean: 55300, Max: 291000",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: -15350, Median: 65700, Mean: 92400, Max: 2940000",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2023-07-04 13:18:40"),

  marital_r__mar = list(
    FAPS = list(
      groups = c(3, 1, 5, 4, 2),
      levels = c("Divorced", "Married", "Never married", "Separated", "Widowed"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:5,
      levels = c("Married", "Widowed", "Divorced", "Separated", "Never married or under 15 years old"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2023-06-23 14:26:26"),

  racecat_r__rac1p = list(
    FAPS = list(
      groups = 1:6,
      levels = c("White", "Black", "American Indian or Alaska Native", "Asian or Native Hawaiian or Other Pacific Islander", "Other race", "Multiple race"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 2, 3, 3, 3, 4, 4, 5, 6),
      levels = c("White alone", "Black or African American alone", "American Indian alone", "Alaska Native alone", "American Indian and Alaska Native tribes specified; or American Indian or Alaska Native, not specified and no other races", "Asian alone", "Native Hawaiian and Other Pacific Islander alone", "Some Other Race alone", "Two or More Races"),
      breaks = "",
      adj = "",
      agg = logical(0)
    ),
    ordered = TRUE,
    comment = "",
    modified = "2025-06-02 11:27:30.145237"),

  racecat_r_r__rac1p = list(
    FAPS = list(
      groups = 1:6,
      levels = c("American Indian or Alaska Native", "Asian or Native Hawaiian or Other Pacific Islander", "Black", "Multiple race", "Other race", "White"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(6, 3, 1, 1, 1, 2, 2, 5, 4),
      levels = c("White alone", "Black or African American alone", "American Indian alone", "Alaska Native alone", "American Indian and Alaska Native tribes specified; or American Indian or Alaska Native, not specified and no other races", "Asian alone", "Native Hawaiian and Other Pacific Islander alone", "Some Other Race alone", "Two or More Races"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2023-06-23 14:18:15"),

  resunitsize__np = list(
    FAPS = list(
      groups = 1,
      levels = "Min: 1, Median: 2, Mean: 2.44, Max: 14",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 1, Median: 2, Mean: 2.47, Max: 20",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2023-06-19 15:58:14"),

  sex_r__sex = list(
    FAPS = list(
      groups = 1:2,
      levels = c("Female", "Male"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 2:1,
      levels = c("Male", "Female"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2023-06-23 14:16:26"),

  snapnowhh__fs = list(
    FAPS = list(
      groups = 1:2,
      levels = c("No", "Yes"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 2:1,
      levels = c("Yes", "No"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2023-06-19 16:04:53"),

  uscitizen_r__cit = list(
    FAPS = list(
      groups = c(1, 2, 1),
      levels = c("No", "Yes", "Not in the US"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(2, 2, 2, 2, 1),
      levels = c("Born in the U.S.", "Born in Puerto Rico, Guam, the U.S. Virgin Islands, or the Northern Marianas", "Born abroad of American parent(s)", "U.S. citizen by naturalization", "Not a citizen of the U.S."),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2023-06-24 10:57:07"),

  vehiclenum__veh = list(
    FAPS = list(
      groups = c(2, 3, 4, 5, 1),
      levels = c("1", "2", "3", "4 or more", "0"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 2, 3, 4, 5, 5, 5),
      levels = c("No vehicles", "1 vehicle", "2 vehicles", "3 vehicles", "4 vehicles", "5 vehicles", "6 or more vehicles"),
      breaks = "",
      adj = "",
      agg = logical(0)
    ),
    ordered = TRUE,
    comment = "",
    modified = "2023-06-19 18:41:55"),

  workcommutetime_r_r__jwmnp = list(
    FAPS = list(
      groups = 1,
      levels = "Min: 0, Median: 2, Mean: 9.68, Max: 120",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 12.44, Max: 200",
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = "",
    comment = "",
    modified = "2025-06-02 11:19:46.848811")
)
