list(

  borninus__cit = list(
    NHTS = list(
      groups = 1:2,
      levels = c("Yes", "No"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 1, 2, 2, 2),
      levels = c("Born in the U.S.", "Born in Puerto Rico, Guam, the U.S. Virgin Islands, or the Northern Marianas", "Born abroad of American parent(s)", "U.S. citizen by naturalization", "Not a citizen of the U.S."),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2025-05-19 15:04:13.471299"),

  educ__schl = list(
    NHTS = list(
      groups = 1:6,
      levels = c("No education", "Less than a high school graduate", "High school graduate or GED", "Some college or associates degree", "Bachelor's degree", "Graduate degree or professional degree"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 4, 4, 4, 5, 6, 6, 6),
      levels = c("Less than 3 years old", "No schooling completed", "Nursery school, preschool", "Kindergarten", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8", "Grade 9", "Grade 10", "Grade 11", "12th grade - no diploma", "Regular high school diploma", "GED or alternative credential", "Some college, but less than 1 year", "1 or more years of college credit, no degree", "Associate's degree", "Bachelor's degree", "Master's degree", "Professional degree beyond a bachelor's degree", "Doctorate degree"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2025-05-19 15:04:13.471462"),

  hh_hisp__hisp = list(
    NHTS = list(
      groups = c(2, 1, 2),
      levels = c("Don't Know", "Yes", "No"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
      levels = c("Not Spanish / Hispanic / Latino", "Mexican", "Puerto Rican", "Cuban", "Dominican", "Costa Rican", "Guatemalan", "Honduran", "Nicaraguan", "Panamanian", "Salvadoran", "Other Central American", "Argentinean", "Bolivian", "Chilean", "Colombian", "Ecuadorian", "Paraguayan", "Peruvian", "Uruguayan", "Venezuelan", "Other South American", "Spaniard", "All Other Spanish / Hispanic / Latino"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2025-05-19 15:04:13.47153"),

  hh_race__rac1p = list(
    NHTS = list(
      groups = 1:7,
      levels = c("White", "Black or African American", "Asian", "American Indian or Alaska Native", "Native Hawaiian or other Pacific Islander", "Multiple responses selected", "Some other race"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 2, 4, 4, 4, 3, 5, 7, 6),
      levels = c("White alone", "Black or African American alone", "American Indian alone", "Alaska Native alone", "American Indian and Alaska Native tribes specified; or American Indian or Alaska Native, not specified and no other races", "Asian alone", "Native Hawaiian and Other Pacific Islander alone", "Some Other Race alone", "Two or More Races"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2025-05-19 15:04:13.471581"),

  hhfaminc__hincp = list(
    NHTS = list(
      groups = 1:11,
      levels = c("Less than $10,000", "$10,000 to $14,999", "$15,000 to $24,999", "$25,000 to $34,999", "$35,000 to $49,999", "$50,000 to $74,999", "$75,000 to $99,999", "$100,000 to $124,999", "$125,000 to $149,999", "$150,000 to $199,999", "$200,000 or more"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:11,
      levels = c("Less than 10000", "[10000 to 15000)", "[15000 to 25000)", "[25000 to 35000)", "[35000 to 50000)", "[50000 to 75000)", "[75000 to 1e+05)", "[1e+05 to 125000)", "[125000 to 150000)", "[150000 to 2e+05)", "2e+05 or more"),
      breaks = c(10000, 15000, 25000, 35000, 50000, 75000, 1e+05, 125000, 150000, 2e+05),
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2025-05-19 18:25:45.968504"),

  hhsize__np = list(
    NHTS = list(
      groups = 1,
      levels = "Min: 1, Median: 2, Mean: 2.454, Max: 13",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 1, Median: 2, Mean: 2.47, Max: 20",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2025-05-19 15:04:13.471624"),

  hhvehcnt__veh = list(
    NHTS = list(
      groups = 1:7,
      levels = c("Less than 1", "[1 to 2)", "[2 to 3)", "[3 to 4)", "[4 to 5)", "[5 to 6)", "6 or more"),
      breaks = c(1, 2, 3, 4, 5, 6),
      adj = ""),
    ACS = list(
      groups = 1:7,
      levels = c("No vehicles", "1 vehicle", "2 vehicles", "3 vehicles", "4 vehicles", "5 vehicles", "6 or more vehicles"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2025-05-19 18:26:36.218549"),

  homeown__ten = list(
    NHTS = list(
      groups = 1:3,
      levels = c("Own", "Rent", "Some other arrangement"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 1, 2, 3),
      levels = c("Owned with mortgage or loan (include home equity loans)", "Owned free and clear", "Rented", "Occupied without payment of rent"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2025-05-19 15:04:13.471687"),

  numadlt__agep = list(
    NHTS = list(
      groups = 1,
      levels = "Min: 1, Median: 2, Mean: 1.893, Max: 10",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 0:1,
      levels = c("Less than 18", "18 or more"),
      breaks = 18,
      adj = "",
      agg = "sum"),
    ordered = "",
    comment = "",
    modified = "2025-05-19 18:27:15.690781"),

  occat__occp = list(
    NHTS = list(
      groups = 1:6,
      levels = c("No job category", "Sales or service", "Clerical or administrative support", "Manufacturing, construction, maintenance, or farming", "Professional, managerial, or technical", "Something else"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 6, 6, 6, 6, 6, 2, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1),
      levels = c("Less than 16 years old / Not-in-labor-force who last worked more than 5 years ago or never worked", "MGR-Chief Executives And Legislators", "MGR-General And Operations Managers", "MGR-Advertising And Promotions Managers", "MGR-Marketing Managers", "MGR-Sales Managers", "MGR-Public Relations And Fundraising Managers", "MGR-Administrative Services Managers", "MGR-Facilities Managers", "MGR-Computer And Information Systems Managers", "MGR-Financial Managers", "MGR-Compensation And Benefits Managers", "MGR-Human Resources Managers", "MGR-Training And Development Managers", "MGR-Industrial Production Managers", "MGR-Purchasing Managers", "MGR-Transportation, Storage, And Distribution Managers", "MGR-Farmers, Ranchers, And Other Agricultural Managers", "MGR-Construction Managers", "MGR-Education And Childcare Administrators", "MGR-Architectural And Engineering Managers", "MGR-Food Service Managers", "MGR-Entertainment and Recreation Managers", "MGR-Lodging Managers", "MGR-Medical And Health Services Managers", "MGR-Natural Sciences Managers", "MGR-Property, Real Estate, And Community Association Managers", "MGR-Social And Community Service Managers", "MGR-Emergency Management Directors", "MGR-Other Managers", "BUS-Agents And Business Managers Of Artists, Performers, And Athletes", "BUS-Buyers And Purchasing Agents, Farm Products", "BUS-Wholesale And Retail Buyers, Except Farm Products", "BUS-Purchasing Agents, Except Wholesale, Retail, And Farm Products", "BUS-Claims Adjusters, Appraisers, Examiners, And Investigators", "BUS-Compliance Officers", "BUS-Cost Estimators", "BUS-Human Resources Workers", "BUS-Compensation, Benefits, And Job Analysis Specialists", "BUS-Training And Development Specialists", "BUS-Logisticians", "BUS-Project Management Specialists", "BUS-Management Analysts", "BUS-Meeting, Convention, And Event Planners", "BUS-Fundraisers", "BUS-Market Research Analysts And Marketing Specialists", "BUS-Business Operations Specialists, All Other", "FIN-Accountants And Auditors", "FIN-Property Appraisers and Assessors", "FIN-Budget Analysts", "FIN-Credit Analysts", "FIN-Financial And Investment Analysts", "FIN-Personal Financial Advisors", "FIN-Insurance Underwriters", "FIN-Financial Examiners", "FIN-Credit Counselors And Loan Officers", "FIN-Tax Examiners And Collectors, And Revenue Agents", "FIN-Tax Preparers", "FIN-Other Financial Specialists", "CMM-Computer And Information Research Scientists", "CMM-Computer Systems Analysts", "CMM-Information Security Analysts", "CMM-Computer Programmers", "CMM-Software Developers", "CMM-Software Quality Assurance Analysts and Testers", "CMM-Web Developers", "CMM-Web And Digital Interface Designers", "CMM-Computer Support Specialists", "CMM-Database Administrators and Architects", "CMM-Network And Computer Systems Administrators", "CMM-Computer Network Architects", "CMM-Computer Occupations, All Other", "CMM-Actuaries", "CMM-Operations Research Analysts", "CMM-Other Mathematical Science Occupations", "ENG-Architects, Except Landscape And Naval", "ENG-Landscape Architects", "ENG-Surveyors, Cartographers, And Photogrammetrists", "ENG-Aerospace Engineers", "ENG-Biomedical And Agricultural Engineers", "ENG-Chemical Engineers", "ENG-Civil Engineers", "ENG-Computer Hardware Engineers", "ENG-Electrical And Electronics Engineers", "ENG-Environmental Engineers", "ENG-Industrial Engineers, Including Health And Safety", "ENG-Marine Engineers And Naval Architects", "ENG-Materials Engineers", "ENG-Mechanical Engineers", "ENG-Petroleum, Mining And Geological Engineers, Including Mining Safety Engineers", "ENG-Other Engineers", "ENG-Architectural And Civil Drafters", "ENG-Other Drafters", "ENG-Electrical And Electronic Engineering Technologists and Technicians", "Other Engineering Technologists And Technicians, Except Drafters", "ENG-Surveying And Mapping Technicians", "SCI-Agricultural And Food Scientists", "SCI-Biological Scientists", "SCI-Conservation Scientists And Foresters", "SCI-Other Life Scientists", "SCI-Astronomers And Physicists", "SCI-Atmospheric And Space Scientists", "SCI-Chemists And Materials Scientists", "SCI-Environmental Scientists And Specialists, Including Health", "SCI-Geoscientists And Hydrologists, Except Geographers", "SCI-Physical Scientists, All Other", "SCI-Economists", "SCI-Clinical And Counseling Psychologists", "SCI-School Psychologists", "SCI-Other Psychologists", "SCI-Urban And Regional Planners", "SCI-Other Social Scientists", "SCI-Agricultural And Food Science Technicians", "SCI-Biological Technicians", "SCI-Chemical Technicians", "SCI-Environmental Science and Geoscience Technicians, And Nuclear Technicians", "SCI-Other Life, Physical, And Social Science Technicians", "SCI-Occupational Health And Safety Specialists and Technicians", "CMS-Substance Abuse And Behavioral Disorder Counselors", "CMS-Educational, Guidance, And Career Counselors And Advisors", "CMS-Marriage And Family Therapists", "CMS-Mental Health Counselors", "CMS-Rehabilitation Counselors", "CMS-Counselors, All Other", "CMS-Child, Family, And School Social Workers", "CMS-Healthcare Social Workers", "CMS-Mental Health And Substance Abuse Social Workers", "CMS-Social Workers, All Other", "CMS-Probation Officers And Correctional Treatment Specialists", "CMS-Social And Human Service Assistants", "CMS-Other Community and Social Service Specialists", "CMS-Clergy", "CMS-Directors, Religious Activities And Education", "CMS-Religious Workers, All Other", "LGL-Lawyers, And Judges, Magistrates, And Other Judicial Workers", "LGL-Judicial Law Clerks", "LGL-Paralegals And Legal Assistants", "LGL-Title Examiners, Abstractors, and Searchers", "LGL-Legal Support Workers, All Other", "EDU-Postsecondary Teachers", "EDU-Preschool And Kindergarten Teachers", "EDU-Elementary And Middle School Teachers", "EDU-Secondary School Teachers", "EDU-Special Education Teachers", "EDU-Tutors", "EDU-Other Teachers and Instructors", "EDU-Archivists, Curators, And Museum Technicians", "EDU-Librarians And Media Collections Specialists", "EDU-Library Technicians", "EDU-Teaching Assistants", "EDU-Other Educational Instruction and Library Workers", "ENT-Artists And Related Workers", "ENT-Commercial And Industrial Designers", "ENT-Fashion Designers", "ENT-Floral Designers", "ENT-Graphic Designers", "ENT-Interior Designers", "ENT-Merchandise Displayers And Windows Trimmers", "ENT-Other Designers", "ENT-Actors", "ENT-Producers And Directors", "ENT-Athletes and Sports Competitors", "ENT-Coaches and Scouts", "ENT-Umpires, Referees, And Other Sports Officials", "ENT-Dancers And Choreographers", "ENT-Music Directors and Composers", "ENT-Musicians and Singers", "ENT-Disc Jockeys, Except Radio", "ENT-Entertainers And Performers, Sports and Related Workers, All Other", "ENT-Broadcast Announcers And Radio Disc Jockeys", "ENT-News Analysts, Reporters And Correspondents", "ENT-Public Relations Specialists", "ENT-Editors", "ENT-Technical Writers", "ENT-Writers And Authors", "ENT-Interpreters and Translators", "ENT-Court Reporters and Simultaneous Captioners", "ENT-Media And Communication Workers, All Other", "ENT-Other Media And Communication Equipment Workers", "ENT-Photographers", "ENT-Television, Video, And Motion Picture Camera Operators And Editors", "MED-Chiropractors", "MED-Dentists", "MED-Dietitians And Nutritionists", "MED-Optometrists", "MED-Pharmacists", "MED-Physicians", "MED-Surgeons", "MED-Physician Assistants", "MED-Podiatrists", "MED-Audiologists", "MED-Occupational Therapists", "MED-Physical Therapists", "MED-Radiation Therapists", "MED-Recreational Therapists", "MED-Respiratory Therapists", "MED-Speech-Language Pathologists", "MED-Other Therapists", "MED-Veterinarians", "MED-Registered Nurses", "MED-Nurse Anesthetists", "MED-Nurse Practitioners, And Nurse Midwives", "MED-Acupuncturists", "MED-Healthcare Diagnosing Or Treating Practitioners, All Other", "MED-Clinical Laboratory Technologists And Technicians", "MED-Dental Hygienists", "MED-Cardiovascular Technologists and Technicians", "MED-Diagnostic Medical Sonographers", "MED-Radiologic Technologists And Technicians", "MED-Magnetic Resonance Imaging Technologists", "MED-Nuclear Medicine Technologists and Medical Dosimetrists", "MED-Emergency Medical Technicians", "MED-Paramedics", "MED-Pharmacy Technicians", "MED-Psychiatric Technicians", "MED-Surgical Technologists", "MED-Veterinary Technologists and Technicians", "MED-Dietetic Technicians And Ophthalmic Medical Technicians", "MED-Licensed Practical And Licensed Vocational Nurses", "MED-Medical Records Specialists", "MED-Opticians, Dispensing", "MED-Miscellaneous Health Technologists and Technicians", "MED-Other Healthcare Practitioners and Technical Occupations", "HLS-Home Health Aides", "HLS-Personal Care Aides", "HLS-Nursing Assistants", "HLS-Orderlies and Psychiatric Aides", "HLS-Occupational Therapy Assistants And Aides", "HLS-Physical Therapist Assistants And Aides", "HLS-Massage Therapists", "HLS-Dental Assistants", "HLS-Medical Assistants", "HLS-Medical Transcriptionists", "HLS-Pharmacy Aides", "HLS-Veterinary Assistants And Laboratory Animal Caretakers", "HLS-Phlebotomists", "HLS-Other Healthcare Support Workers", "PRT-First-Line Supervisors Of Correctional Officers", "PRT-First-Line Supervisors Of Police And Detectives", "PRT-First-Line Supervisors Of Fire Fighting And Prevention Workers", "PRT-First-Line Supervisors of Security And Protective Service Workers, All Other", "PRT-Firefighters", "PRT-Fire Inspectors", "PRT-Bailiffs", "PRT-Correctional Officers and Jailers", "PRT-Detectives And Criminal Investigators", "PRT-Fish And Game Wardens And Parking Enforcement Officers", "PRT-Police Officers", "PRT-Animal Control Workers", "PRT-Private Detectives And Investigators", "PRT-Security Guards And Gaming Surveillance Officers", "PRT-Crossing Guards And Flaggers", "PRT-Transportation Security Screeners", "PRT-School Bus Monitors", "PRT-Other Protective Service Workers", "EAT-Chefs And Head Cooks", "EAT-First-Line Supervisors Of Food Preparation And Serving Workers", "EAT-Cooks", "EAT-Food Preparation Workers", "EAT-Bartenders", "EAT-Fast Food And Counter Workers", "EAT-Waiters And Waitresses", "EAT-Food Servers, Nonrestaurant", "EAT-Dining Room And Cafeteria Attendants And Bartender Helpers", "EAT-Dishwashers", "EAT-Hosts And Hostesses, Restaurant, Lounge, And Coffee Shop", "EAT-Food Preparation and Serving Related Workers, All Other", "CLN-First-Line Supervisors Of Housekeeping And Janitorial Workers", "CLN-First-Line Supervisors Of Landscaping, Lawn Service, And Groundskeeping Workers", "CLN-Janitors And Building Cleaners", "CLN-Maids And Housekeeping Cleaners", "CLN-Pest Control Workers", "CLN-Landscaping And Groundskeeping Workers", "CLN-Tree Trimmers and Pruners", "CLN-Other Grounds Maintenance Workers", "PRS-Supervisors Of Personal Care And Service Workers", "PRS-Animal Trainers", "PRS-Animal Caretakers", "PRS-Gambling Services Workers", "PRS-Ushers, Lobby Attendants, And Ticket Takers", "PRS-Other Entertainment Attendants And Related Workers", "PRS-Embalmers, Crematory Operators, And Funeral Attendants", "PRS-Morticians, Undertakers, And Funeral Arrangers", "PRS-Barbers", "PRS-Hairdressers, Hairstylists, And Cosmetologists", "PRS-Manicurists And Pedicurists", "PRS-Skincare Specialists", "PRS-Other Personal Appearance Workers", "PRS-Baggage Porters, Bellhops, And Concierges", "PRS-Tour And Travel Guides", "PRS-Childcare Workers", "PRS-Exercise Trainers And Group Fitness Instructors", "PRS-Recreation Workers", "PRS-Residential Advisors", "PRS-Personal Care and Service Workers, All Other", "SAL-First-Line Supervisors Of Retail Sales Workers", "SAL-First-Line Supervisors Of Non-Retail Sales Workers", "SAL-Cashiers", "SAL-Counter And Rental Clerks", "SAL-Parts Salespersons", "SAL-Retail Salespersons", "SAL-Advertising Sales Agents", "SAL-Insurance Sales Agents", "SAL-Securities, Commodities, And Financial Services Sales Agents", "SAL-Travel Agents", "SAL-Sales Representatives Of Services, Except Advertising, Insurance, Financial Services, And Travel", "SAL-Sales Representatives, Wholesale And Manufacturing", "SAL-Models, Demonstrators, And Product Promoters", "SAL-Real Estate Brokers And Sales Agents", "SAL-Sales Engineers", "SAL-Telemarketers", "SAL-Door-To-Door Sales Workers, News And Street Vendors, And Related Workers", "SAL-Sales And Related Workers, All Other", "OFF-First-Line Supervisors Of Office And Administrative Support Workers", "OFF-Switchboard Operators, Including Answering Service", "OFF-Telephone Operators", "OFF-Communications Equipment Operators, All Other", "OFF-Bill And Account Collectors", "OFF-Billing And Posting Clerks", "OFF-Bookkeeping, Accounting, And Auditing Clerks", "OFF-Payroll And Timekeeping Clerks", "OFF-Procurement Clerks", "OFF-Tellers", "OFF-Other Financial Clerks", "OFF-Court, Municipal, And License Clerks", "OFF-Credit Authorizers, Checkers, And Clerks", "OFF-Customer Service Representatives", "OFF-Eligibility Interviewers, Government Programs", "OFF-File Clerks", "OFF-Hotel, Motel, And Resort Desk Clerks", "OFF-Interviewers, Except Eligibility And Loan", "OFF-Library Assistants, Clerical", "OFF-Loan Interviewers And Clerks", "OFF-New Accounts Clerks", "OFF-Correspondence Clerks And Order Clerks", "OFF-Human Resources Assistants, Except Payroll And Timekeeping", "OFF-Receptionists And Information Clerks", "OFF-Reservation And Transportation Ticket Agents And Travel Clerks", "OFF-Other Information And Records Clerks", "OFF-Cargo And Freight Agents", "OFF-Couriers And Messengers", "OFF-Public Safety Telecommunicators", "OFF-Dispatchers, Except Police, Fire, And Ambulance", "OFF-Meter Readers, Utilities", "OFF-Postal Service Clerks", "OFF-Postal Service Mail Carriers", "OFF-Postal Service Mail Sorters, Processors, And Processing Machine Operators", "OFF-Production, Planning, And Expediting Clerks", "OFF-Shipping, Receiving, And Inventory Clerks", "OFF-Weighers, Measurers, Checkers, And Samplers, Recordkeeping", "OFF-Executive Secretaries And Executive Administrative Assistants", "OFF-Legal Secretaries and Administrative Assistants", "OFF-Medical Secretaries and Administrative Assistants", "OFF-Secretaries And Administrative Assistants, Except Legal, Medial, And Executive", "OFF-Data Entry Keyers", "OFF-Word Processors And Typists", "OFF-Insurance Claims And Policy Processing Clerks", "OFF-Mail Clerks And Mail Machine Operators, Except Postal Service", "OFF-Office Clerks, General", "OFF-Office Machine Operators, Except Computer", "OFF-Proofreaders And Copy Markers", "OFF-Statistical Assistants", "OFF-Other Office And Administrative Support Workers", "FFF-First-Line Supervisors Of Farming, Fishing, And Forestry Workers", "FFF-Agricultural Inspectors", "FFF-Graders And Sorters, Agricultural Products", "FFF-Other Agricultural Workers", "FFF-Fishing And Hunting Workers", "FFF-Forest And Conservation Workers", "FFF-Logging Workers", "CON-First-Line Supervisors Of Construction Trades And Extraction Workers", "CON-Boilermakers", "CON-Brickmasons, Blockmasons, Stonemasons, And Reinforcing Iron And Rebar Workers", "CON-Carpenters", "CON-Carpet, Floor, And Tile Installers And Finishers", "CON-Cement Masons, Concrete Finishers, And Terrazzo Workers", "CON-Construction Laborers", "CON-Construction Equipment Operators", "CON-Drywall Installers, Ceiling Tile Installers, And Tapers", "CON-Electricians", "CON-Glaziers", "CON-Insulation Workers", "CON-Painters and Paperhangers", "CON-Pipelayers", "CON-Plumbers, Pipefitters, And Steamfitters", "CON-Plasterers And Stucco Masons", "CON-Roofers", "CON-Sheet Metal Workers", "CON-Structural Iron And Steel Workers", "CON-Solar Photovoltaic Installers", "CON-Helpers, Construction Trades", "CON-Construction And Building Inspectors", "CON-Elevator Installers And Repairers", "CON-Fence Erectors", "CON-Hazardous Materials Removal Workers", "CON-Highway Maintenance Workers", "CON-Rail-Track Laying And Maintenance Equipment Operators", "CON-Other Construction And Related Workers", "EXT-Derrick, Rotary Drill, And Service Unit Operators, And Roustabouts, Oil, Gas, And Mining", "EXT-Surface Mining Machine Operators And Earth Drillers", "EXT-Explosives Workers, Ordnance Handling Experts, and Blasters", "EXT-Underground Mining Machine Operators", "EXT-Other Extraction Workers", "RPR-First-Line Supervisors Of Mechanics, Installers, And Repairers", "RPR-Computer, Automated Teller, And Office Machine Repairers", "RPR-Radio And Telecommunications Equipment Installers And Repairers", "RPR-Avionics Technicians", "RPR-Electric Motor, Power Tool, And Related Repairers", "RPR-Other Electrical And Electronic Equipment Mechanics, Installers, And Repairers.", "RPR-Electronic Home Entertainment Equipment Installers And Repairers", "RPR-Security And Fire Alarm Systems Installers", "RPR-Aircraft Mechanics And Service Technicians", "RPR-Automotive Body And Related Repairers", "RPR-Automotive Glass Installers And Repairers", "RPR-Automotive Service Technicians And Mechanics", "RPR-Bus And Truck Mechanics And Diesel Engine Specialists", "RPR-Heavy Vehicle And Mobile Equipment Service Technicians And Mechanics", "RPR-Small Engine Mechanics", "RPR-Miscellaneous Vehicle And Mobile Equipment Mechanics, Installers, And Repairers", "RPR-Control And Valve Installers And Repairers", "RPR-Heating, Air Conditioning, And Refrigeration Mechanics And Installers", "RPR-Home Appliance Repairers", "RPR-Industrial And Refractory Machinery Mechanics", "RPR-Maintenance And Repair Workers, General", "RPR-Maintenance Workers, Machinery", "RPR-Millwrights", "RPR-Electrical Power-Line Installers And Repairers", "RPR-Telecommunications Line Installers And Repairers", "RPR-Precision Instrument And Equipment Repairers", "RPR-Coin, Vending, And Amusement Machine Servicers And Repairers", "RPR-Locksmiths And Safe Repairers", "RPR-Riggers", "RPR-Helpers--Installation, Maintenance, And Repair Workers", "RPR-Other Installation, Maintenance, And Repair Workers", "PRD-First-Line Supervisors Of Production And Operating Workers", "PRD-Electrical, Electronics, And Electromechanical Assemblers", "PRD-Engine And Other Machine Assemblers", "PRD-Structural Metal Fabricators And Fitters", "PRD-Other Assemblers And Fabricators", "PRD-Bakers", "PRD-Butchers And Other Meat, Poultry, And Fish Processing Workers", "PRD-Food And Tobacco Roasting, Baking, And Drying Machine Operators And Tenders", "PRD-Food Batchmakers", "PRD-Food Cooking Machine Operators And Tenders", "PRD-Food Processing Workers, All Other", "PRD-Computer Numerically Controlled Tool Operators And Programmers", "PRD-Forming Machine Setters, Operators, And Tenders, Metal And Plastic", "PRD-Cutting, Punching, And Press Machine Setters, Operators, And Tenders, Metal And Plastic", "Grinding, Lapping, Polishing, And Buffing Machine Tool", "PRD-Other Machine Tool Setters, Operators, And Tenders, Metal and Plastic", "PRD-Machinists", "PRD-Metal Furnace Operators, Tenders, Pourers, And Casters", "PRD-Model Makers, Patternmakers, And Molding Machine Setters, Metal And Plastic", "PRD-Tool And Die Makers", "PRD-Welding, Soldering, And Brazing Workers", "PRD-Other Metal Workers And Plastic Workers", "PRD-Prepress Technicians And Workers", "PRD-Printing Press Operators", "PRD-Print Binding And Finishing Workers", "PRD-Laundry And Dry-Cleaning Workers", "PRD-Pressers, Textile, Garment, And Related Materials", "PRD-Sewing Machine Operators", "PRD-Shoe And Leather Workers", "PRD-Tailors, Dressmakers, And Sewers", "PRD-Textile Machine Setters, Operators, And Tenders", "PRD-Upholsterers", "PRD-Other Textile, Apparel, And Furnishings Workers", "PRD-Cabinetmakers And Bench Carpenters", "PRD-Furniture Finishers", "PRD-Sawing Machine Setters, Operators, And Tenders, Wood", "PRD-Woodworking Machine Setters, Operators, And Tenders, Except Sawing", "PRD-Other Woodworkers", "PRD-Power Plant Operators, Distributors, And Dispatchers", "PRD-Stationary Engineers And Boiler Operators", "PRD-Water And Wastewater Treatment Plant And System Operators", "PRD-Miscellaneous Plant And System Operators", "PRD-Chemical Processing Machine Setters, Operators, And Tenders", "PRD-Crushing, Grinding, Polishing, Mixing, And Blending Workers", "PRD-Cutting Workers", "PRD-Extruding, Forming, Pressing, And Compacting Machine Setters, Operators, And Tenders", "PRD-Furnace, Kiln, Oven, Drier, And Kettle Operators And Tenders", "PRD-Inspectors, Testers, Sorters, Samplers, And Weighers", "PRD-Jewelers And Precious Stone And Metal Workers", "PRD-Dental And Ophthalmic Laboratory Technicians And Medical Appliance Technicians", "PRD-Packaging And Filling Machine Operators And Tenders", "PRD-Painting Workers", "PRD-Photographic Process Workers And Processing Machine Operators", "PRD-Adhesive Bonding Machine Operators And Tenders", "PRD-Etchers And Engravers", "PRD-Molders, Shapers, And Casters, Except Metal And Plastic", "PRD-Paper Goods Machine Setters, Operators, And Tenders", "PRD-Tire Builders", "PRD-Helpers-Production Workers", "PRD-Miscellaneous Production Workers, Including Equipment Operators And Tenders", "TRN-Supervisors Of Transportation And Material Moving Workers", "TRN-Aircraft Pilots And Flight Engineers", "TRN-Air Traffic Controllers And Airfield Operations Specialists", "TRN-Flight Attendants", "TRN-Ambulance Drivers And Attendants, Except Emergency Medical Technicians", "TRN-Bus Drivers, School", "TRN-Bus Drivers, Transit And Intercity", "TRN-Driver / Sales Workers And Truck Drivers", "TRN-Shuttle Drivers And Chauffeurs", "TRN-Taxi Drivers", "TRN-Motor Vehicle Operators, All Other", "TRN-Locomotive Engineers And Operators", "TRN-Railroad Conductors And Yardmasters", "TRN-Other Rail Transportation Workers", "TRN-Sailors And Marine Oilers, And Ship Engineers", "TRN-Ship And Boat Captains And Operators", "TRN-Parking Lot Attendants", "TRN-Transportation Service Attendants", "TRN-Transportation Inspectors", "TRN-Passenger Attendants", "TRN-Other Transportation Workers", "TRN-Crane And Tower Operators", "TRN-Conveyor, Dredge, And Hoist and Winch Operators", "TRN-Industrial Truck And Tractor Operators", "TRN-Cleaners Of Vehicles And Equipment", "TRN-Laborers And Freight, Stock, And Material Movers, Hand", "TRN-Machine Feeders And Offbearers", "TRN-Packers And Packagers, Hand", "TRN-Stockers And Order Fillers", "TRN-Pumping Station Operators", "TRN-Refuse And Recyclable Material Collectors", "TRN-Other Material Moving Workers", "MIL-Military Officer Special And Tactical Operations Leaders", "MIL-First-Line Enlisted Military Supervisors", "MIL-Military Enlisted Tactical Operations And Air / Weapons Specialists And Crew Members", "MIL-Military, Rank Not Specified", "Unemployed And Last Worked 5 Years Ago Or Earlier Or Never Worked"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2025-05-19 18:35:10.063332"),

  pc__laptop = list(
    NHTS = list(
      groups = c(2, 1, 1, 1, 1),
      levels = c("Never", "A few times a year", "A few times a month", "A few times a week", "Daily"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:2,
      levels = c("Yes", "No"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2025-05-19 15:04:13.47173"),

  r_age__agep = list(
    NHTS = list(
      groups = 1,
      levels = "Min: 5, Median: 40, Mean: 40.7, Max: 92",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 38, Mean: 39.1, Max: 96",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2025-05-19 15:04:13.471777"),

  r_hisp__hisp = list(
    NHTS = list(
      groups = 1:2,
      levels = c("Yes, Hispanic or Latino", "No, Not Hispanic or Latino"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
      levels = c("Not Spanish / Hispanic / Latino", "Mexican", "Puerto Rican", "Cuban", "Dominican", "Costa Rican", "Guatemalan", "Honduran", "Nicaraguan", "Panamanian", "Salvadoran", "Other Central American", "Argentinean", "Bolivian", "Chilean", "Colombian", "Ecuadorian", "Paraguayan", "Peruvian", "Uruguayan", "Venezuelan", "Other South American", "Spaniard", "All Other Spanish / Hispanic / Latino"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2025-05-19 15:04:13.471828"),

  r_race__rac1p = list(
    NHTS = list(
      groups = c(1, 2, 3, 4, 5, 6, 7, 1),
      levels = c("Refused", "White", "Black or African American", "Asian", "American Indian or Alaska Native", "Native Hawaiian or other Pacific Islander", "Multiple responses selected", "Some other race"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(2, 3, 5, 5, 5, 4, 6, 1, 7),
      levels = c("White alone", "Black or African American alone", "American Indian alone", "Alaska Native alone", "American Indian and Alaska Native tribes specified; or American Indian or Alaska Native, not specified and no other races", "Asian alone", "Native Hawaiian and Other Pacific Islander alone", "Some Other Race alone", "Two or More Races"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2025-05-19 15:04:13.471877"),

  r_sex__sex = list(
    NHTS = list(
      groups = 1:2,
      levels = c("Male", "Female"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:2,
      levels = c("Male", "Female"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2025-05-19 15:04:13.471941"),

  tab__tablet = list(
    NHTS = list(
      groups = c(1, 2, 2, 2, 2),
      levels = c("Never", "A few times a year", "A few times a month", "A few times a week", "Daily"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 2:1,
      levels = c("Yes", "No"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2025-05-19 15:04:13.472002"),

  timetowk__jwmnp = list(
    NHTS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 12.17, Max: 600",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 12.44, Max: 200",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2025-05-19 15:04:13.472059"),

  webuse17__access = list(
    NHTS = list(
      groups = c(2, 1, 1, 1, 1),
      levels = c("Never", "A few times a year", "A few times a month", "A few times a week", "Daily"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 1, 2),
      levels = c("Yes, by paying a cell phone company or Internet service provider", "Yes, without paying a cell phone company or Internet service provider", "No access to the Internet at this house, apartment, or mobile home"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2025-05-19 15:04:13.472118"),

  wkftpt__wkhp = list(
    NHTS = list(
      groups = 1:3,
      levels = c("Not full time or part-time worker", "Part-time", "Full-time"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:3,
      levels = c("Less than 1", "[1 to 15)", "15 or more"),
      breaks = c(1, 15),
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2025-05-19 18:37:17.038455"),

  worker__wkl = list(
    NHTS = list(
      groups = 1:2,
      levels = c("No", "Yes"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 2, 2, 1),
      levels = c("Less than 16 years old", "Within the past 12 months", "1-5 years ago", "Over 5 years ago or never worked"),
      breaks = 1,
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2025-05-19 15:04:13.472159"),

  wrkcount__wif = list(
    NHTS = list(
      groups = 1:4,
      levels = c("Less than 1", "[1 to 2)", "[2 to 3)", "3 or more"),
      breaks = c(1, 2, 3),
      adj = ""),
    ACS = list(
      groups = c(1, 1, 2, 3, 4),
      levels = c("Non-family household", "No workers", "1 worker", "2 workers", "3 or more workers in family"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2025-05-19 18:36:13.507566"),

  wrktrans__jwtr = list(
    NHTS = list(
      groups = c(1, 9, 8, 2, 2, 2, 2, 10, 7, 10, 3, 3, 3, 3, 3, 4, 4, 6, 6, 10, 5, 10),
      levels = c("No mode to work", "Walk", "Bicycle", "Car", "SUV", "Van", "Pickup truck", "Golf cart / Segway", "Motorcycle / Moped", "RV (motor home, ATV, snowmobile)", "School bus", "Public or commuter bus", "Paratransit / Dial-a-ride", "Private / Charter / Tour / Shuttle bus", "City-to-city bus (Greyhound, Megabus)", "Amtrak / Commuter rail", "Subway / Elevated / Light rail / Street car", "Taxi / Limo (including Uber / Lyft)", "Rental car (including Zipcar / Car2Go)", "Airplane", "Boat / Ferry / Water taxi", "Something Else"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 2, 3, 4, 4, 4, 5, 6, 7, 8, 9, 1, 10),
      levels = c("Not a worker--not in the labor force, including persons under 16 years; unemployed; employed, with a job but not at work; Armed Forces, with a job but not at work", "Car, truck, or van", "Bus or trolley bus", "Streetcar or trolley car (carro publico in Puerto Rico)", "Subway or elevated", "Railroad", "Ferryboat", "Taxicab", "Motorcycle", "Bicycle", "Walked", "Worked at home", "Other method"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2025-05-19 15:04:13.472195"),

  youngchild__nrc = list(
    NHTS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 0.1546, Max: 5",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 0.552, Max: 14",
      breaks = "",
      adj = "ifelse(fparc == (\"With related children under 5 years only\"),nrc,0)",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2025-05-19 15:04:13.472251")
)
