list(

  bedrooms__bdsp = list(
    RECS = list(
      groups = 1,
      levels = "Min: 0, Median: 3, Mean: 2.76, Max: 6",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 3, Mean: 2.744, Max: 8",
      breaks = "",
      adj = "",
      agg = logical(0)
    ),
    ordered = "",
    comment = "",
    modified = "2024-09-16 12:02:27.369288"),

  cooktop__stov = list(
    RECS = list(
      groups = 1:2,
      levels = c("Less than 1", "1 or more"),
      breaks = 1,
      adj = "cooktop + range"),
    ACS = list(
      groups = 2:1,
      levels = c("Yes", "No"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2024-09-16 12:03:13.725298"),

  education__schl = list(
    RECS = list(
      groups = 1:5,
      levels = c("Less than high school diploma or GED", "High school diploma or GED", "Some college or Associate's degree", "Bachelor's degree", "Master's, Professional, or Doctoral degree"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3, 3, 3, 4, 5, 5, 5),
      levels = c("Less than 3 years old", "No schooling completed", "Nursery school, preschool", "Kindergarten", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8", "Grade 9", "Grade 10", "Grade 11", "12th grade - no diploma", "Regular high school diploma", "GED or alternative credential", "Some college, but less than 1 year", "1 or more years of college credit, no degree", "Associate's degree", "Bachelor's degree", "Master's degree", "Professional degree beyond a bachelor's degree", "Doctorate degree"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = TRUE,
    comment = "",
    modified = "2024-09-16 12:02:27.369796"),

  elpay__elefp = list(
    RECS = list(
      groups = c(2, 1, 1, 3),
      levels = c("Household is responsible for paying for all electricity used in this home", "All electricity used in this home is included in the rent or condo fee", "Some is paid by the household, some is included in the rent or condo fee", "Other"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 3, 2),
      levels = c("Included in rent or in condo fee", "No charge or electricity not used", "Valid monthly electricity cost in ELEP"),
      breaks = "",
      adj = "",
      agg = logical(0)
    ),
    ordered = FALSE,
    comment = "",
    modified = "2024-09-16 12:02:27.369912"),

  employhh__wkhp = list(
    RECS = list(
      groups = c(3, 2, 1, 1),
      levels = c("Employed full-time", "Employed part-time", "Retired", "Not employed"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:3,
      levels = c("Less than 1", "[1 to 20)", "20 or more"),
      breaks = c(1, 20),
      adj = "",
      agg = "reference"),
    ordered = TRUE,
    comment = "",
    modified = "2024-09-16 12:04:09.552589"),

  fopay__fulfp = list(
    RECS = list(
      groups = c(3, 1, 1, 2, 2),
      levels = c("Household is responsible for paying for all fuel oil used in this home", "All fuel oil used in this home is included in the rent or condo fee", "Some is paid by the household, some is included in the rent or condo fee", "Other", "Do not use fuel oil"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:3,
      levels = c("Included in rent or in condo fee", "No charge or fuel other than gas or electricity not used", "Valid annual fuel cost in FULP"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2024-09-16 12:02:27.370003"),

  fuelheat__hfl = list(
    RECS = list(
      groups = 1:7,
      levels = c("No space heating", "Electricity", "Natural gas from underground pipes", "Propane (bottled gas)", "Fuel oil", "Wood or pellets", "Other"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(3, 4, 2, 5, 7, 6, 7, 7, 1),
      levels = c("Utility gas", "Bottled, tank, or LP gas", "Electricity", "Fuel oil, kerosene, etc.", "Coal or coke", "Wood", "Solar energy", "Other fuel", "No fuel used"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2024-09-16 12:02:27.370085"),

  hhage__agep = list(
    RECS = list(
      groups = 1,
      levels = "Min: 18, Median: 55, Mean: 54.2, Max: 90",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 37, Mean: 38.3, Max: 97",
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = "",
    comment = "",
    modified = "2024-09-16 12:02:27.370171"),

  hhsex__sex = list(
    RECS = list(
      groups = 1:2,
      levels = c("Female", "Male"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 2:1,
      levels = c("Male", "Female"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2024-09-16 12:02:27.370264"),

  householder_race__rac1p = list(
    RECS = list(
      groups = 1:6,
      levels = c("White Alone", "Black or African/American Alone", "American Indian or Alaska Native Alone", "Asian Alone", "Native Hawaiian or Other Pacific Islander Alone", "2 or More Races Selected"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 2, 3, 3, 3, 4, 5, 6, 6),
      levels = c("White alone", "Black or African American alone", "American Indian alone", "Alaska Native alone", "American Indian and Alaska Native tribes specified; or American Indian or Alaska Native, not specified and no other races", "Asian alone", "Native Hawaiian and Other Pacific Islander alone", "Some Other Race alone", "Two or More Races"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2024-09-16 12:02:27.370365"),

  internet__access = list(
    RECS = list(
      groups = 1:3,
      levels = c("Yes, by paying a cell phone company or Internet service provider", "Yes, without paying a cell phone company or Internet service provider", "No access to the Internet"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:3,
      levels = c("Yes, by paying a cell phone company or Internet service provider", "Yes, without paying a cell phone company or Internet service provider", "No access to the Internet at this house, apartment, or mobile home"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2024-09-16 12:04:31.167036"),

  kownrent__ten = list(
    RECS = list(
      groups = 1:3,
      levels = c("Own", "Rent", "Occupy without payment of rent"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 1, 2, 3),
      levels = c("Owned with mortgage or loan (include home equity loans)", "Owned free and clear", "Rented", "Occupied without payment of rent"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2024-09-16 12:02:27.370449"),

  moneypy__hincp = list(
    RECS = list(
      groups = 1:16,
      levels = c("Less than $5,000", "$5,000 - $7,499", "$7,500 - $9,999", "$10,000 - $12,499", "$12,500 - $14,999", "$15,000 - $19,999", "$20,000 - $24,999", "$25,000 - $29,999", "$30,000 - $34,999", "$35,000 - $39,999", "$40,000 - $49,999", "$50,000 - $59,999", "$60,000 - $74,999", "$75,000 - $99,999", "$100,000 - $149,999", "$150,000 or more"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:16,
      levels = c("Less than 5000", "[5000 to 7500)", "[7500 to 10000)", "[10000 to 12500)", "[12500 to 15000)", "[15000 to 20000)", "[20000 to 25000)", "[25000 to 30000)", "[30000 to 35000)", "[35000 to 40000)", "[40000 to 50000)", "[50000 to 60000)", "[60000 to 75000)", "[75000 to 1e+05)", "[1e+05 to 150000)", "150000 or more"),
      breaks = c(5000, 7500, 10000, 12500, 15000, 20000, 25000, 30000, 35000, 40000, 50000, 60000, 75000, 1e+05, 150000),
      adj = "hincp * 1.056",
      agg = ""),
    ordered = TRUE,
    comment = "Adjusted hincp for inflation to 2020 dollars from 2017 prior to binning.",
    modified = "2024-09-16 12:05:47.957659"),

  ngpay__gasfp = list(
    RECS = list(
      groups = c(1, 2, 2, 3, 3),
      levels = c("Household is responsible for paying for all natural gas used in this home", "All natural gas used in this home is included in the rent or condo fee", "Some is paid by the household, some is included in the rent or condo fee", "Other", "Do not use natural gas"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 2, 3, 1),
      levels = c("Included in electricity payment", "Included in rent or in condo fee", "No charge or gas not used", "Valid monthly gas cost in GASP"),
      breaks = "",
      adj = "",
      agg = logical(0)
    ),
    ordered = FALSE,
    comment = "",
    modified = "2024-09-16 12:02:27.370519"),

  nhsldmem__np = list(
    RECS = list(
      groups = 1,
      levels = "Min: 1, Median: 2, Mean: 2.44, Max: 7",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 1, Median: 2, Mean: 2.49, Max: 20",
      breaks = "",
      adj = "",
      agg = logical(0)
    ),
    ordered = "",
    comment = "",
    modified = "2024-09-16 12:02:27.370594"),

  numadult1__agep = list(
    RECS = list(
      groups = 1,
      levels = "Min: 0, Median: 1, Mean: 1.41, Max: 7",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 37, Mean: 38.3, Max: 97",
      breaks = "",
      adj = "agep >= 18 & agep <=64",
      agg = "sum"),
    ordered = "",
    comment = "",
    modified = "2024-09-16 12:02:27.37068"),

  numadult2__agep = list(
    RECS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 0.527, Max: 6",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 37, Mean: 38.3, Max: 97",
      breaks = "",
      adj = "agep >= 65",
      agg = "sum"),
    ordered = "",
    comment = "",
    modified = "2024-09-16 12:02:27.370755"),

  numchild__agep = list(
    RECS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 0.504, Max: 4",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 37, Mean: 38.3, Max: 97",
      breaks = "",
      adj = "agep <= 17",
      agg = "sum"),
    ordered = "",
    comment = "",
    modified = "2024-09-16 12:02:27.370828"),

  numfrig__refr = list(
    RECS = list(
      groups = 1:2,
      levels = c("Less than 1", "1 or more"),
      breaks = 1,
      adj = ""),
    ACS = list(
      groups = 2:1,
      levels = c("Yes", "No"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2024-09-16 12:06:07.225523"),

  numlaptop__laptop = list(
    RECS = list(
      groups = 1:2,
      levels = c("Less than 1", "1 or more"),
      breaks = 1,
      adj = "numlaptop + desktop"),
    ACS = list(
      groups = 2:1,
      levels = c("Yes", "No"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "Added numlaptop and desktop together to match ACS laptop variable definition.",
    modified = "2024-09-16 12:06:42.579794"),

  sdescent__hisp = list(
    RECS = list(
      groups = 1:2,
      levels = c("Yes", "No"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
      levels = c("Not Spanish / Hispanic / Latino", "Mexican", "Puerto Rican", "Cuban", "Dominican", "Costa Rican", "Guatemalan", "Honduran", "Nicaraguan", "Panamanian", "Salvadoran", "Other Central American", "Argentinean", "Bolivian", "Chilean", "Colombian", "Ecuadorian", "Paraguayan", "Peruvian", "Uruguayan", "Venezuelan", "Other South American", "Spaniard", "All Other Spanish / Hispanic / Latino"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2024-09-16 12:02:27.370897"),

  totrooms__rmsp = list(
    RECS = list(
      groups = 1,
      levels = "Min: 1, Median: 6, Mean: 6.25, Max: 15",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 1, Median: 6, Mean: 5.87, Max: 19",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2024-09-16 12:02:27.370975"),

  typehuq__bld = list(
    RECS = list(
      groups = 1:5,
      levels = c("Mobile home", "Single-family house detached from any other house", "Single-family house attached to one or more other houses (for example: duplex, row house, or townhome)", "Apartment in a building with 2 to 4 units", "Apartment in a building with 5 or more units"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 2, 3, 4, 4, 5, 5, 5, 5, 1),
      levels = c("Mobile home or trailer", "One-family house detached", "One-family house attached", "2 Apartments", "3-4 Apartments", "5-9 Apartments", "10-19 Apartments", "20-49 Apartments", "50 or more apartments", "Boat, RV, van, etc."),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2024-09-16 12:02:27.371081"),

  yearmaderange__ybl = list(
    RECS = list(
      groups = 1:9,
      levels = c("Before 1950", "1950 to 1959", "1960 to 1969", "1970 to 1979", "1980 to 1989", "1990 to 1999", "2000 to 2009", "2010 to 2015", "2016 to 2020"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 1, 2, 3, 4, 5, 6, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 9, 9),
      levels = c("1939 or earlier", "1940 to 1949", "1950 to 1959", "1960 to 1969", "1970 to 1979", "1980 to 1989", "1990 to 1999", "2000 to 2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017"),
      breaks = "",
      adj = "",
      agg = logical(0)
    ),
    ordered = TRUE,
    comment = "",
    modified = "2024-09-16 12:15:23.481301")
)
