list(

  bedrooms__bdsp = list(
    RECS = list(
      groups = 1,
      levels = "Min: 0, Median: 3, Mean: 2.833, Max: 10",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 3, Mean: 2.837, Max: 8",
      breaks = "",
      adj = ""),
    ordered = "",
    comment = "",
    modified = "2021-07-03 12:10:17"),

  desktop__laptop = list(
    RECS = list(
      groups = 1:2,
      levels = c("Less than 1", "1 or more"),
      breaks = 1,
      adj = "desktop + numlaptop"),
    ACS = list(
      groups = 2:1,
      levels = c("Yes", "No"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "Add 'desktop' and 'laptop' variables in RECS, since ACS variable refers to presence of either one.",
    modified = "2021-07-03 12:12:22"),

  education__schl = list(
    RECS = list(
      groups = 1:5,
      levels = c("Less than high school diploma or GED", "High school diploma or GED", "Some college or Associate's degree", "Bachelor's degree (for example: BA, BS)", "Master's, Professional, or Doctorate degree (for example: MA, MS, MBA, MD, JD, PhD)"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3, 3, 3, 4, 5, 5, 5),
      levels = c("No schooling completed", "Nursery school, preschool", "Kindergarten", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8", "Grade 9", "Grade 10", "Grade 11", "12th grade - no diploma", "Regular high school diploma", "GED or alternative credential", "Some college, but less than 1 year", "1 or more years of college credit, no degree", "Associate's degree", "Bachelor's degree", "Master's degree", "Professional degree beyond a bachelor's degree", "Doctorate degree"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = TRUE,
    comment = "",
    modified = "2021-07-03 12:10:17"),

  elpay__elefp = list(
    RECS = list(
      groups = c(1, 2, 3, 1),
      levels = c("All used in this home is included in the rent or condo fee", "Household is responsible for paying for all used in this home", "Paid for some other way", "Some is paid by the household, some is included in the rent or condo fee"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 3, 2),
      levels = c("Included in rent or in condo fee", "No charge or electricity not used", "Valid monthly electricity cost in ELEP"),
      breaks = "",
      adj = "",
      agg = logical(0)
    ),
    ordered = FALSE,
    comment = "",
    modified = "2022-03-12 10:36:48"),

  employhh__wkhp = list(
    RECS = list(
      groups = 1:3,
      levels = c("Employed full-time", "Employed part-time", "Not employed/retired"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 3:1,
      levels = c("Less than 1", "[1 to 20)", "20 or more"),
      breaks = c(1, 20),
      adj = "",
      agg = "reference"),
    ordered = TRUE,
    comment = "",
    modified = "2021-07-03 12:31:54"),

  fuelheat__hfl = list(
    RECS = list(
      groups = 1:7,
      levels = c("Do not use space heating", "Electricity", "Fuel oil/kerosene", "Natural gas from underground pipes", "Propane (bottled gas)", "Some other fuel", "Wood (cordwood or pellets)"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(5, 6, 2, 3, 1, 6, 6, 4, 7),
      levels = c("Bottled, tank, or LP gas", "Coal or coke", "Electricity", "Fuel oil, kerosene, etc.", "No fuel used", "Other fuel", "Solar energy", "Utility gas", "Wood"),
      breaks = "",
      adj = ""),
    ordered = FALSE,
    comment = "",
    modified = "2021-07-03 12:10:17"),

  hhage__agep = list(
    RECS = list(
      groups = 1,
      levels = "Min: 18, Median: 53, Mean: 52.3, Max: 85",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 0, Median: 43, Mean: 42.2, Max: 96",
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = "",
    comment = "",
    modified = "2021-07-03 12:10:17"),

  hhsex__sex = list(
    RECS = list(
      groups = 1:2,
      levels = c("Female", "Male"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:2,
      levels = c("Female", "Male"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2021-07-03 12:10:17"),

  householder_race__rac1p = list(
    RECS = list(
      groups = 1:6,
      levels = c("White Alone", "Black or African/American Alone", "American Indian or Alaska Native Alone", "Asian Alone", "Native Hawaiian or Other Pacific Islander Alone", "2 or More Races Selected"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 2, 3, 3, 3, 4, 5, 6, 6),
      levels = c("White alone", "Black or African American alone", "American Indian alone", "Alaska Native alone", "American Indian and Alaska Native tribes specified; or American Indian or Alaska Native, not specified and no other races", "Asian alone", "Native Hawaiian and Other Pacific Islander alone", "Some Other Race alone", "Two or More Races"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2021-07-03 12:42:46"),

  internet__access = list(
    RECS = list(
      groups = 1:2,
      levels = c("Yes", "No"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 1, 2),
      levels = c("Yes, with subscription to an Internet service", "Yes, without a subscription to an Internet service", "No Internet access at this house, apartment, or mobile home"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2021-07-03 12:18:18"),

  kownrent__ten = list(
    RECS = list(
      groups = 1:3,
      levels = c("Occupied without payment of rent", "Owned or being bought by someone in your household", "Rented"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 2, 2, 3),
      levels = c("Occupied without payment of rent", "Owned free and clear", "Owned with mortgage or loan (include home equity loans)", "Rented"),
      breaks = "",
      adj = ""),
    ordered = FALSE,
    comment = "",
    modified = "2021-07-03 12:10:17"),

  moneypy__hincp = list(
    RECS = list(
      groups = 1:8,
      levels = c("Less than $20,000", "$20,000 - $39,999", "$40,000 - $59,999", "$60,000 to $79,999", "$80,000 to $99,999", "$100,000 to $119,999", "$120,000 to $139,999", "$140,000 or more"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:8,
      levels = c("Less than 20000", "[20000 to 40000)", "[40000 to 60000)", "[60000 to 80000)", "[80000 to 1e+05)", "[1e+05 to 120000)", "[120000 to 140000)", "140000 or more"),
      breaks = c(20000, 40000, 60000, 80000, 1e+05, 120000, 140000),
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2021-07-03 12:28:17"),

  ngpay__gasfp = list(
    RECS = list(
      groups = c(1, 2, 3, 3, 1),
      levels = c("All used in this home is included in the rent or condo fee", "Household is responsible for paying for all used in this home", "No natural gas", "Paid for some other way", "Some is paid by the household, some is included in the rent or condo fee"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 2, 3, 2),
      levels = c("Included in rent or in condo fee", "Included in electricity payment", "No charge or gas not used", "Valid monthly gas cost in GASP"),
      breaks = "",
      adj = "",
      agg = logical(0)
    ),
    ordered = FALSE,
    comment = "",
    modified = "2022-03-12 10:37:28"),

  nhsldmem__np = list(
    RECS = list(
      groups = 1,
      levels = "Min: 1, Median: 2, Mean: 2.547, Max: 12",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 1, Median: 2, Mean: 2.49, Max: 20",
      breaks = "",
      adj = "",
      agg = ""),
    ordered = "",
    comment = "",
    modified = "2021-07-29 07:16:27"),

  numadult__agep = list(
    RECS = list(
      groups = 1,
      levels = "Min: 1, Median: 2, Mean: 1.953, Max: 10",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 0:1,
      levels = c("Less than 18", "18 or more"),
      breaks = 18,
      adj = "",
      agg = "sum"),
    ordered = "",
    comment = "",
    modified = "2021-07-03 12:15:43"),

  numchild__agep = list(
    RECS = list(
      groups = 1,
      levels = "Min: 0, Median: 0, Mean: 0.594, Max: 10",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1:0,
      levels = c("Less than 18", "18 or more"),
      breaks = 18,
      adj = "",
      agg = "sum"),
    ordered = "",
    comment = "",
    modified = "2021-07-03 12:39:18"),

  numfrig__refr = list(
    RECS = list(
      groups = 1:2,
      levels = c("Less than 1", "1 or more"),
      breaks = 1,
      adj = ""),
    ACS = list(
      groups = 2:1,
      levels = c("Yes", "No"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2021-07-03 12:13:12"),

  numtablet__handheld = list(
    RECS = list(
      groups = 1:2,
      levels = c("Less than 1", "1 or more"),
      breaks = 1,
      adj = ""),
    ACS = list(
      groups = 2:1,
      levels = c("Yes", "No"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2021-07-03 12:40:08"),

  occupyyrange__mv = list(
    RECS = list(
      groups = c(1, 1, 1, 1, 1, 2, 3, 4),
      levels = c("Before 1950", "1950 to 1959", "1960 to 1969", "1970 to 1979", "1980 to 1989", "1990 to 1999", "2000 to 2009", "2010 to 2015"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(4, 4, 4, 4, 3, 2, 1),
      levels = c("12 months or less", "13 to 23 months", "2 to 4 years", "5 to 9 years", "10 to 19 years", "20 to 29 years", "30 years or more"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "Precise alignment of the year ranges is not possible. Matched as best as possible.",
    modified = "2021-07-03 12:36:17"),

  sdescent__hisp = list(
    RECS = list(
      groups = 2:1,
      levels = c("No", "Yes"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
      levels = c("All Other Spanish / Hispanic / Latino", "Argentinean", "Bolivian", "Chilean", "Colombian", "Costa Rican", "Cuban", "Dominican", "Ecuadorian", "Guatemalan", "Honduran", "Mexican", "Nicaraguan", "Not Spanish / Hispanic / Latino", "Other Central American", "Other South American", "Panamanian", "Paraguayan", "Peruvian", "Puerto Rican", "Salvadoran", "Spaniard", "Uruguayan", "Venezuelan"),
      breaks = "",
      adj = "",
      agg = "reference"),
    ordered = FALSE,
    comment = "",
    modified = "2021-07-03 12:10:17"),

  stoven__stov = list(
    RECS = list(
      groups = 1:2,
      levels = c("Less than 1", "1 or more"),
      breaks = 1,
      adj = ""),
    ACS = list(
      groups = 2:1,
      levels = c("Yes", "No"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2021-07-03 12:13:36"),

  totrooms__rmsp = list(
    RECS = list(
      groups = 1,
      levels = "Min: 1, Median: 6, Mean: 6.19, Max: 19",
      breaks = "",
      adj = ""),
    ACS = list(
      groups = 1,
      levels = "Min: 1, Median: 6, Mean: 6.15, Max: 20",
      breaks = "",
      adj = ""),
    ordered = "",
    comment = "",
    modified = "2021-07-03 12:10:17"),

  typehuq__bld = list(
    RECS = list(
      groups = 1:5,
      levels = c("Apartment in a building with 2 to 4 units", "Apartment in a building with 5 or more units", "Mobile home", "Single-family attached house", "Single-family detached house"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(3, 5, 4, 1, 1, 2, 2, 2, 2, 3),
      levels = c("Mobile home or trailer", "One-family house detached", "One-family house attached", "2 Apartments", "3-4 Apartments", "5-9 Apartments", "10-19 Apartments", "20-49 Apartments", "50 or more apartments", "Boat, RV, van, etc."),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = FALSE,
    comment = "",
    modified = "2021-07-03 12:10:17"),

  yearmaderange__ybl = list(
    RECS = list(
      groups = 1:8,
      levels = c("Before 1950", "1950 to 1959", "1960 to 1969", "1970 to 1979", "1980 to 1989", "1990 to 1999", "2000 to 2009", "2010 to 2015"),
      breaks = "",
      adj = ""),
    ACS = list(
      groups = c(1, 1, 2, 3, 4, 5, 6, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8),
      levels = c("1939 or earlier", "1940 to 1949", "1950 to 1959", "1960 to 1969", "1970 to 1979", "1980 to 1989", "1990 to 1999", "2000 to 2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015"),
      breaks = "",
      adj = "",
      agg = ""),
    ordered = TRUE,
    comment = "",
    modified = "2021-07-03 12:29:29")
)
