#' Generate Output Files Resulting from Fusion
#'
#' @description
#' Executes the model training, internal validation, and prediction steps required
#' to fuse donor survey variables onto American Community Survey (ACS) recipient microdata.
#' Uses preprocessed input files generated by \code{\link{fusionInput}}.
#'
#' @param donor Character. Donor survey identifier and vintage (e.g., `"RECS_2015"` or `"RECS_2020"`).
#'   Must match the underscore-separated folder naming convention generated by `fusionInput()`.
#' @param respondent Character. Desired respondent level of microdata: either `"household"` (or `"H"`) or `"person"` (or `"P"`).
#' @param acs_year Integer. Year of the ACS microdata to be used as recipient (e.g., `2015`).
#' @param fusion_vars Character vector or list. Variable names in the donor microdata to be fused to the ACS recipient microdata. Any `fusion_vars` used as predictors in the training data are automatically ignored.
#' @param M Integer. Desired number of fusion implicates (simulated output datasets). Defaults to `1`.
#' @param test_mode Logical. If `TRUE` (default), output files are written to a `/fusion_` directory rather than `/fusion`, and fast, light hyperparameter settings are passed to \code{\link[fusionModel]{train}}.
#' @param input_version Character. Version timestamp string (formatted as `"YYYY-MM-DD"`) of the desired input folder in `/input`. Defaults to `"latest"`.
#' @param output_version Character. Version timestamp string (formatted as `"YYYY-MM-DD"`) to assign to the `/output` folder. Defaults to `"today"`.
#' @param fsn Character. Optional file path to an existing trained model archive (`.fsn`) created by a previous call to \code{fusionOutput()}. If provided, the function attempts to bypass feature preparation (`prepXY`) or complete model training (`train`).
#' @param rlocation Data frame. Optional data frame containing actual/disclosed respondent locations to override imputed locations in donor data.
#' @param note Character. Optional user-supplied note to be recorded in the output log file for future reference.
#' @param validation Logical. If `TRUE` (default), fuses implicates back onto original donor training data to generate internal validation files (`valid.fsd`).
#' @param ncores Integer. Number of physical CPU cores used for parallel computation and file I/O threading. Defaults to `1`.
#' @param margin Numeric. Integer or numeric margin passed to \code{\link[fusionModel]{fuse}} controlling memory-saving chunk boundaries during prediction. Defaults to `4`.
#' @param ... Additional arguments passed to underlying modeling functions.
#'   For \code{fusionOutput}, arguments are passed to \code{\link[fusionModel]{train}}.
#'   For \code{fusionOutput_multiyear}, arguments are passed to \code{fusionOutput}
#'   (and subsequently to \code{train}).
#'
#' @details
#' `fusionOutput()` ties together the machine-learning pipeline provided by the \code{fusionModel} package.
#' Given a valid setup created by \code{\link{fusionInput}}, `fusionOutput()` manages the complete modeling lifecycle:
#'
#' 1. **Data Assembly**: Loads harmonized donor predictors, donor target variables (`fusion_vars`), and spatial predictor variables matching the donor's survey vintage and geographic boundaries (PUMA 2010 vs. PUMA 2020).
#' 2. **Predictor Selection (`prepXY`)**: Evaluates feature correlations and screening thresholds via \code{\link[fusionModel]{prepXY}} (or reuses structure from an existing `.fsn` file if `fsn` is specified).
#' 3. **Model Training (`train`)**: Trains gradient boosted decision trees via LightGBM using sensible default hyperparameters tuned for production or rapid test runs.
#' 4. **Validation Fusing (`fuse`)**: If `validation = TRUE`, fuses the target variables back onto the training data to create a validation dataset (`.fsd`) for downstream evaluation.
#' 5. **Recipient Prediction (`fuse`)**: Loads ACS microdata, merges spatial context predictors, and fuses `M` implicates of the target variables onto the recipient microdata.
#'
#' @section Directory Structure & Outputs:
#' Output files are stored in structured paths based on execution mode:
#' \itemize{
#'   \item **Test Mode:** \code{fusion_/[DONOR_NAME]/[DONOR_VINTAGE]/[ACS_YEAR]/output/[DATE]/}
#'   \item **Production Mode:** \code{fusion/[DONOR_NAME]/[DONOR_VINTAGE]/[ACS_YEAR]/output/[DATE]/}
#' }
#' Each run creates the following files in the target directory:
#' \enumerate{
#'   \item \code{[DONOR]_[ACS_YEAR]_[TYPE]_prep.rds}: Saved feature selection object from
#'         \code{\link[fusionModel]{prepXY}} mapping target variables to screened predictors.
#'   \item \code{[DONOR]_[ACS_YEAR]_[TYPE]_model.fsn}: Trained LightGBM model archive generated by
#'         \code{\link[fusionModel]{train}} containing tree structures and feature metadata.
#'   \item \code{[DONOR]_[ACS_YEAR]_[TYPE]_valid.fsd}: *(Optional, created if \code{validation = TRUE})*
#'         Fused implicates simulated back onto original donor observations for possible internal validation by the user.
#'   \item \code{[DONOR]_[ACS_YEAR]_[TYPE]_fused.fsd}: Fused microdata containing \code{M} simulated
#'         target implicates mapped onto the recipient ACS microdata.
#'   \item \code{[DONOR]_[ACS_YEAR]_[TYPE]_outputlog.txt}: Execution log containing system details,
#'         arguments, CPU/memory stats, and timing summaries.
#'   \item \code{[DONOR]_[ACS_YEAR]_[TYPE]_outputlog0.txt}: *(Optional, created when reusing an existing \code{.fsn})*
#'         Retained console output from the original model training run.
#' }
#'
#' @return Invisibly returns a character string containing the absolute file path to the
#' generated `/output` directory.
#'
#' @seealso
#' \itemize{
#'   \item \code{\link{fusionInput}} for creating the harmonized input datasets required by this function.
#'   \item \code{\link[fusionModel]{train}} for the underlying LightGBM model training workflow.
#'   \item \code{\link[fusionModel]{fuse}} for the spatial and implicate prediction engine used during validation and final recipient fusion.
#' }
#'
#' @examples
#' \dontrun{
#' # Typical workflow following fusionInput()
#' out_path <- fusionOutput(
#'   donor = "RECS_2015",
#'   respondent = "household",
#'   acs_year = 2015,
#'   fusion_vars = c("btung", "btuel", "cooltype"),
#'   M = 1,
#'   test_mode = TRUE
#' )
#'
#' # View generated output files
#' list.files(out_path)
#' }
#'
#' @export

#-----

# TESTING
# library(tidyverse)
# library(data.table)
# source("R/utils.R")
#
# donor = "RECS_2024"
# acs_year = 2019
# respondent = "household"
# fusion_vars <- c("adqinsul",  "totsqft_en")
# M <- 1
# note = NULL
# test_mode = FALSE
# validation = TRUE
# ncores = getOption("fusionData.cores")
# margin = 2

#-----

# Dummy respondent location data for testing
# geo <- fst::read_fst("geo-processed/concordance/geo_concordance.fst")
# donor = fst::read_fst("fusion_/RECS/2020/2015/RECS_2020_2015_H_donor.fst")
# temp <- geo %>%
#    select(state, county10, tract10) %>%
#    distinct() %>%
#    slice_sample(n = nrow(donor))
# rlocation <- data.frame(hid = donor$hid)
# rlocation <- cbind(rlocation, temp)
# rlocation <- slice_sample(rlocation, prop = 0.95)

# fusionOutput(donor = "RECS_2020",
#              respondent = "H",
#              acs_year = 2015,
#              fusion_vars = c("aircond", "scaleb", "btuel"),
#              fsn = "fusion_/RECS/2020/2015/RECS_2020_2015_H_model.fsn",
#              rlocation = rlocation)

#-----

fusionOutput <- function(donor,
                         respondent,
                         acs_year,
                         fusion_vars,
                         M = 1,
                         test_mode = TRUE,
                         input_version = "latest",
                         output_version = "today",
                         fsn = NULL,
                         rlocation = NULL,
                         note = NULL,
                         validation = TRUE,
                         ncores = getOption("fusionData.cores"),
                         margin = 4,
                         ...) {

  tstart <- Sys.time()

  # Check validity of the working directory path
  # Checks if "/fusionData" is part of the path, as this is required
  b <- strsplit(full.path(getwd()), .Platform$file.sep, fixed = TRUE)[[1]]
  i <- which(b == "fusionData")
  if (length(i) == 0) stop("'/fusionData' is not part of the working directory path; this is required.")
  dir <- paste(b[1:i], collapse = .Platform$file.sep)

  # Get path to the fusion file INPUT directory
  donor <- strsplit(donor, "_", fixed = TRUE)[[1]]
  dir.in <- file.path(dir, ifelse(test_mode, "fusion_", "fusion"), donor[1], donor[2], acs_year, "input")
  if (!dir.exists(dir.in)) stop("Could not locate input directory:\n", dir.in)

  # Check input arguments
  respondent <- substring(toupper(respondent), 1, 1)
  stopifnot({
    respondent %in% c("H", "P")
    is.character(fusion_vars) | is.list(fusion_vars)
    M > 0 & M %% 1 == 0
    input_version == "latest" | !is.na(as.Date(input_version, format = "%Y-%m-%d"))
    output_version == "today" | !is.na(as.Date(output_version, format = "%Y-%m-%d"))
    is.null(fsn) | is.character(fsn)
    is.null(rlocation) | is.data.frame(rlocation)
    is.null(note) | is.character(note)
    is.logical(test_mode)
    is.logical(validation)
    ncores > 0 & ncores %% 1 == 0
    is.numeric(margin)
  })

  # Create 'dir.in' to include either the latest or user-specified input version
  vlist <- list.dirs(dir.in, full.names = FALSE, recursive = FALSE)
  if (input_version == "latest") {
    input_version <- last(vlist)
    if (length(input_version) == 0) stop("No valid latest version in input directory:\n", dir.in)
  } else {
    if (!input_version %in% vlist) stop("Requested 'input_version' could not be located in:\n", dir.in)
  }
  dir.in <- file.path(dir.in, input_version)

  # Check validity of the 'fusion_vars' argument
  fvars <- unlist(fusion_vars)
  if (anyDuplicated(fvars)) stop("Duplicate fusion variables provided (must be unique)")

  # Check validity of the 'fsn' argument, if present
  if (is.character(fsn)) {
    stopifnot({
      endsWith(fsn, ".fsn")
      file.exists(fsn)
    })
    fsn <- full.path(fsn)
  }

  # Set number of cores for 'fst' and 'data.table' packages to use
  data.table::setDTthreads(ncores)
  fst::threads_fst(ncores)

  # Create log file
  log.temp <- tempfile()
  log.txt <- file(log.temp, open = "wt")
  sink(log.txt, type = "output", split = TRUE)

  #-----

  # Report initial messages to console and log
  tstamp <- as.POSIXct(Sys.time(), tz = "UTC")  # Time in UTC time zone
  cli::cat_line("==================================================================")
  cli::cat_line("fusionOutput() RUN INFORMATION")
  cli::cat_line("==================================================================")
  cli::cat_line("Timestamp: ", format(tstamp, usetz = TRUE))
  cli::cat_line("R Version: ", R.version.string)
  cli::cat_line("Platform:  ", R.Version()$platform)
  cli::cat_line("Package:   fusionData v", as.character(utils::packageVersion("fusionData")))
  cli::cat_line("Package:   fusionModel v", as.character(utils::packageVersion("fusionModel")))
  cli::cat_line()

  # Report number of CPU cores and available memory
  gc(verbose = FALSE)
  avail_cores <- ifelse(Sys.getenv("SLURM_CPUS_PER_TASK") == "", parallel::detectCores(logical = FALSE), as.integer(Sys.getenv("SLURM_CPUS_PER_TASK")))
  cli::cat_line("Resources:")
  cli::cat_line("  - Using ", ncores, " of ", avail_cores, " available CPU cores")
  cli::cat_line("  - Detected ", signif(freeMemory() / 1e3, 3), " GB of available memory at start")
  cli::cat_line()

  # Print the original function arguments
  # Excludes 'note', if present, since it is printed separately to log, below
  cli::cat_line("Function Call:")
  print(match.call.defaults(exclude = if (is.null(note)) NULL else "note"))
  cli::cat_line()

  # Print message indicating 'test_mode' value
  cli::cat_line("Execution Mode: ", ifelse(test_mode, "TEST", "PRODUCTION"))
  cli::cat_line()

  # Report the INPUT directory
  cli::cat_line("Fusion INPUT Directory:")
  cli::cat_line("  ", dir.in)
  cli::cat_line()

  # Construct and report the OUTPUT directory
  output_version <- if (output_version == "today") as.Date(tstamp) else output_version
  dir.out <- file.path(sub("/input$", "/output", dirname(dir.in)), output_version)
  if (!dir.exists(dir.out)) dir.create(dir.out, recursive = TRUE)
  cli::cat_line("Fusion OUTPUT Directory:")
  cli::cat_line("  ", dir.out)
  cli::cat_line()

  # Write 'note' argument to log file (and console), if requested
  if (!is.null(note)) {
    cli::cat_line("User-Supplied Note:")
    cli::cat_line("  ", note)
    cli::cat_line()
  }

  #-----

  # Check for presence of training dataset
  tfile <- full.path(list.files(dir.in, pattern = paste0(respondent, "_donor\\.fst$"), full.names = TRUE))
  if (length(tfile) == 0) stop("Cannot locate 'donor.fst' file at: ", tfile)

  # Check for presence of ACS prediction dataset
  rfile <- sub("donor.fst", "recipient.fst", tfile)
  if (!file.exists(rfile)) stop("Cannot locate 'recipient.fst' file at: ", rfile)

  # Check for presence of donor processed microdata
  dfile <- full.path(list.files(path = "survey-processed", pattern = paste(c(donor, respondent, "processed.fst"), collapse = "_"), recursive = TRUE, full.names = TRUE))
  if (length(dfile) == 0) stop("Cannot locate donor processed microdata in /survey-processed")

  # Check for presence of 'geo_predictors.fst' file
  gfile <- full.path("geo-processed/geo_predictors.fst")
  if (!file.exists(gfile)) stop("Cannot locate 'geo_predictors.fst' file")

  # Update 'stub' used for output files
  stub <- file.path(dir.out, sub("donor.fst", "", basename(tfile), fixed = TRUE))

  # Log file paths
  log.path <- paste0(stub, "outputlog.txt")
  log.path0 <- paste0(stub, "outputlog0.txt") # Possible copy location when training step is skipped

  #-----

  cli::cat_line("------------------------------------------------------------------")
  cli::cat_line("STEP 1: ASSEMBLE TRAINING DATA")
  cli::cat_line("------------------------------------------------------------------")

  # Load training predictor data extracted during fusionInput()
  cli::cat_line("Loading donor harmonized predictors: ", basename(tfile))
  train.data <- fst::read_fst(tfile, as.data.table = TRUE)
  hvars <- grep("__", names(train.data), fixed = TRUE, value = TRUE)  # Harmonized predictor variables

  # Identify PUMA census standard (2010 vs 2020) stored in training dataset
  puma_col <- intersect(names(train.data), c("puma10", "puma20"))[1]
  if (!length(puma_col) == 1) stop("'train.data' must contain either 'puma10' or 'puma20'")

  #---

  # Replace imputed state/PUMA geography with disclosed locations if provided by 'rlocation' argument
  if (is.data.frame(rlocation)) {
    cli::cat_line("Updating donor imputed respondent location with disclosed location...")
    geo <- fst::read_fst("geo-processed/concordance/geo_concordance.fst")
    rlocation <- geo %>%
      select(state, any_of(puma_col), any_of(names(rlocation))) %>%
      distinct() %>%
      inner_join(rlocation) %>%
      select(hid, state, any_of(puma_col)) %>%
      filter(hid %in% as.character(train.data$hid)) %>%
      na.omit()

    # Apply disclosed locations to match training observations
    if (nrow(rlocation) > 0) {
      N0 <- nrow(train.data)
      pct <- 100 * signif(nrow(rlocation) / nrow(train.data), 3)
      cli::cat_line("  - Disclosed location provided for ", nrow(rlocation), " donor respondents (", pct, "% of households)")
    }
    train.data <- train.data %>%
      mutate_at(vars(state, any_of(puma_col)), as.character) %>%
      rows_update(rlocation, by = "hid")

    if (nrow(train.data) > N0) stop("Problem with 'rlocation'; merge led to erroneous increase in number of donor observations.")
    rm(rlocation, geo)
  }

  #---

  # Load specific donor variables targeted for fusion from processed survey files
  cli::cat_line("Loading fusion variables from: ", basename(dfile))
  idvars <- intersect(names(train.data), c('hid', 'pid'))
  dvars <- names(fst::fst(dfile))
  miss <- setdiff(fvars, dvars)  # Missing fusion variables
  if (length(miss)) {
    stop("The following fusion variables are not present in the donor microdata:\n", paste(miss, collapse = ","), "\n")
  }
  drop <- intersect(c('year', 'weight', idvars, sub("__.*$", "", hvars)), fvars)  # Variables that CANNOT be fused (i.e. universal or harmonized predictor)
  if (length(drop)) {
    fvars <- setdiff(fvars, drop)
    fusion_vars <- sapply(fusion_vars, function(x) setdiff(x, drop))  # Removes 'drop' variables from list elements (i.e. grouped variables)
    fusion_vars <- fusion_vars[lengths(fusion_vars) > 0]
    cli::cat_line("  - Ignoring disallowed harmonized 'fusion_vars': ", paste(drop, collapse = ', '))
  }
  fuse.data <- fst::read_fst(dfile, as.data.table = TRUE, columns = c(idvars, fvars)) %>%
    setkeyv(idvars)

  # Load spatial predictor attributes mapped to geographic boundaries
  cli::cat_line("Loading spatial predictors from: ", basename(gfile))

  # Record mtime and MD5 hash to guarantee provenance of spatial context features
  cli::cat_line("  - Last modified: ", format(file.info(gfile)$mtime, usetz = TRUE))
  cli::cat_line("  - MD5 checksum:  ", tools::md5sum(gfile)[[1]])

  # Determine survey vintage year (midpoint calculation for multi-year survey spans)
  svintage <- ceiling(median(eval(parse(text = sub("-", ":", donor[2])))))

  # Filter spatial contextual predictor dataset to match survey vintage and PUMA vintage (2010 vs 2020 boundaries)
  spatial.data <- fst::read_fst(gfile, as.data.table = TRUE) %>%
    filter(vintage == svintage, puma_vintage == ifelse(puma_col == "puma10", 2010, 2020)) %>%
    setnames("puma", puma_col) %>%
    setkeyv(c('state', puma_col)) %>%
    select(-vintage, -puma_vintage)

  # Merge predictors, spatial features, and fusion target variables into single training table
  cli::cat_line("Assembling full training dataset...")
  full.data <- train.data %>%
    merge(spatial.data, all.x = TRUE, sort = FALSE) %>%
    setkeyv(key(fuse.data)) %>%
    merge(fuse.data, all.x = TRUE, sort = FALSE) %>%
    select(-all_of(c(idvars, key(spatial.data)))) %>%
    select(weight, all_of(fvars), everything())

  # Remove categorical variables exceeding LightGBM max category thresholds (>255 levels)
  drop <- names(which(sapply(full.data, nlevels) > 255))
  if (length(drop)) {
    full.data <- select(full.data, -all_of(drop))
    cli::cat_line("  - Removed high-cardinality factors (>255 levels): ", paste(drop, collapse = ", "))
  }

  cli::cat_line("Training dataset assembled: ", nrow(full.data), " observations")
  cli::cat_line()
  rm(train.data, fuse.data)

  #-----

  # Evaluate existing model object (.fsn) to determine if training or prep step can be bypassed.
  # 1. If fsn target path equals the destination output path, skip.train = TRUE (bypasses prep & training).
  # 2. If fsn is provided as a pre-trained feature selection model, skip.prep = TRUE (reuses predictor ranking).
  skip.train <- skip.prep <- FALSE
  if (is.character(fsn)) {

    # Extract metadata from zip archive of existing .fsn model
    td <- tempfile()
    zip::unzip(zipfile = fsn, exdir = td)
    meta <- readRDS(file.path(td, "metadata.rds"))
    unlink(td)

    # Check if target model path matches destination model path to bypass full training
    temp <- file.path(dir.out, sub("donor.fst", "model.fsn", basename(tfile)))
    if (fsn == temp) {
      skip.train <- TRUE
      fsn.path <- fsn
    }

    if (!skip.train) {

      # Extract predictor set used in template model
      temp <- dir.in
      str_sub(temp, -21, -18) <- str_sub(dirname(fsn), -22, -19)
      fsn.donor <- file.path(temp, sub("_model.fsn", "_donor.fst", basename(fsn)))
      hvars0 <- names(fst::fst(fsn.donor))
      hvars0 <- grep("__", hvars0, fixed = TRUE, value = TRUE)

      # Extract variable importance from existing .fsn model
      vimp <- fusionModel::importance(fsn)$detailed %>%
        distinct(y, x) %>%
        filter(x %in% names(full.data))

      if (!all(fvars %in% vimp$y)) stop("Not all requested 'fusion_vars' are present in the existing 'fsn' model")

      # Force inclusion of newly added harmonized predictors not present in template model
      hvars <- grep("__", names(full.data), fixed = TRUE, value = TRUE)
      force <- setdiff(hvars, hvars0)

      # Reconstruct prep object structures based on template model feature rankings
      ylist <- lapply(meta$ylist, function(v) intersect(v, fvars))  # Restricts 'fsn' y-ordering to requested fusion variables
      ylist <- ylist[lengths(ylist) > 0]
      prep <- list(y = ylist)
      prep$x <- lapply(prep$y, function(v) {
        filter(vimp, y %in% v) %>%
          pull(x) %>%
          unique() %>%
          c(force)
      })

      xunique <- setdiff(unique(unlist(prep$x)), fvars)
      skip.prep <- TRUE

    }
  }

  #-----

  if (skip.train) {

    cli::cat_line("------------------------------------------------------------------")
    cli::cat_line("STEP 2: MODEL TRAINING (SKIPPED)")
    cli::cat_line("------------------------------------------------------------------")
    cli::cat_line("Using provided .fsn model to bypass prepXY() and train() steps:")
    cli::cat_line("  ", fsn)

    # Retain initial training log output when reusing model files
    if (!file.exists(log.path0)) file.copy(from = log.path, to = log.path0)
    cli::cat_line("See ", basename(log.path0), " for console output from original model training step.")
    cli::cat_line()

  } else {

    cli::cat_line("------------------------------------------------------------------")
    cli::cat_line("STEP 2: FEATURE PREPARATION & MODEL TRAINING")
    cli::cat_line("------------------------------------------------------------------")

    if (skip.prep) {

      cli::cat_line("Using provided .fsn model to bypass prepXY() step:")
      cli::cat_line("  ", fsn)
      cli::cat_line("Retained ", length(xunique), " of ", ncol(full.data) - length(fvars) - 1, " potential predictor variables.")
      cli::cat_line()

      # Filter full dataset down to selected predictors defined in prep structure
      full.data <- full.data %>%
        select(weight, any_of(unique(c(fvars, unlist(prep$x)))))

    } else {

      cli::cat_line("Running fusionModel::prepXY()...")

      # Screen predictors via correlation and LASSO selection
      n0 <- nrow(full.data)
      pfrac <- min(1, ifelse(test_mode, 5e3, max(20e3, n0 * 0.1)) / n0)
      prep <- fusionModel::prepXY(data = full.data,
                                  y = fusion_vars,
                                  x = setdiff(names(full.data), c(fvars, "weight")),
                                  weight = "weight",
                                  cor_thresh = 0.025,
                                  lasso_thresh = 0.99,
                                  xmax = 100,
                                  xforce = NULL,
                                  fraction = pfrac,
                                  cores = ncores)

    }

    # Save prepared predictor and target variable mappings
    xfile <- paste0(stub, "prep.rds")
    saveRDS(prep, file = xfile)
    fsize <- signif(file.size(xfile) / 1e6, 3)
    cli::cat_line("Results saved to: ", paste0(basename(xfile), " (", fsize, " MB)"))

    cli::cat_line("\nRunning fusionModel::train()...\n")

    # Remove stale original log copy if present
    if (file.exists(log.path0)) unlink(log.path0)

    # Configure gradient boosting hyperparameters for LightGBM
    hyper.params <- if (test_mode) {
      cli::cat_line("  - Hyperparameters: TEST mode settings")
      list(
        boosting = "gbdt",
        data_sample_strategy = "goss",
        num_leaves = 7,
        min_data_in_leaf = max(20, ceiling(nrow(full.data) * 0.01)),
        num_iterations = 50,
        feature_fraction = 0.5,
        learning_rate = 0.2,
        max_depth = 3,
        max_bin = 255,
        min_data_in_bin = ceiling(nrow(full.data) * 0.01),
        max_cat_threshold = 32
      )
    } else {
      cli::cat_line("  - Hyperparameters: PRODUCTION mode settings")
      hyper.params <- list(
        boosting = "gbdt",
        data_sample_strategy = "goss",
        num_leaves = 31,
        min_data_in_leaf = max(10, ceiling(nrow(full.data) * 0.001)),
        num_iterations = 2500,
        feature_fraction = 0.75,
        learning_rate = 0.1,
        max_depth = 5,
        max_bin = 255,
        min_data_in_bin = 3,
        max_cat_threshold = 32
      )
      print(hyper.params)
    }

    # Train LightGBM models via fusionModel infrastructure
    cli::cat_line("\nTraining fusion model...\n")
    fsn.path <- fusionModel::train(data = full.data,
                                   y = prep$y,
                                   x = prep$x,
                                   fsn = paste0(stub, "model.fsn"),
                                   weight = "weight",
                                   hyper = hyper.params,
                                   cores = ncores,
                                   ...)

    xfile <- paste0(stub, "model.fsn")
    fsize <- signif(file.size(xfile) / 1e6, 3)
    cli::cat_line("Results saved to: ", paste0(basename(xfile), " (", fsize, " MB)"))
    cli::cat_line()

  }

  #-----

  if (validation) {

    cli::cat_line("------------------------------------------------------------------")
    cli::cat_line("STEP 3: INTERNAL VALIDATION FUSION")
    cli::cat_line("------------------------------------------------------------------")
    cli::cat_line("Fusing onto donor microdata for internal validation...")

    # Fuse target implicates back to original training observations to evaluate performance
    validfsd <- fusionModel::fuse(data = full.data %>% select(-all_of(fvars)),
                                  fsn = fsn.path,
                                  M = M,
                                  fsd = paste0(stub, "valid.fsd"),
                                  cores = ncores,
                                  margin = margin)

    xfile <- paste0(stub, "valid.fsd")
    fsize <- signif(file.size(xfile) / 1e6, 3)
    cli::cat_line("Results saved to: ", paste0(basename(xfile), " (", fsize, " MB)"))
    cli::cat_line()

  }

  #-----

  cli::cat_line("------------------------------------------------------------------")
  cli::cat_line("STEP 4: RECIPIENT MICRODATA FUSION")
  cli::cat_line("------------------------------------------------------------------")

  # Load recipient ACS prediction features and merge spatial context variables
  cli::cat_line("Loading recipient harmonized predictors: ", basename(rfile))
  predict.data <- fst::read_fst(rfile, as.data.table = TRUE) %>%
    merge(spatial.data, all.x = TRUE, sort = FALSE) %>%
    select(any_of(c(idvars, names(full.data))))

  # Set ACS year and set data.table primary keys
  set(predict.data, j = 'year', value = as.integer(acs_year))
  setkeyv(predict.data, cols = c('year', idvars))

  # Clear memory allocations prior to prediction pass
  rm(full.data)
  gc(verbose = FALSE)

  # Generate fused target variable implicates for ACS recipient microdata
  cli::cat_line("Fusing to ACS ", acs_year, " microdata (", M, " ", ifelse(M == 1, "implicate", "implicates"), ")...")

  fusionModel::fuse(data = predict.data,
                    fsn = fsn.path,
                    M = M,
                    fsd = paste0(stub, "fused.fsd"),
                    retain = key(predict.data),  # Retain the ACS year, household ID, and possibly 'pid' in the output
                    cores = ncores,
                    margin = margin)

  xfile <- paste0(stub, "fused.fsd")
  fsize <- signif(file.size(xfile) / 1e6, 3)
  cli::cat_line("Results saved to: ", paste0(basename(xfile), " (", fsize, " MB)"))

  #-----

  # Clean up workspace allocations
  rm(predict.data, spatial.data)
  gc(verbose = FALSE)

  cli::cat_line()
  cli::cat_line("==================================================================")
  cli::cat_line("fusionOutput() IS FINISHED!")
  cli::cat_line("==================================================================")

  # Report total execution runtime
  tout <- difftime(Sys.time(), tstart)
  cli::cat_line("\nTotal processing time: ", signif(as.numeric(tout), 3), " ", attr(tout, "units"))

  # Terminate logging output redirect
  cli::cat_line("Log file saved to:\n  ", log.path)
  cli::cat_line()

  sink(type = "output")
  close(log.txt)
  invisible(file.copy(from = log.temp, to = log.path, overwrite = TRUE))

  # Return path to generated /output folder invisibly
  return(invisible(dir.out))

}

#--------------------

#' Execute Multi-Year Data Fusion Across ACS Recipient Years
#'
#' @rdname fusionOutput
#' @aliases NULL
#'
#' @description
#' `fusionOutput_multiyear()` is a convenience wrapper around `fusionOutput()` to iteratively run data fusion
#' models across sequential ACS recipient years. The function automatically passes the
#' \code{.fsn} model file generated by the prior year's run to accelerate variable selection
#' and model training for subsequent years.
#'
#' @param acs_years Numeric vector. Sequence of ACS recipient years to process
#'   (e.g., \code{2019:2023}). Must be provided in ascending numeric order.
#'
#' @export

fusionOutput_multiyear <- function(acs_years, ...) {

  # Input validation
  stopifnot(is.numeric(acs_years), length(acs_years) > 0)
  stopifnot(is.character(fusion_vars), length(fusion_vars) > 0)

  if (is.unsorted(acs_years)) {
    stop("`acs_years` must be provided in ascending numeric order (e.g., 2019:2023).", call. = FALSE)
  }

  fsn_paths <- character(length(acs_years))
  names(fsn_paths) <- as.character(acs_years)

  prev_fsn <- NULL
  dots <- list(...)

  for (i in seq_along(acs_years)) {
    current_year <- acs_years[i]
    cli::cat_rule(sprintf("Processing ACS Year: %d (%d of %d)", current_year, i, length(acs_years)))

    # Confirm previous model file exists if not on the first iteration
    if (!is.null(prev_fsn)) {
      if (!file.exists(prev_fsn)) {
        stop(sprintf("Previous .fsn model file not found for year %d: %s", current_year - 1, prev_fsn), call. = FALSE)
      }
      cli::cat_bullet(sprintf("Passing previous model: %s", prev_fsn), bullet = "info")
    } else {
      cli::cat_bullet("Initial year: No prior .fsn model passed.", bullet = "info")
    }

    # Construct a clean language call object to preserve fusionOutput's match.call/logging
    call_list <- c(
      list(
        quote(fusionData::fusionOutput),
        donor = donor,
        fusion_vars = fusion_vars,
        respondent = respondent,
        acs_year = current_year,
        fsn = prev_fsn
      ),
      dots
    )

    # Evaluate as a standard function call syntax
    dir_out <- eval(as.call(call_list))

    # Pattern includes current acs_year: donor_ACSYEAR_RESPONDENT_model.fsn
    target_pattern <- sprintf("%s_%s_%s_model\\.fsn$", donor, current_year, respondent)

    # Locate generated model file directly inside returned output directory
    if (!is.null(dir_out) && dir.exists(dir_out)) {
      candidate_files <- list.files(dir_out, pattern = target_pattern, recursive = TRUE, full.names = TRUE)

      if (length(candidate_files) > 0) {
        # Select the most recently modified .fsn file if multiple exist
        prev_fsn <- candidate_files[which.max(file.info(candidate_files)$mtime)]
        fsn_paths[as.character(current_year)] <- prev_fsn
      } else {
        warning(sprintf("Could not locate generated .fsn file matching pattern '%s' in '%s'.", target_pattern, dir_out))
        prev_fsn <- NULL
      }
    } else {
      warning(sprintf("Output directory returned by fusionOutput() does not exist or is NULL: %s", as.character(dir_out)))
      prev_fsn <- NULL
    }

    gc(verbose = FALSE)
  }

  invisible(fsn_paths)
}
