#' Create Harmonized Microdata Datasets
#'
#' @description
#' Parses a specified `.R` "harmony file" generated by the Survey Harmonization Tool
#' (\code{harmony}) to transform raw survey microdata into structured, aligned
#' datasets containing specified harmonized variables. This function serves as a
#' core internal workhorse for \code{\link{fusionInput}} during the input preparation phase.
#'
#' @param harmony.file Character. Filename of a `.R` harmony object located within the
#'   `harmony/harmonies/` repository path (e.g., `"RECS_2015__ACS_2015.R"`).
#' @param respondent Character. Desired unit of observation for output microdata;
#'   must be either `"household"` or `"person"`.
#' @param output Character. Indicates which microdata dataset(s) to process and return:
#'   `"both"` (default), `"donor"`, or `"recipient"`.
#' @param ncores Integer. Number of CPU cores allocated for parallel execution. Defaults
#'   to `getOption("fusionData.cores")`.
#'
#' @details
#' `harmonize()` executes the variable transformation and aggregation definitions recorded
#' in a harmony file against processed donor and ACS microdata (`survey-processed/*.fst`).
#'
#' Key internal processing steps include:
#' * **Microdata Loading:** Dynamically pulls matching household (`H`) and person (`P`) `.fst`
#'   files based on the harmony file specifications.
#' * **Variable Transformation & Recoding:** Evaluates custom inline expressions (`adj`),
#'   applies categorical grouping (`groups` / `levels`), or assigns numeric break intervals
#'   (`breaks`).
#' * **Cross-Level Aggregation & Rescaling:** Automatically converts person-level variables to
#'   household-level (via methods such as reference person assignment, mean, min, max) or
#'   replicates household attributes across person-level observations as required by the
#'   `respondent` level.
#' * **Geographic Attribute Retention:** Automatically extracts state and PUMA geographic
#'   identifiers for recipient ACS observations across vintages.
#'
#' @section Note:
#' This function is an unexported internal helper within `fusionData`. It is invoked automatically
#' by \code{fusionInput()} and typically does not need to be called directly by users.
#'
#' @return If `output = "both"`, a named list of two data frames corresponding to donor and
#' recipient microdata. If `output = "donor"` or `"recipient"`, a single data frame.
#' Returned data frames include structural metadata attached as custom R attributes:
#' \itemize{
#'   \item `survey`: Name of source survey.
#'   \item `identifier`: Column names defining unique keys (e.g., `hid`, `pid`).
#'   \item `employed.vars`: Raw processed variables used to construct the harmonized output.
#'   \item `geo.vars`: Geographic variable names retained for ACS recipient microdata.
#'   \item `harmonized.vars`: Full list of harmonized variable names generated.
#' }
#'
#' @examples
#' \dontrun{
#' # Harmonize household-level microdata for CEI and ACS
#' hdata <- harmonize(
#'   harmony.file = "CEI_2015-2019__ACS_2015.R",
#'   respondent = "household",
#'   output = "both"
#' )
#' }
#'
#' @keywords internal
#' @seealso \code{\link{imputeLocation}}, \code{\link{fusionInput}}
#' @noMd

#-----

# Example inputs
# harmony.file = "RECS_2015__ACS_2015.R"
# respondent = "household"
# output = "both"

#-----

harmonize <- function(harmony.file,
                      respondent,
                      output = "both",
                      ncores = getOption("fusionData.cores")) {

  # Load the structured harmonization list definition from disk
  H <- dget(file.path("harmony/harmonies", harmony.file))

  # Validate parameter inputs
  stopifnot({
    respondent %in% c("household", "person")
    output %in% c("both", "donor", "recipient")
  })

  # Logical flag indicating if output unit of observation is Household level
  HH <- toupper(substring(respondent, 1, 1)) == "H"

  # Internal helper function to split combined survey/variable string names
  splitNames <- function(x) strsplit(x, "__", fixed = TRUE)

  # Extract donor and recipient survey names from harmony file name
  survey <- unlist(splitNames(gsub(".R", "", basename(harmony.file), fixed = TRUE)))

  # Verify availability of processed donor microdata at requested respondent level
  temp <- list.files(path = "survey-processed", pattern = paste(survey[1], ifelse(HH, "H", "P"), "processed.fst", sep = "_"), recursive = TRUE)
  if (length(temp) == 0) stop("No ", respondent, "-level microdata available for ", survey[1], " survey")

  # Names of all target harmonized variables defined in the harmony specification
  hnames <- names(H)

  # Load package dictionary to identify structural respondent levels (Household vs Person)
  load("data/dictionary.rda")
  dict.vars <- paste(paste(dictionary$Survey, dictionary$Vintage, sep = "_"), dictionary$Variable)

  # Determine structural respondent level of raw donor variables
  dnames <- map_chr(splitNames(hnames), 1)
  dind <- match(paste(survey[1], dnames), dict.vars)
  dres <- dictionary$Respondent[dind]

  # Determine structural respondent level of raw recipient variables
  rnames <- map_chr(splitNames(hnames), 2)
  rind <- match(paste(survey[2], rnames), dict.vars)
  rres <- dictionary$Respondent[rind]

  # Identify recipient geographic identifiers to preserve (state and vintage-appropriate PUMA)
  rgeo <- c('state', dictionary$Variable[grep(paste(survey[2], 'puma'), dict.vars)[1]])

  # Set up loop execution to process donor and/or recipient datasets
  do.types <- if (output == "both") c("donor", "recipient") else output
  result <- vector(mode = "list", length = length(do.types))
  names(result) <- do.types

  for (type in do.types) {

    j <- ifelse(type == "donor", 1, 2)
    vnames <- if (j == 1) dnames else c(rnames, rgeo)
    vres <- if (j == 1) dres else rres

    # Output status notification via cli package
    cli::cli_inform("Harmonizing {survey[j]} ({type}) microdata at {respondent} level...")

    # Load household processed microdata (.fst) if available
    hpath <- list.files(path = "survey-processed", pattern = paste(survey[j], "H", "processed.fst", sep = "_"), recursive = TRUE, full.names = TRUE)
    dh <- if (length(hpath)) fst::fst(hpath) else NULL

    # Load person processed microdata (.fst) if available
    ppath <- list.files(path = "survey-processed", pattern = paste(survey[j], "P", "processed.fst", sep = "_"), recursive = TRUE, full.names = TRUE)
    dp <- if (length(ppath)) fst::fst(ppath) else NULL

    # Standard primary household identifier column name across processed surveys
    hid <- "hid"
    if (!"hid" %in% names(dh)) stop("Couldn't find household ID column ('hid') in donor data")

    # Parse inline adjustment formulas ('adj') to determine dependent variables to read
    adj <- H %>%
      map(~ .x[[j]]$adj) %>%
      map(~ strsplit(gsub("[^[:alnum:] ]", " ", .x), "\\s+")[[1]]) %>%
      compact() %>%
      unlist()

    # Identify complete list of required raw variables to selectively load from disk
    m <- c(vnames, adj, hid, "pid", "weight")

    # Load required subset of household variables
    k <- intersect(names(dh), m)
    dh <- if (length(k) > 1) dh[k] else NULL

    # Load required subset of person variables
    k <- intersect(names(dp), m)
    dp <- if (length(k) > 1) dp[k] else NULL

    # Sort microdata tables strictly by household ID to guarantee row alignment
    if (!is.null(dh)) dh <- arrange(dh, across(all_of(hid)))
    if (!is.null(dp)) dp <- arrange(dp, across(all_of(hid)))

    # Align household and person tables to contain identical sets of households
    if (!is.null(dh) & !is.null(dp)) {
      ids <- intersect(dh[[hid]], dp[[hid]])
      dh <- dh[dh[[hid]] %in% ids, ]
      dp <- dp[dp[[hid]] %in% ids, ]
      if (is.factor(dh[[hid]])) {
        dh[[hid]] <- factor(dh[[hid]], levels = sort(unique(dh[[hid]])))
        dp[[hid]] <- factor(dp[[hid]], levels = levels(dh[[hid]]))
      }
    }

    # Index vector mapping person records back to parent household rows
    hh.rep <- if (!HH) match(dp[[hid]], dh[[hid]]) else NULL

    # Flag reference person (pid == 1) for person-to-household aggregation routines
    vrel <- "ref__person"
    if (any(vres == "Person")) {
      dp[[vrel]] <- dp$pid == 1
    }

    # Verify key sorting alignment before processing transformations
    stopifnot({
      !is.unsorted(dh[[hid]])
      !is.unsorted(dp[[hid]])
    })

    # Sub-function: Transforms a single variable specification into harmonized output
    makeHarmony <- function(i) {

      v <- vnames[i]
      hh <- vres[i] == "Household"
      h <- H[[i]][[j]]

      if (length(h$agg) == 0) h$agg <- ""

      # Set target observation length based on requested respondent level
      N <- if (HH) nrow(dh) else nrow(dp)

      # Extract base variable data or evaluate custom string transformation formula
      if (h$adj == "") {

        x <- if (hh) dh[[v]] else dp[[v]]

      } else {

        x <- if (hh) dh else dp
        x <- mutate(x, !!v := !!rlang::parse_quo(h$adj, env = rlang::current_env()))[[v]]

      }

      # Perform categorical level mapping or continuous interval binning
      if (length(h$groups) > 1) {

        if (h$breaks[1] == "") {

          x <- h$groups[match(x, h$levels)]

        } else {

          x <- findInterval(x, h$breaks) + 1L
          x <- h$groups[x]

        }

        # Convert output vector to factor if an aggregation method is set
        if (h$agg %in% c("", "reference", "min", "max")) {
          x <- factor(x, levels = sort(unique(h$groups)), ordered = H[[i]]$ordered)
        }

      }

      # Handle cross-level respondent conversions (Person to Household or Household to Person)
      if (!hh & (HH | dres[i] == "Household")) {

        # Assign default aggregation function if unspecified
        if (h$agg == "") {
          if (is.numeric(x)) h$agg <- 'mean'
          if (is.factor(x)) h$agg <- 'reference'
          if (is.ordered(x)) h$agg <- 'max'
        }

        # Aggregate person values to household level using reference person or custom function
        if (h$agg == "reference") {

          ind <- which(dp[[vrel]])
          x <- x[ind]

        } else {

          # Fast group-by aggregation via data.table
          dt <- data.table(x, hid = dp[[hid]])
          fcall <- paste0(h$agg, "(x)")
          x <- dt[, eval(parse(text = fcall)), by = hid][[2]]

        }

        hh <- TRUE

      }

      # Replicate household-level attributes across person-level observations
      if (!HH & hh) x <- x[hh.rep]

      # Verify output validity and row count alignment
      if (anyNA(x) | length(x) != N) stop("There is a problem with output 'x' for variable ", v, " (type = ", type, ")")

      return(x)

    }

    # Execute harmonization across all variable specifications in the harmony file
    out <- lapply(X = 1:length(H), FUN = makeHarmony) %>%
      setNames(names(H)) %>%
      as.data.frame()

    # Construct primary identifiers and sampling weights data frame
    other <- list(
      if (HH) dh[[hid]] else dp[[hid]],
      if (!HH) dp[["pid"]] else NULL,
      if (HH) dh$weight else {if (is.null(dh)) dp$weight else dh$weight[hh.rep]}
    ) %>%
      setNames(c(hid, "pid", "weight")) %>%
      compact() %>%
      as.data.frame()

    # Attach state and PUMA geographic identifiers for recipient datasets
    if (type == "recipient") {
      other <- cbind(other, if (HH) dh[rgeo] else dp[rgeo])
    }

    # Ensure metadata alignment before merging
    stopifnot(nrow(out) == nrow(other))

    # Combine identifiers and harmonized feature columns
    out <- cbind(other, out)

    # Attach structural package metadata attributes to data frame
    setattr(out, "survey", survey[j])
    setattr(out, "identifier", c(hid, intersect(names(out), "pid")))
    setattr(out, "employed.vars", setdiff(c(names(dh), names(dp)), c(hid, "pid", "weight", rgeo)))
    if (type == "recipient") setattr(out, "geo.vars", rgeo)

    # Store formatted dataset in execution results list
    result[[type]] <- out
    rm(out)
    gc(verbose = FALSE)

  }

  # Assign survey names to result list
  names(result) <- survey

  # Return single data frame directly if only one output type was requested
  if (length(result) == 1) result <- result[[1]]

  # Attach harmonized variable name attribute to final object
  setattr(result, "harmonized.vars", names(H))

  return(result)

}
